### ISSUE TITLE
Reading compound types that contain arrays

### ISSUE THREAD

**Issue by PhilipDeegan** [BlueBrain/HighFive#1044]
Trying to get some traction on a discussion topic, it would be appreciated.

https://github.com/BlueBrain/HighFive/discussions/1043

**Comment by 1uc** [comment]
Seems like it would require a clean implementation of: https://github.com/BlueBrain/HighFive/issues/659 in a manner that the arrays can then be combined with other compound types.

**Comment by PhilipDeegan** [comment]
ok, it's not currently handled by the sounds of things. feel free to close as duplicate of #398

**Comment by PhilipDeegan** [comment]
we can get the data from the lib that writes the file thankfully, the source to do so including the array stuff can be seen here if you're interested

https://github.com/LLNL/SAMRAI/blob/develop/source/SAMRAI/tbox/HDFDatabase.cpp#L969

**Comment by 1uc** [comment]
Thank you that might prove useful in the future.
