### ISSUE TITLE
Multiple resizing of the data sets. 

### ISSUE THREAD

**Issue by petlist** [BlueBrain/HighFive#1071]
**Describe the bug**
Hello, and thank you for the excellent tool! 

I've been doing some benchmarking and noticed something that might potentially be a bug. `H5Dset_extent` is called twice [here](https://github.com/BlueBrain/HighFive/blob/ddcf6321a0f2528750d846f681b8f2223106abaf/include/highfive/bits/h5d_wrapper.hpp#L86). Perhaps, using the error code from the previous call could be sufficient (see below).

**Version Information**
  - HighFive: `master` branch

**Proposed (trivial) fix**
```
inline herr_t h5d_set_extent(hid_t dset_id, const hsize_t size[]) {
    herr_t err = H5Dset_extent(dset_id, size);
    if (err < 0) {
        HDF5ErrMapper::ToException<DataSetException>("Could not resize dataset.");
    }

    return err;
}
```

**Comment by 1uc** [comment]
Thank you, fixed (as suggested) here:
https://github.com/highfive-devs/highfive/pull/2
