### ISSUE TITLE
Cannot read dataset to std::vector<uint8_t>

### ISSUE THREAD

**Issue by antonysigma** [BlueBrain/HighFive#108]
I experienced a runtime error when I try to read a dataset to the std:vector<uint8_t>. Here is the error message:

`HDF5-DIAG: Error detected in HDF5 (1.10.0-patch1) MPI-process 0:
  #000: H5Dio.c line 170 in H5Dread(): can't read data
    major: Dataset
    minor: Read failed
  #001: H5Dio.c line 418 in H5D__read(): unable to set up type info
    major: Dataset
    minor: Unable to initialize object
  #002: H5Dio.c line 978 in H5D__typeinfo_init(): unable to convert between src and dest datatype
    major: Dataset
    minor: Feature is unsupported
  #003: H5T.c line 4560 in H5T_path_find(): no appropriate function for conversion path
    major: Datatype
    minor: Unable to initialize object
HDF5 error: Error during HDF5 Read:  (Datatype) Unable to initialize object`

The error goes away if I recompile the program by replacing "uint8_t" with "unsigned char". It also worked for "unsigned short".

**Comment by alkino** [comment]
Can you provide an example of the failing file?

**Comment by alkino** [comment]
Without any response I close it.
If you want to give us more details feel free to reopen it.
