### ISSUE TITLE
Collective read

### ISSUE THREAD

**Issue by iamholger** [BlueBrain/HighFive#112]
Hi,
I am happily using HighFive at NERSC to read HDF5 files. Currently, I am encountering a
performance bottleneck with parallel read and was wondering if it is possible to configure
HighFive to do collective read.

Thank you very much,
Holger

**Comment by roblatham00** [comment]
Can I expand the scope of this issue to collective read and write?   https://github.com/BlueBrain/HighFive/blob/master/include/highfive/bits/H5Slice_traits_misc.hpp#L252  passes a hard coded H5P_DEFAULT to H5Dwrite, which means no matter what property list folks set up it will never request collective I/O.  Same is true for the call to H5Dread in `SliceTraits<Derivate>::read()` https://github.com/BlueBrain/HighFive/blob/master/include/highfive/bits/H5Slice_traits_misc.hpp#L214

**Comment by 1uc** [comment]
Thank you for reporting the issue. I need a similar feature myself. Therefore, this will likely get looked at and fixed in the next few weeks.
