### ISSUE TITLE
Support non-STL types

### ISSUE THREAD

**Issue by tdegeus** [BlueBrain/HighFive#123]
I just came across your nice project. Is there any way that non-STL types that one would use for multi-dimensional arrays (e.g. Eigen, xtensor, ...) could we directly supported, without, at least seemingly, first passing through `std::vector`? I have done this in my own lightweight simple wrapper [HDF5pp](http://hdf5pp.geus.me) for Eigen (and my own n-d array library [cppmat](http://cppmat.geus.me)).

**Comment by wolfv** [comment]
@tdegeus just FYI we have a PR in xtensor-io that adds support for HDF5 using this library

**Comment by henryiii** [comment]
By the way, https://github.com/nlohmann/json has excellent support for adding converters (for json, in this case). I wonder if a similar system could be used for HighFive someday?
