### ISSUE TITLE
Ability to creating Soft link

### ISSUE THREAD

**Issue by nhatson1987** [BlueBrain/HighFive#154]
Is it possible to create a soft-link to a dataset using HighFive? 
I couldn't find such feature in current release.

Imagine it could do:
```c++
rootGroup.createSoftLink(std::string name,const HighFive::DataSet & targetDataSet)
or
rootGroup.createSoftLink(std::string name, std::string pathToDataSetObject /* /group1/group2/dataset*/)
```

Thanks in advance for any help.

**Comment by ferdonline** [comment]
Hi. This feature is still not implemented. It seems relatively easy, though, if you are willing to implement I will gladly review.

**Comment by alkino** [comment]
For future people reading this:
https://support.hdfgroup.org/HDF5/doc1.6/UG/09_Groups.html

> HDF5 also has soft links similar to UNIX soft links. A soft link is an object that has a name and a path name for the target object. The soft link can be followed to open the target of the link just like a regular or hard link. The differences are that the hard link cannot be created if the target object does not exist and it always points to the same object. A soft link can be created with any path name, whether or not the object exists; it may or may not, therefore, be possible to follow a soft link. Furthermore, a soft link's target object may be changed.
