### ISSUE TITLE
Is there a documentation for this library?

### ISSUE THREAD

**Issue by gaochenyi** [BlueBrain/HighFive#160]
Hi, the examples are helpful to begin with this wonderful library. I would like to use filter (e.g., deflate), but I could not find the corresponding example code.

Is there a documentation or a way to generate documentation?

**Comment by tristan0x** [comment]
Hello @gaochenyi 
Thank you for your interests. Unfortunately there is no documentation but unit-tests and examples for the moment. I found a usage of deflate property in the unit-tests though:

https://github.com/BlueBrain/HighFive/blob/fb79a7cbe8faf92d281bcc9f4ed85ffd1913e2c8/tests/unit/tests_high_five_base.cpp#L1290-L1301

Hope that helps.
