### ISSUE TITLE
Compiler warnings implicit type casts

### ISSUE THREAD

**Issue by gaehlerm** [BlueBrain/HighFive#164]
Hi

Thanks a lot for your great efforts, they make working with HDF5 much easier! And your unit tests are a great tutorial :-)

When compiling with MSVS we get some warnings, mainly due to type conversions. Could you please fix those?

cheers, Marco

h5attribute_misc.hpp:37, MSBuild, Priority: Normal
'return': conversion from 'hsize_t' to 'size_t', possible loss of data

h5dataset_misc.hpp:37, MSBuild, Priority: Normal
'return': conversion from 'hsize_t' to 'size_t', possible loss of data

h5dataset_misc.hpp:63, MSBuild, Priority: Normal
'return': conversion from 'haddr_t' to 'size_t', possible loss of data

h5dataspace_misc.hpp:125, MSBuild, Priority: Normal
'static_cast': truncation of constant value

h5propertylist_misc.hpp:57, MSBuild, Priority: Normal
unreachable code

h5propertylist_misc.hpp:120, MSBuild, Priority: Normal
'argument': conversion from 'size_t' to 'int', possible loss of data

h5propertylist.hpp:153, MSBuild, Priority: Normal
'initializing': conversion from 'size_t' to 'const unsigned int', possible loss of data

**Comment by tristan0x** [comment]
Thank you for your feedback @gaehlerm 
I was thinking of adding continuous integration with AppVeyor to provide good support to MSVC at some point. I think it is a good time for that.

Could you please share the exact versionS of MSVC you use?
Besides, the error lines you reported do not match the master branch. Can you please test again and update this issue?

**Comment by tristan0x** [comment]
See #146

**Comment by gaehlerm** [comment]
The last 2 warnings seem to be already fixed, but the others seem to be unaffected by the new version:

h5attribute_misc.hpp:37, MSBuild, Priority: Normal
'return': conversion from 'hsize_t' to 'size_t', possible loss of data

h5dataset_misc.hpp:37, MSBuild, Priority: Normal
'return': conversion from 'hsize_t' to 'size_t', possible loss of data

h5dataset_misc.hpp:63, MSBuild, Priority: Normal
'return': conversion from 'haddr_t' to 'size_t', possible loss of data

h5dataspace_misc.hpp:125, MSBuild, Priority: Normal
'static_cast': truncation of constant value

h5propertylist_misc.hpp:57, MSBuild, Priority: Normal
unreachable code

**Comment by gaehlerm** [comment]
We're compiling with VS2017 and all warnings enabled.

**Comment by gaehlerm** [comment]
MSVC++ 14.16 _MSC_VER == 1916 (Visual Studio 2017 version 15.9)
