### ISSUE TITLE
Writing rows of mixed types

### ISSUE THREAD

**Issue by spannella** [BlueBrain/HighFive#173]
I am looking to write a series of flat structs to hdf5. I have done this once before using the C library directly. I came across this library and I was wonder if this is possible using this wrapping?

```c++
struct record_t
{
    uint64_t timestamp:
    double value1;
    uint16_t enum1;
    uint32_t value2;
    char str_value[16];
};
```

I am looking to be able to write that into 5 columns in an HDF5 file. The C interface was a bit unpleasant to work with directly.

**Comment by ferdonline** [comment]
If the question is how to write a dataset of such a structure, it should have been made possible with the recent support for Compound types.
We would be happy to know whether you have succeeded in doing so.

**Comment by alkino** [comment]
No waiting anymore for an answer, if it's not working with Compound type, tell us by opening again this.
