### ISSUE TITLE
HighFive::File::Overwrite flag does not match comment describing behavior

### ISSUE THREAD

**Issue by contre** [BlueBrain/HighFive#189]
As per the title, the Overwrite flag for file operations does not match the comment associated with it.

https://github.com/BlueBrain/HighFive/blob/a9e0aaa7d483dc7b0321fd7df7dec58bd16190c4/include/highfive/H5File.hpp#L42-L43

Based on the that comment, I would expect that it would be defined as the below instead
```
Overwrite = ReadWrite | Create | Truncate,
```

I can create a pull request for this but I am not certain which part is "right"

**Comment by ferdonline** [comment]
Hi @contre. `Truncate` in hdf5 must be used with `H5Fcreate` which in turn implies `ReadWrite`. Hence the comment. 
So `Truncate` is the necessary condition for calling H5Fcreate. BUT H5Fcreate doesn't even accept the other flags. See https://support.hdfgroup.org/HDF5/doc1.6/UG/08_TheFile.html
So, reviewing the code, all looks right.

If you are facing any issue which seems related please describe it
