### ISSUE TITLE
Writing/Reading from a in-memory file/buffer?

### ISSUE THREAD

**Issue by wuyuanyi135** [BlueBrain/HighFive#203]
Hello,
I wonder whether HighFive supports loading or dumping the data from/into a in-memory buffer, instead of a file with given filename? 

Regards,
YW

**Comment by wuyuanyi135** [comment]
I have found a solution in [so](https://stackoverflow.com/questions/43721534/create-hdf5-file-from-scratch-using-file-image-operations-memory-mapped-hdf5-fi).
First, create a new class derived 
``` cpp
#include <highfive/H5PropertyList.hpp>
#include <hdf5.h>
class h5_memory_access : public HighFive::FileAccessProps {
 public:
  h5_memory_access(): HighFive::FileAccessProps() {
    _initializeIfNeeded();
      auto result = H5Pset_fapl_core(getId(), 1 << 22, false);
      assert(result >= 0 && "H5Pset_fapl_core failed");
  }

  void get_buffer(std::vector<uint8_t>& buf) {
      ssize_t sz=H5Fget_file_image(getId(),nullptr ,0);
      H5Fget_file_image(getId(),buf.data(),sz);
  }
};
```

Then, 
```cpp
    const h5_memory_access &props = simex::h5_memory_access();
    HighFive::File file = HighFive::File("/tmp/whatever", H5F_ACC_TRUNC, props);
```

note that the file name would be arbitrary. `/tmp/whatever` would never be created.

Finally, the data bytes can be retrieved with `get_buffer` method.

**Comment by ferdonline** [comment]
@wuyuanyi135 Thanks for sharing your solution. Besides creating a new derived class (which is the best way of doing it) I believe you could alternatively use `RawPropertyList`s.
```
RawPropertyList<PropertyType::FILE_ACCESS> lcpl;
lcpl.add(H5Pset_fapl_core, 1 << 22, false);
```

**Comment by sighingnow** [comment]
To whom who need to reading a `HighFive::File` from memory buffer, the pull request https://github.com/BlueBrain/HighFive/pull/648 would make that possible:

```cpp
  hid_t file_id = H5LTopen_file_image(const_cast<void*>(data), size,
                                      H5LT_FILE_IMAGE_DONT_RELEASE);
  hid_t root_id = H5Gopen(file_id, "/", H5P_DEFAULT);
  HighFive::File file(root_id);
```
