### ISSUE TITLE
Warnings: "Avoid unnamed objects" and "PDB was not found"

### ISSUE THREAD

**Issue by nyckmaia** [BlueBrain/HighFive#208]
I'm using the HighFive in my C++ project and always I got these kind of warnings:

![image](https://user-images.githubusercontent.com/4555404/66233673-4825ee00-e6c2-11e9-8009-d53962e4861f.png)

The 2 main ones are:
1- `Avoid unnamed objects with custom constructor and destructor`
2- `PDB 'libhdf5.pdb' was not found with 'libhdf5.lib'`

**How can I solve it?**

**Comment by nyckmaia** [comment]
I solved the first item, but the second item remains the same.

Any news about these 3 warnings related with the `*.pdb` files?

1. `libhdf5.pdb`
2. `libzlib.pdb`
3. `libszip.pdb`

**Info:** These 3 warnings appears **only** in the Windows environment (Linux is clear).
I tried it using MSVC 2019 compiler with two IDE's:

- Microsoft Visual Studio 2019
- Qt Creator IDE 4.11

**Last detail:** I download the HFD5 source code, generated a Visual Studio 2019 solution and built a `Debug` and `Release` versions.

The `Release` version doesn't generate `*.pdb` files.
The `Debug` version generate the expected `*.pdb` files, but their names are in "debug mode", like:

1. `libhdf5_D.pdb`
2. `libzlib_D.pdb`
3. `libszip_D.pdb`

**What I have to do to fix this `*.pdb` warnings in my Windows environment?**

**Comment by ferdonline** [comment]
Hello @nyckmaia 

> I solved the first item, but the second item remains the same.

Did it require changing the HighFive source code?
We don't really have developers working in the MSVC toolchain. So we would be glad to accept suggestions there

**Comment by nyckmaia** [comment]
Hi @ferdonline ...
No, in this first solution that I mention above, I do not change any HighFive source-code.
I just switch from Microsoft Visual Studio to Qt Creator IDE using MSVC 2019 and the first warning was gone.

Yes, if I can find anything to improve the MSVC toolchain, I send to you!

**Comment by alkino** [comment]
It looks that this kind of problem is not about HighFive but about the configuration of your environment.
At a time you should generate a program database? https://docs.microsoft.com/en-us/cpp/build/reference/pdb-use-program-database?view=msvc-170

as other I don't know microsoft env so much.
