### ISSUE TITLE
Create a deleteAttribute in Annotate_Traits

### ISSUE THREAD

**Issue by vic-sv** [BlueBrain/HighFive#213]
Is there a way how to delete or rewrite an attribute using HighFive?

**Comment by alkino** [comment]
The answer is no today. But HDF5 permit it, so it's possible.

See HDF5 documentation here : https://support.hdfgroup.org/HDF5/doc/RM/RM_H5A.html#Annot-Delete

As we lacking of time, feel free to do it yourself, if you want it fast.
