### ISSUE TITLE
Is it required to link against MPI explicitly?

### ISSUE THREAD

**Issue by tristan0x** [BlueBrain/HighFive#219]
https://github.com/BlueBrain/HighFive/blob/74250cf2f2a82a2b9af2f00f93475c431a2d7e09/tests/unit/CMakeLists.txt#L18

Raised by @matz-e  https://github.com/BlueBrain/HighFive/pull/183#discussion_r334404925

**Comment by alkino** [comment]
Parallel test use mpi directly: https://github.com/BlueBrain/HighFive/blob/master/tests/unit/tests_high_five_parallel.cpp#L32-L35

**Comment by matz-e** [comment]
> Parallel test use mpi directly: https://github.com/BlueBrain/HighFive/blob/master/tests/unit/tests_high_five_parallel.cpp#L32-L35

The thing is… at least on our cluster, MPI usage is done through a compiler wrapper. When I try to debug these flags, they are always empty. So I'm wondering if that flag is a holdout from ancient time or still current practice. @pramodk?

**Comment by ferdonline** [comment]
I don't think we can rely on the fact that people will do CC=mpicc. spack might do it for us (and thus the flags become empty?) but apparently there is a strong convention that says CC should be the bare compiler and MPI_LANG_COMPILER should be the wrapper so that Cmake will extract the flags.
To my mind we should comply with both ways and link with mpi libraries.

**Comment by matz-e** [comment]
> I don't think we can rely on the fact that people will do CC=mpicc. spack might do it for us (and thus the flags become empty?)

Flags are empty because `mpicc` is a wrapper including the flags. I guess there may be an MPI implementation without a wrapper script.

> but apparently there is a strong convention that says CC should be the bare compiler and MPI_LANG_COMPILER should be the wrapper so that Cmake will extract the flags.
> To my mind we should comply with both ways and link with mpi libraries.

OK. I think we can close this then, my curiosity has been satisfied, thank you!

**Comment by pramodk** [comment]
I concur with Fernando. Finding MPI through CMake and then linking explicitly is preferred than relying on user specifying CXX=mpicxx.
