### ISSUE TITLE
Exception Triggered

### ISSUE THREAD

**Issue by nyckmaia** [BlueBrain/HighFive#224]
I did a simple "copy and paste" test with Qt 5 and HighFive library and it works good!
I tested the H5Easy C++ example...

So, now I would like to use this library in my Qt C++ project.

In the middle of my code, I typed:
```
H5Easy::File file("example.h5", H5Easy::File::Overwrite);
std::vector<double> B  = { 1., 2., 3. };
H5Easy::dump(file, "/path/to/B", B, H5Easy::DumpMode::Overwrite);
```
**All compiles Ok...no errors.**

It creates the `example.h5` file... it creates the `B` vector...all ok.
But when the debugger hits the `H5::dump()` **I got this error message:**

![error](https://user-images.githubusercontent.com/4555404/66926270-1ab33b80-f004-11e9-8c55-cf101c309f09.jpg)

The Qt console points to this file:
```
highfive\bits\H5Exception_misc.hpp:63: 
warning: Debugger encountered an exception: Exception at 0x7ffc2c9e9129, code: 0xe06d7363: C++ exception, flags=0x1 (execution cannot be continued) (first chance)
```

**My questions:**
1- What can I do **to solve** this exception?
2- Is there a way to know if the H5::dump() **wrote all data with no errors?** Like a `return bool`?

**My system is:**

- OS: Windows 10 x64
- Compiler: MSVC2019 64bit
- IDE: Qt Creator IDE 4.10

**Comment by ferdonline** [comment]
Hi @nyckmaia 
If you start it from a command line, do you see any additional error messages?

**Comment by alkino** [comment]
In fact it already return the created `DataSet` or `throw` on error.
Do you need more informations?

**Comment by nyckmaia** [comment]
I'm trying to catch the throw exception:
```
try {
    // Write density vector to a HDF5 file:
    H5Easy::dump(file, "/my/path/to/density", _density, H5Easy::DumpMode::Overwrite);
} catch (HighFive::Exception e) {
    // Print error on console:
    qDebug() << e.what();
}
```
But when the debugger hits the `H5Easy::dump()` I got the expection GUI window like my first post here (image above).

Questions:
1 - So, how can I **hold the exception using HighFive?**
2- Could you please give a **short example** about the return of `H5Easy::dump()`?
I tried something like:

```
H5Easy::DataSet = H5Easy::dump(file, "/my/path/to/density", _density, H5Easy::DumpMode::Overwrite);
```
But I got a compilation error. **Could you help me?**

**Comment by nyckmaia** [comment]
Well, debugging my application I found a weird thing. Please, look this code:

```
H5Easy::File file("example.h5", H5Easy::File::Overwrite);

// Writing a simple test data:
std::vector<double> B = {1.0, 2.0, 3.0};
H5Easy::dump(file, "/my/path/to/B", B, H5Easy::DumpMode::Overwrite);

// Writing my data:
I'm passing the H5File file by reference to my 'save' method.
my_obj.save(file, "/my/path/to/density");
```
Here is the `save` method:
```
void Obj::save(H5Easy::File& file, const QString& path)
{
    try {
        // Write density vector to a HDF5 file:
        H5Easy::dump(file, path.toStdString(), _density, H5Easy::DumpMode::Overwrite);
    } catch (HighFive::Exception e) {
        qDebug() << e.what();
    }
}
```

### Now the WEIRD thing:

**This code works good and I got no errors or exceptions.**

BUT, If I remove these two lines:
```
std::vector<double> B = {1.0, 2.0, 3.0};
H5Easy::dump(file, "/my/path/to/B", B, H5Easy::DumpMode::Overwrite);
```
When the debugger hits the:
```
H5Easy::dump(file, path.toStdString(), _density, H5Easy::DumpMode::Overwrite);
```
I got the GUI exception error above in the first post here.

**Why is this happening?**

**Comment by tdegeus** [comment]
@nyckmaia Also I don't have windows nor windows experience. However looking at H5Easy_misc.hpp:63 it seems that you get an exception from `file.createGroup(...)`. Could you check the group name, manually call the function, and confirm that you hdf5 was empty?

**Comment by tdegeus** [comment]
Also, your attempt to get the dataset missed a variable name

**Comment by nyckmaia** [comment]
@tdegeus Yes, I missed the H5Easy::DataSet variable name.
So, to check if I wrote all data I'm doing something like:
```
H5Easy::DataSet ds = H5Easy::dump(file, "/my/path/to/density", _density, H5Easy::DumpMode::Overwrite);

if (ds.getElementCount() == 0) {
    // Error
}
```
**It was my mistake**...sorry about that...

**Comment by nyckmaia** [comment]
### The Weird question

```
H5Easy::File file("example.h5", H5Easy::File::Overwrite);
std::vector<double> B = {1.0, 2.0, 3.0};
file.createGroup("/my/path/to/B");
H5Easy::dump(file, "/my/path/to/B", B, H5Easy::DumpMode::Overwrite);
```
When the debugger hits the `H5Easy::dump()`, **I got the exception below.**
Please, look my screen and see the **debugger variable names:**
![debugger](https://user-images.githubusercontent.com/4555404/67009384-e56d2300-f0c1-11e9-923c-abc9e8e6cf2c.jpg)

**What I have to do now?**

**Comment by alkino** [comment]
Try it:
```C++
H5Easy::File file("example.h5", H5Easy::File::Overwrite);
std::vector<double> B = {1.0, 2.0, 3.0};
file.createGroup("/my/path/to");
H5Easy::dump(file, "/my/path/to/B", B, H5Easy::DumpMode::Overwrite);
```

**Comment by nyckmaia** [comment]
**Great! It works! Thank you** @alkino 

So, **only at the first time** when my main application calls the `H5Easy::dump()` it needs first to create a `HDF5 group` **without** the data name in the `group path`. Like:
```
file.createGroup("/my/path/to");
H5Easy::dump(file, "/my/path/to/data_name", B, H5Easy::DumpMode::Overwrite);
```

After this first time call, I can call the `H5Easy::dump()` directly, without create the `group` before it and passing the **full path + data name**. Like:
```
H5Easy::dump(file, "/other_path/new_data", data, H5Easy::DumpMode::Overwrite);`
```
That's it? If yes, This post can be closed.

Thank you again! **You are great!**

**Comment by alkino** [comment]
You need to create all group chain '**my**', '**my/path**', '**my/path/to**' only one time, after opening the file.
After that you can create the dataset **B** inside this group with **dump**.

What you did before is creating a group named **B** inside **my/path/to** and so you cannot create a dataset on this group.

**Comment by nyckmaia** [comment]
### The Last Thing

To solve this questions (create `group` before `dump` data) I modified my C++ method to this:
```
size_t Step_Density::save(H5Easy::File& file, const QString& group_path, const QString ds_name) const
{
    // Verify if the group exists:
    if (!file.exist(group_path.toStdString())) {
        // Create the HDF5 group path:
        file.createGroup(group_path.toStdString());
    }

    // Concatenate the group path with dataset name:
    QString full_path = group_path + "/" + ds_name;

    // Write data to HDF5 file:
    H5Easy::DataSet ds = H5Easy::dump(file, full_path.toStdString(), _density, H5Easy::DumpMode::Overwrite);

    // Get the number of written  elements:
    size_t el = ds.getElementCount();

    // Error checking:
    if(el == 0) {
        qDebug() << "Zero elements were written  to the HDF5 file";
    }

    return el;
}
```
But when the debugger hits the:
```
if (!file.exist(group_path.toStdString())) {
```
**I got the same exception:**
```
Exception at 0x7ffc2c9e9129, code: 0xe06d7363: C++ exception, flags=0x1 (execution cannot be continued) (first chance) at C:\Users\lamar\Desktop\rotortest\Core\third-party\highfive\bits\H5Exception_misc.hpp:63
```
**Why this is happening?**

**Comment by nyckmaia** [comment]
Now the Qt Creator IDE Debugger is **not** going to the `highfive\bits\H5Exception_misc.hpp:63` file.
I got the exception message on the IDE console, but in the debugger I can go **until here** `H5Node_traits_misc.hpp` and **not** inside the `H5Exception_misc.hpp` file;

**File:** H5Node_traits_misc.hpp

![image](https://user-images.githubusercontent.com/4555404/67018931-50bef100-f0d2-11e9-8fe3-0c7fa80fc868.png)

When I enter in this `bool NodeTraits<Derivate>::_exist(const std::string& node_name)` function, the value of `val` variable is equal to `2`.

After running this line:
```
htri_t val = H5Lexists(static_cast<const Derivate*>(this)->getId(),
                           node_name.c_str(), H5P_DEFAULT);
```
The variable `val` is equal to `-1` and I got the exception error in the Qt console:
```
Exception at 0x7ffc2c9e9129, code: 0xe06d7363: C++ exception, flags=0x1 (execution cannot be continued) (first chance) at C:\Users\lamar\Desktop\rotortest\Core\third-party\highfive\bits\H5Exception_misc.hpp:63
```

So, after that, I press the F10 key and the debugger enter inside the `if` and hits:
```
HDF5ErrMapper::ToException<GroupException>(
            std::string("Invalid link for exist() "));
```
The aplication still running **but I loose the "yellow debugger arrow" and I have to `break/stop` the debug session.**

**Please, tell me how could I help you to understand better this problem?**
I'm online all the time...

**Comment by nyckmaia** [comment]
![image](https://user-images.githubusercontent.com/4555404/67020339-6b926500-f0d4-11e9-9f66-527c2df2cd6e.png)

**Comment by nyckmaia** [comment]
Thank you @alkino for your patience and quick responses...

Please, let me know the updates and news about that...
I'm developing a commercial software where this feature is essential...

Thank you again,

**Comment by tdegeus** [comment]
@alkino @nyckmaia Sorry I don't understand your bug (or in fact I'm not entirely sure that it is highfive that is giving you problems). H5Easy was designed such that it creates all groups that you need if needed. I.e. the following works:

```cpp
#include <highfive/H5Easy.hpp>

int main()
{
  std::vector<size_t> a = {1, 2, 3};

  H5Easy::File file("test.h5", H5Easy::File::Overwrite);

  H5Easy::dump(file, "/path/a", a);
  H5Easy::dump(file, "/path/to/my/data", a);

  return 0;
}
```

Maybe you can try this code in isolation with your Qt compiler?

**Comment by nyckmaia** [comment]
This is a completly new Qt Console project, and **I got the same exception:**
![image](https://user-images.githubusercontent.com/4555404/67026455-28d58a80-f0de-11e9-9d60-58ee96251536.png)

**Detail:** In the right side, I have a debugger values. I expand the `File` variable and inside of it I have others 3 fields to expand. When I try to expand the `HighFive::AnnotateTraits` I loose all informations about the `File` variable.
![image](https://user-images.githubusercontent.com/4555404/67026828-ec565e80-f0de-11e9-8af9-fc898a06d301.png)

**My system is:**

- Windows 10 x64
- Qt Creator IDE 4.10.1
- C++ Compiler: MSVC 2019 x64

**Qt version details:**
![image](https://user-images.githubusercontent.com/4555404/67027292-aa79e800-f0df-11e9-86f2-26162e1e6bbc.png)

**Visual Studio version details**
![image](https://user-images.githubusercontent.com/4555404/67027400-db5a1d00-f0df-11e9-8d80-b705e6a62492.png)

Just to be clear, **I'm not using Visual Studio,** but the Qt C++ compiler is **MSVC**.

**Comment by nyckmaia** [comment]
For the new/clean from @tdegeus example, here is the exception file debugger:
![image](https://user-images.githubusercontent.com/4555404/67028462-b797d680-f0e1-11e9-8f6c-9a8ddef9808a.png)

**Comment by tdegeus** [comment]
@nyckmaia To me it sounds a lot like a bug of the underlying library. Can you try the library calls as in `createGroup` in isolation to zoom in?

**Comment by nyckmaia** [comment]
Of course @tdegeus, but I’m newer in HDF5 format.

Could you please give me a source-code example to do this?

**Comment by ferdonline** [comment]
There are several thing at play here. To avoid turning this conversation in some blog-like thing, allow me to give some insight.

Internally `exist()` will call a lower level `_exist()` that indeed throws an exception in case h5Lexist returned a -1. This is just to be conforming to the generic HighFive way of doing things: If an error is produced we need to gather the error information with the ErrorMapper into the Highfive exception.

So even if you indeed get an exception at that point, the high level `exist()` (without underscore) will catch the exception and return a false. That's why apparently your program finishes and writes data.

See tests_high_five_base.cpp line 1069 for a test where that is working.

*What can be wrong*:
 - MSVC. It is picky. It really is, see #172. Sometimes things break in debug mode that shouldn't.
 - QT interference
 - Windows system with low-level highfive
 - Any of the previous mixed with the fact that we use a SilenceHDF5 object to avoid printing the error stack in something we don't assume it is an error

*What you can do to debug*
 - Test without QT
 - Comment out the silencer (H5Node_traits.hpp:190) and see if something more weird is happening in low-level hdf5
 - Turn the exception to an error code. Maybe your debugger doesn't handle exceptions well

**Comment by nyckmaia** [comment]
@ferdonline thank you...

So, I tested this simple example on both IDE's:

- Qt Creator IDE 4.10.1
- Visual Studio 2019 (16.3.4)
```
// Only in Qt source-code version:
#include <QCoreApplication>

#include "Eigen/Dense"
#include "highfive/H5Easy.hpp"
#include <vector>

using Eigen::MatrixXd;

int main(int argc, char *argv[])
{
    // Only in Qt source-code version:
    QCoreApplication app(argc, argv);

    H5Easy::File file("test.h5", H5Easy::File::Overwrite);

    std::vector<double> a = { 1, 2, 3, 4, 5 };

    MatrixXd m(2, 2);
    m(0, 0) = 3;
    m(1, 0) = 2.5;
    m(0, 1) = -1;
    m(1, 1) = m(1, 0) + m(0, 1);

    H5Easy::dump(file, "/path/a", a);
    H5Easy::dump(file, "/path/to/my/data", a);
    H5Easy::dump(file, "/my/matrix", m);

    // Only in Qt source-code version:
    return app.exec();
}
```
I got **NO exception erros using Visual Studio**, and I got **3 exception** (one for each `dump()` line) using **Qt Creator IDE.**

The problem is that my developed **cross-plataform GUI is already done in Qt**, and I can't re-write it.
**Is there any possibility to mute/silence this exception using Qt Creator IDE?**
I tryed to do something like:
```
try {
    H5Easy::dump(file, "/path/a", a);
} catch (H5Easy::Exception e) {
    // Do something to hold the exception...
    const char* msg = e.what();
}
```
But when the debugger hits the `dump()` line I got the exception **without** catch it.

**Comment by nyckmaia** [comment]
To me, this difference between Qt and Visual Studio is weird because **Qt is using the same MSVC compiler and CDB debugger of Visual Studio.**

Here is the Qt IDE list of auto detected Windows **debuggers installed in my system:**
![image](https://user-images.githubusercontent.com/4555404/67042382-24b96500-f0fe-11e9-8a40-05edd708d177.png)

Here is the **Compiler and Debugger** that I'm using in this example project:
![image](https://user-images.githubusercontent.com/4555404/67042620-9c878f80-f0fe-11e9-90e9-006dda9d340b.png)


So, in my understanding, the only difference is the IDE text editor...

Well, in the end of the day, to me, the most important **NOW** is to find a way to continue using Qt Creator IDE on Windows **without getting the exceptions erros,** but if any one would like to explain to me why Qt results are different of VS results, **I will gratefull.**

**Comment by ferdonline** [comment]
> I got 3 exception (one for each dump() line)

If it was a real unhandled exception the program would immediately abort. What seems to me you have is some weird configuration in Qt creator that shows you a GUI message with the info about exceptions which are thrown, independently or not of the fact they are correctly caught.
Actually more people complaining: https://forum.qt.io/topic/95563/flood-of-exception-warnings-is-there-any-way-to-disable-this

I'm very sorry but this is not something we can fix for you. Please look if there is something you can disable or contact Qt support.
In the very last resort you can always fork and patch Highfive to never throw the exception but pass an error code among the functions instead.
