### ISSUE TITLE
Check that type is a DataSet before overwriting with H5Easy::dump

### ISSUE THREAD

**Issue by alkino** [BlueBrain/HighFive#226]
The error is really not friendly.
There is a function for it `H5Object::getType()`.
It will helps people as seen here: #224

**Comment by tdegeus** [comment]
@alkino For me to learn: What do you mean exactly, checking before `file.createDataSet`? And what is the relationship to #224?

**Comment by alkino** [comment]
In this comment https://github.com/BlueBrain/HighFive/issues/224#issuecomment-543155144
You can see that the user create a group named `/my/path/to/B` and so try to dump a `DataSet` in the same path.
The error is seen here: https://github.com/BlueBrain/HighFive/blob/master/include/highfive/bits/H5Easy_vector.hpp#L46 and is `Unable to open the dataset: inappropriate type`.
As we already check if the dataset size is good, we can also check that this is a dataset.

**Comment by tdegeus** [comment]
I wonder if it should be `H5Easy::dump` to checks for it as you state in the title or `createDataSet` , `getDataSet`, and `detail::createGroupsToDataSet`?

**Comment by alkino** [comment]
I have no idea...
