### ISSUE TITLE
Add a recursive version of H5Note_Traits::exist()

### ISSUE THREAD

**Issue by alkino** [BlueBrain/HighFive#227]
All is in the title.

[H5Lexists](https://support.hdfgroup.org/HDF5/doc/RM/RM_H5L.html#Link-Exists) try only for the last components and error if one of the middle does not exist.

We can add a recursive version to be nice with our users.

**Comment by ferdonline** [comment]
exists() check is recursive. Implemented in #152

**Comment by alkino** [comment]
I'm afraid you break this feature here:
https://github.com/BlueBrain/HighFive/pull/152/commits/a3a2f7d4f2c0dcef5304c1d5716f94b0d2a6436d

**Comment by alkino** [comment]
I add a test and it works, you're right
