### ISSUE TITLE
Imported targets: Compat w CMake version and external projects

### ISSUE THREAD

**Issue by ferdonline** [BlueBrain/HighFive#228]
With #183 we started using imported targets from Boost.

However there are two isues. 
 - FindBoost.cmake only creates the exported targets from cmake 3.5 onwards. Can we lift the CMake mininum required version to 3.5, or patch for compat with old versions?
 - When exporting/importing the target, dependencies go as-text, so HighFive dependency Boost::serialization is not resolved in the new project and we get (e.g. compiling libsonata) 
```
  Target "sonata_shared" links to target "Boost::serialization" but the
  target was not found.  Perhaps a find_package() call is missing (...)

  ld: library not found for -lBoost::serialization
```
The last issue is specially critical

**Comment by alkino** [comment]
chocolatey : 3.15.4
ubuntu LTS (Xenial) : 3.5.1
homebrew : 3.15.4
conda : 3.14.0
debian (sid) : 3.13.4

**Comment by alkino** [comment]
Can't we use cmake 3.5.1?

**Comment by alkino** [comment]
And what about: https://github.com/BlueBrain/HighFive/pull/229 ?
