### ISSUE TITLE
Spurious failure of file.exists("/");

### ISSUE THREAD

**Issue by Dekken** [BlueBrain/HighFive#232]
Hi there,

I've run into a peculiar issue.

```C++
    auto getOrCreateGroup(std::string path)
    {
        if (!hi5_.file_.exist(path))
            hi5_.file_.createGroup(path);
        return hi5_.file_.getGroup(path);
    }
```

then calling 
```C++
getOrCreate("/");
```

is fine on debian with mpich, but isn't on fedora with openmpi (not sure how relevant these things are)

in the second case, it attempts to create a group for root "/" which already exists so it fails.

**Comment by ferdonline** [comment]
Hello @Dekken thanks for reporting the problem.
It seems that hdf5 changed behavior from version 1.8 to 1.10, which are probably the versions installed in the different machines. In 1.8 it indeed returns false. See the note on behaviour changes in https://support.hdfgroup.org/HDF5/doc/RM/RM_H5L.html#Link-Exists
Anyway, we shall patch HighFive for that.
