### ISSUE TITLE
Build of 2.1 Failing on Linux due to warnings

### ISSUE THREAD

**Issue by wolfv** [BlueBrain/HighFive#243]
Hi all,

When building HighFive 2.1, it seems to fail on Linux due to warnings (in the examples): https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=85546&view=logs

Just wanted to give you a heads-up. 
I guess for the recipe, we could disable erroring on warnings. (https://github.com/conda-forge/highfive-feedstock)

Cheers!

**Comment by ferdonline** [comment]
Thanks for reporting it. Our intention is to have a better coverage for testing, but eventually those warning are too common to be considered errors. I'll create a patch relaxing it.
Would it also make sense that, in your setup, you disable the building of the examples?

**Comment by ferdonline** [comment]
@wolfv Could you please confirm that the latest patch fixes all the issues?
We might consider having a patch release with the latest few fixes.

**Comment by wolfv** [comment]
thanks, right now i am trying to build the conda packages without the examples.
