### ISSUE TITLE
Selection of a memory data space

### ISSUE THREAD

**Issue by tpadioleau** [BlueBrain/HighFive#245]
Hey,
I could not find any example for doing a selection over a data space. I have an array and I want to write only some selection of it. Is it possible to do it with HighFive ?

**Comment by alkino** [comment]
Hey,
You have three ways to do a selection before writing: https://bluebrain.github.io/HighFive/class_high_five_1_1_slice_traits.html
Slice is a traits of DataSet.
You can examples here: https://github.com/BlueBrain/HighFive/blob/master/src/examples/select_partial_dataset_cpp11.cpp#L39-L41
I hope it answer your question.

**Comment by tpadioleau** [comment]
Well it answers partially to my question.

If I understand well the Slice selection, it only acts on the file data space. From `H5Slice_traits_misc.hpp`:
```c++
DataSpace space = static_cast<const Derivate*>(this)->getSpace().clone();
if (H5Sselect_hyperslab(space.getId(), H5S_SELECT_SET, offset_local.data(),
                        stride.empty() ? NULL : stride_local.data(),
                        count_local.data(), NULL) < 0) {
    HDF5ErrMapper::ToException<DataSpaceException>(
        "Unable to select hyperslap");
}
```
for which `getSpace()` returns `_file_space`.

But what if you want to slice the memory space ? For example, let say `buffer` is a 1D float array of size 100 and you only want to dump even-spaced values (so 50 float values). Then it is not contiguous. A way to do would be to use HDF5 hyperslab to select even-spaced values. Is it something possible to do with the current HighFive API ?

**Comment by ferdonline** [comment]
According to the current design, memory-space must be contiguous.
Adding non-contiguous support requires a number of new features and API (strides, columns, offsets), and compared to other requests and our limited bandwidth we cannot give it high priority.
If you feel comfortable with the code please feel free to bootstrap something and we will review.

**Comment by tpadioleau** [comment]
I see, thank you for the reply. I am afraid I don't see any easy bootstrap for the moment.
