### ISSUE TITLE
possible race condition 

### ISSUE THREAD

**Issue by Dekken** [BlueBrain/HighFive#249]
I'm trying to write separate vectors in various MPI processes to similar but distinct paths with HighFive, and there seems to be some conflicts.

Only one path results, and it is corrupted with data from other paths.

Perhaps there's something special I'm missing or (not) doing

the following code should reproduce it

```
int main(int argc, char** argv)
{
    int mpi_rank;

    MPI_Init(&argc, &argv);
    MPI_Comm_rank(MPI_COMM_WORLD, &mpi_rank);

    auto rankstr = std::to_string(mpi_rank);
    std::vector x(40 + mpi_rank, 3 + mpi_rank);

    using namespace HighFive;
    File file("hang.5", File::ReadWrite | File::Create | File::Truncate,
              MPIOFileDriver(MPI_COMM_WORLD, MPI_INFO_NULL));

    std::string path = "/" + rankstr + "/x";
    std::cout << "writing vector to path: " << path << std::endl;
    H5Easy::detail::createGroupsToDataSet(file, path);
    file.createDataSet<double>(path, DataSpace(x.size())).write(x.data());

    MPI_Finalize();
    return 0;
}
```

from this I would expect two paths in the HDF5 file, is that wrong?

**Comment by Dekken** [comment]
guess this might come down to needing to create all datasets in all processes.

**Comment by ferdonline** [comment]
Indeed, that's a requirement of hdf5 itself, most calls have to be done by all processes, including create groups, datasets. etc.
See https://support.hdfgroup.org/HDF5/doc/RM/CollectiveCalls.html
Does it answer your doubts?

**Comment by Dekken** [comment]
Thanks for your help.
