### ISSUE TITLE
Is this working for std::vector<bool>? Thanks

### ISSUE THREAD

**Issue by kvart2006** [BlueBrain/HighFive#25]

**Comment by adevress** [comment]
Hi @kvart2006 

It is not supported currently, but would be very nice to have. This and the same mapping for boost::dynamic_bitset

If you don't feel like looking to it, I will try to have a look how to implement that in the incoming days.

Two difficulties I see are :

-  std::vector<bool> is an overload of std::vector with an implementation specific memory layout. It would probably not work (or be dangerous) to do a dummy copy to an continuous B8 / B32 dataset.

-  The H5T BITFIELD datatype is poorly documented, it would need a bit of research to have a look on how to use it "space efficient"

Adev

**Comment by ax3l** [comment]
Bool support would be great! Please be aware that [HDF5 has no native support for `bool` representation](https://support.hdfgroup.org/HDF5/hdf5-quest.html#bool).

A common way that e.g. `h5py` adopted to store bools is via [`enums`](https://support.hdfgroup.org/HDF5/doc/H5.user/Datatypes.html#Datatypes_Enum). Careful: `TRUE` and `FALSE` labels for the enums are case-sensitive.

**Comment by alkino** [comment]
Fixed by #654
