### ISSUE TITLE
Citing HighFive

### ISSUE THREAD

**Issue by iamholger** [BlueBrain/HighFive#251]
Hello, 

is there a journal article or similar that you would like people to cite that use HighFive?

Thanks!

**Comment by ferdonline** [comment]
Hello @iamholger 
HighFive was actually never published in any official conference. It eventually will, but it hasn't been a priority.
If you are publishing something and would like to mention us please refer to it as "HighFive, developed at the Blue Brain Project, EPFL". For a link you can use the GitHub page.
We are eternally thankful! 😄

**Comment by alkino** [comment]
We now have a Zenodo if you want to cite us: https://zenodo.org/records/10679738
