### ISSUE TITLE
Boost, CMake, conda-forge

### ISSUE THREAD

**Issue by tdegeus** [BlueBrain/HighFive#253]
***Updated***

There are two issues with HighFive's current CMake behaviour: one major and urgent (and hard), and one minor, not urgent. Both are related to conda (which I think to be a huge asset), see [highfive-feedstock](https://github.com/conda-forge/highfive-feedstock). The problem is that, currently, certain decisions are taken at install time. This is problematic for the conda feedstock, as the installation is invoked only on conda's CI, and the pre-build package is then shipped.

## Urgent

Currently a `HighFiveTargets.cmake` is built that that contains a bunch of system dependent file paths set at install time. For conda, the file paths relevant only for the CI environment on which the package is built, and typically have no relevance for the end user (see example below). This obviously results in compiler errors.

This should obviously be solved with CMake configuration files that search on run time and not on install time.

## Less urgent

In addition to the bug, the choice of yes/no using boost in now hard-coded in `HighFiveTargets.cmake`, leaving no choice to the end user. I am really unhappy with this. I think, instead, we should leave the choice to the end user. We should thus have either:

* Boost is enabled in the conda environment **only** if Boost is also loaded. I'm not sure if this is possible, nor how to do it. Maybe @wolfv can comment?
* Nicer could be to allow `target_link_libraries(example HighFive HighFive::Boost)` if you want to use Boost as an end user, and `target_link_libraries(example HighFive)` if you don't. This could be complemented with `target_link_libraries(example HighFive HighFive::Boost HighFive::Eigen ...)`

@ferdonline @alkino 

## Current `HighFiveTargets.cmake` on conda

```cmake
cat HighFiveTargets.cmake
# Generated by CMake

(...)
# Create imported target HighFive
add_library(HighFive INTERFACE IMPORTED)

set_target_properties(HighFive PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "NDEBUG;_FORTIFY_SOURCE=2;H5_USE_BOOST"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include;/home/tdegeus/miniconda3/envs/code_mean-field/include;/home/tdegeus/miniconda3/envs/code_mean-field/include;${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "/home/tdegeus/miniconda3/envs/code_mean-field/lib/libhdf5.so;/home/conda/feedstock_root/build_artifacts/highfive_1574264233427/_build_env/x86_64-conda_cos6-linux-gnu/sysroot/usr/lib/librt.so;/home/conda/feedstock_root/build_artifacts/highfive_1574264233427/_build_env/x86_64-conda_cos6-linux-gnu/sysroot/usr/lib/libpthread.so;/home/tdegeus/miniconda3/envs/code_mean-field/lib/libz.so;/home/conda/feedstock_root/build_artifacts/highfive_1574264233427/_build_env/x86_64-conda_cos6-linux-gnu/sysroot/usr/lib/libdl.so;/home/conda/feedstock_root/build_artifacts/highfive_1574264233427/_build_env/x86_64-conda_cos6-linux-gnu/sysroot/usr/lib/libm.so;/home/tdegeus/miniconda3/envs/code_mean-field/lib/libboost_serialization.so"
  INTERFACE_SYSTEM_INCLUDE_DIRECTORIES "/home/tdegeus/miniconda3/envs/code_mean-field/include;/home/tdegeus/miniconda3/envs/code_mean-field/include"
)
(...)
```

**Comment by tdegeus** [comment]
Another point is that is might be good to mention conda in the readme.

**Comment by alkino** [comment]
When you make the `highfive-config.cmake` you have to disable boost.
But we should clarify it, you're true.

**Comment by tdegeus** [comment]
@alkino The problem with conda is that the end user does not make `highfive-config.cmake`. I.e. she/he looses the choice, and gets stuck with the default.

**Comment by tdegeus** [comment]
@alkino I summarised the issues here. I think that this is urgent, but also involves significant work.

**Comment by tdegeus** [comment]
I add this reference to discuss improved CMake behaviour: https://pabloariasal.github.io/2018/02/19/its-time-to-do-cmake-right/

**Comment by ferdonline** [comment]
By trying to solve another problem, I think #255 almost solves the hard problem. At least I think we are on the right path.
