### ISSUE TITLE
Add support for blaze dense matrix and vector types

### ISSUE THREAD

**Issue by timzimm** [BlueBrain/HighFive#262]
Hi,

it would be very nice if HighFive could also support blaze::DenseVector and blaze::DenseMatrix
in the future.

https://bitbucket.org/blaze-lib/blaze/src/master/

**Comment by alkino** [comment]
We will not do it ourselves are we do not use it, but feel free to make a PR.

**Comment by alkino** [comment]
I close it as we will not develop it ourselves.
