### ISSUE TITLE
Error in usage of H5Eget_major under Windows

### ISSUE THREAD

**Issue by metab0t** [BlueBrain/HighFive#263]
I use this library on my Windows computer(HDF5 1.10.6, built as DLL), and tried the following simple example

```cpp
#include <highfive/H5Easy.hpp>
int main()
{
    H5Easy::File file("example.h5", H5Easy::File::OpenOrCreate);
    // (over)write and read scalar
    {
        int A = 10;
        H5Easy::dump(file, "/path/A", A, H5Easy::DumpMode::Create);
    }
    return 0
}
```
and encountered following bug in

https://github.com/BlueBrain/HighFive/blob/41b0390d6102184b1b6617cefb3fe89ef9cbe07d/include/highfive/bits/H5Exception_misc.hpp#L26

the result is freed in 

https://github.com/BlueBrain/HighFive/blob/41b0390d6102184b1b6617cefb3fe89ef9cbe07d/include/highfive/bits/H5Exception_misc.hpp#L34

It triggered exception in MSVC CRT and the log is as follows:
```
HEAP[highfive_try.exe]: Invalid address specified to RtlValidateHeap( 000002D39C6A0000, 000002D39C6DFF70 )
highfive_try.exe 已触发了一个断点。

Debug Assertion Failed!

Program: C:\code\cmakebuild\try-highfive\Debug\highfive_try.exe
File: minkernel\crts\ucrt\src\appcrt\heap\debug_heap.cpp
Line: 904

Expression: _CrtIsValidHeapPointer(block)

For information on how your program can cause an assertion
failure, see the Visual C++ documentation on asserts.

(Press Retry to debug the application)
```
 I suspect that the retured result should not be freed but there is no description in HDF5 official documentation. 
Would you have time to look into this issue?

**Comment by alkino** [comment]
Thank you for reporting this.
The documentation say that this function return a `const char*` so we should not free this.
By the way this function is deprecated since 1.8. A new function has been added in 1.8: `H5Eget_msg`.
I don't know the politics for supported version of HDF5.
