### ISSUE TITLE
Select regions. Loading particle positions into 2d matrix

### ISSUE THREAD

**Issue by mlund** [BlueBrain/HighFive#274]
I have a dataset in a hdf5 file of shape (10,6000,3) representing 10 frames each with 6000 xyz particle coordinates:
~~~ bash
h5dump output.h5 | grep -e coordinates -A 10
   DATASET "coordinates" {
      DATATYPE  H5T_IEEE_F32LE
      DATASPACE  SIMPLE { ( 10, 6000, 3 ) / ( H5S_UNLIMITED, 6000, 3 ) }
      DATA {
      (0,0,0): 2.66322, 1.55546, 3.92376,
      (0,1,0): 2.68008, 1.59389, 3.833,
      (0,2,0): 2.61028, 1.62054, 3.9782,
      ...
~~~
Is there a way to a single _frame_ into an `Eigen::MatrixXd` 2d object of shape 6000,3? This far I have tried with `H5Easy::load` but a 3d data structure is expected.

**Comment by tdegeus** [comment]
Slicing is unfortunately not supported in H5Easy. I do know how to do it with [xtensor](https://github.com/xtensor-stack/xtensor), e.g.:

```cpp
#include <xtensor/xtensor.hpp>
#include <xtensor/xview.hpp>
#include <xtensor/xio.hpp>
#include <highfive/H5Easy.hpp>

int main()
{
    H5Easy::File data("foo.h5", H5Easy::File::Read);

    xt::xtensor<double,3> x = H5Easy::load<xt::xtensor<double,3>>(data, "/bar");
    xt::xtensor<double,2> x0 = xt::view(pos, 0, xt::all(), xt::all());

    return 0;
}
```

(untested)

**Comment by ferdonline** [comment]
I'm afraid selecting a 2D regions from a given first index is not supported, I believe only getting a subregion (same dimensionality).
Anyway lookup examples for the `Dataset.select()` feature. It might help you.

**Comment by alkino** [comment]
I think this ticket goes into #305
