### ISSUE TITLE
Warnings: H5Exception_misc.hpp

### ISSUE THREAD

**Issue by nyckmaia** [BlueBrain/HighFive#276]
Hi, I'm developing a cross-platform Qt GUI Application (Linux and Windows) x64.

To mute the undesired Qt exceptions alerts (see this topic here #224 ) I commented out 2 `throw` lines. Please, look below:

**H5Exception_misc function:**
```c++
template <typename ExceptionType>
    [[noreturn]] static inline void ToException(const std::string& prefix_msg) {

        hid_t err_stack = H5Eget_current_stack();
        if (err_stack >= 0) {
            ExceptionType e("");
            ExceptionType* e_iter = &e;

            H5Ewalk2(err_stack, H5E_WALK_UPWARD,
                     &HDF5ErrMapper::stackWalk<ExceptionType>, &e_iter);
            H5Eclear2(err_stack);

            const char* next_err_msg = (e.nextException() != NULL)
                                           ? (e.nextException()->what())
                                           : ("");

            e.setErrorMsg(prefix_msg + " " + next_err_msg);

            // throw e;
        }

        // throw generic error, unrecognized error
        // throw ExceptionType(prefix_msg + ": Unknown HDF5 error");
    }
```
Now my Qt application compiles and works good, but I would like to remove 2 warnings related with this `H5Exception_misc.hpp` file:

**Warning 1:**
```
highfive/bits/H5Exception_misc.hpp:-1: 
In static member function ‘static void HighFive::HDF5ErrMapper::ToException(const string&) [with ExceptionType = HighFive::GroupException]’:
```

**Warning 2:**
```
highfive/bits/H5Exception_misc.hpp:69: 
warning: ‘noreturn’ function does return
     }
     ^
```

Could you help me?

**My setup:**
**OS:** Ubuntu 19.04 x64
**Qt Version:** 5.13.0
**IDE:** Qt Creator IDE 4.11
**Compiler:** GCC8

**Comment by alkino** [comment]
Hi,
You have to give more line for the first warning.

For the second one remove the `[[noreturn]]`.

By the way what you try to do is weird, you should catch throw.

**Comment by nyckmaia** [comment]
Thank you @alkino ...

Yes, this 2 comments are weirds to me too, but as I said in the topic #224 , I got a Qt exceptions GUI window always when I try to write a Eigen Matrix in a HDF5 file using HighFive library.
These 2 comments were "the way" that I found to use HighFive and Qt 5.

So, as I said, I'm developing a cross-platform application (Linux and Windows).
I kept these 2 comments and removed the `[[noreturn]]` and these **both warnings disapears**, but they were replaced by a new (and last) one in both environments (Windows and Linux):
```
H5PropertyList_misc.hpp:57: warning: C4715: 
'HighFive::`anonymous namespace'::convert_plist_type': not all control paths return a value
```
Do you have any ideas about **how to fix this last warning?**

My **Linux** environment:
**OS:** Ubuntu 19.04 x64
**Qt Version:** 5.13.0
**IDE:** Qt Creator IDE 4.11
**Compiler:** GCC8

My **Windows** environment:
**OS:** Windows 10 x64
**Qt Version:** 5.13.0
**IDE:** Qt Creator IDE 4.11
**Compiler:** MSVC 2019

The warning is pointed to the last line of this code below:
```
namespace {
inline hid_t convert_plist_type(PropertyType propertyType) {
    // The HP5_XXX are macros with function calls so we can't assign
    // them as the enum values
    switch (propertyType) {
    case PropertyType::OBJECT_CREATE:
        return H5P_OBJECT_CREATE;
    case PropertyType::FILE_CREATE:
        return H5P_FILE_CREATE;
    case PropertyType::FILE_ACCESS:
        return H5P_FILE_ACCESS;
    case PropertyType::DATASET_CREATE:
        return H5P_DATASET_CREATE;
    case PropertyType::DATASET_ACCESS:
        return H5P_DATASET_ACCESS;
    case PropertyType::DATASET_XFER:
        return H5P_DATASET_XFER;
    case PropertyType::GROUP_CREATE:
        return H5P_GROUP_CREATE;
    case PropertyType::GROUP_ACCESS:
        return H5P_GROUP_ACCESS;
    case PropertyType::DATATYPE_CREATE:
        return H5P_DATATYPE_CREATE;
    case PropertyType::DATATYPE_ACCESS:
        return H5P_DATATYPE_ACCESS;
    case PropertyType::STRING_CREATE:
        return H5P_STRING_CREATE;
    case PropertyType::ATTRIBUTE_CREATE:
        return H5P_ATTRIBUTE_CREATE;
    case PropertyType::OBJECT_COPY:
        return H5P_OBJECT_COPY;
    case PropertyType::LINK_CREATE:
        return H5P_LINK_CREATE;
    case PropertyType::LINK_ACCESS:
        return H5P_LINK_ACCESS;
    default:
        HDF5ErrMapper::ToException<PropertyException>(
            "Unsupported property list type");
    }
}
```

**Comment by alkino** [comment]
You have to put a return at the end of the function `convert_plist_type`.
For example: return 0;
But seriously, stop doing that, it hurts me.

You should catch your error inside the Qt app.

**Comment by nyckmaia** [comment]
You are totally right @alkino ...

I don't know what was happening here, but now I'm using the `try/catch` and moved back to the original HighFive files (removed my 2 comments described before) and it works good!

Sorry about my confusion!

**Thank you so much for your great help end patience**

I will close this topic. My last HighFive doubt is in the #208 .It would be a great help if you could have a look over there.

Thank you again!
