### ISSUE TITLE
The copy in `FixedLenStringArray<N>::operator[]` makes me want to cry ;)

### ISSUE THREAD

**Issue by tristan0x** [BlueBrain/HighFive#278]
The copy in `FixedLenStringArray<N>::operator[]` makes me want to cry ;)

With C++17, we could use `std::string_view` but this is not an option in this project yet.
But the GSL already provides `string_span` that we could probably leverage.

This ticket is about:
1. See if the usage of `string_span` is applicable and indeed prevent creating a copy of the string.
1. Ship [gsl-lite](https://github.com/gsl-lite/gsl-lite) in HighFive as a single-header file, hidden in HighFive namespace to prevent conflicts.

_Originally posted by @tristan0x in https://github.com/BlueBrain/HighFive/pull/277_

**Comment by ferdonline** [comment]
This is now mitigated by the change in API so that `operator[]` return a char* without involving a copy. The user is then free to convert it as he/she requires. For the common case to convert to a real string, the method `getString()` is also provided
