### ISSUE TITLE
Lapack++ and IT++ Support

### ISSUE THREAD

**Issue by nyckmaia** [BlueBrain/HighFive#280]
I know that HighFive can use Eigen and Boots libraries to deal with Vectors/Matrices, but I would like to know if is possible to use this library with other C++ Math libraries as:

- Lapack++ [link here](http://lapackpp.sourceforge.net/html/index.html)
- IT++: [link here](https://en.wikipedia.org/wiki/IT%2B%2B)

**Comment by alkino** [comment]
If you implement it yourself and make a PR, we will accept it.
Otherwise we don't use them right now, so will not make the development for this.
