### ISSUE TITLE
HighFiveTargetDeps.cmake

### ISSUE THREAD

**Issue by weblucas** [BlueBrain/HighFive#281]
The flag cxx_std_11 used in the  in HighFiveTargetDeps.cmake is only available from cmake 3.8. Please consider another solution.

**Comment by alkino** [comment]
It's easy to fix by using `CMAKE_CXX_STANDARD` between `3.1` and `3.8`

**Comment by weblucas** [comment]
Great. Thanks.
Solution:
-DCMAKE_CXX_STANDARD=11
