### ISSUE TITLE
Blaze Support

### ISSUE THREAD

**Issue by nyckmaia** [BlueBrain/HighFive#282]
I would like to know if HighFive have support to Blaze Math Llibrary.

**Repository link:** [link](https://bitbucket.org/blaze-lib/blaze/src/master/)

**Blaze Performance Comparison:** [link](https://www.youtube.com/watch?v=w-Y22KrMgFE)

Is there a way to use Blaze with HighFive?

**Comment by alkino** [comment]
If you implement yourself maybe.
We don't use it Blaze, so we will not make the development for this.
Feel free to submit a PR.

See #262
