### ISSUE TITLE
Writing to hdf: "static assertion failed" with Eigen matrix, mapped from OpenCV

### ISSUE THREAD

**Issue by spacescientist** [BlueBrain/HighFive#286]
* HighFive => 2.1-dev (current master)
* Eigen => 3.3.7
* OpenCV => 4.1.2, 4.2.0-dev
* Operating System / Platform => Debian 10 x86_64 GNU/Linux (4.19.0-6-amd64)
* Compiler => g++ 8.3.0

##### Detailed description

I can do an `Eigen::Map` of a `cv::Mat`, to recover the data in the form of an `Eigen::Matrix`, but I get a 'static assertion failed' as soon as I use HighFive to store that data in an hdf file.

Since the mapping appears to work, I do not understand why `H5Easy::dump` behaves differently than with any another `Eigen::Matrix`.

###### 1. Eigen::Map:
```cpp

double data[16] = {1,2,3,4, 5,6,7,8, 9,10,11,12, 13,14,15,16};
cv::Mat cvmat = cv::Mat_<double>(4,4, data);

// fixed dimensions, column-major
Eigen::Map<Eigen::Matrix4d> eigen_simple(reinterpret_cast<double*>(cvmat.data));
```

###### 2. Behaves as expected:
```cpp
std::cout << eigen_simple << '\n' << std::endl;
std::cout << eigen_simple.row(0) << '\n' << std::endl;
std::cout << eigen_simple.col(0) << '\n' << std::endl;
```
indeed prints
```
 1  5  9 13
 2  6 10 14
 3  7 11 15
 4  8 12 16

 1  5  9 13

1
2
3
4
```

###### 3. Won't compile once I try to write the data to an hdf file:
```cpp
H5Easy::File output_hdf("out_test.hdf", H5Easy::File::Overwrite);

// won't compile:
H5Easy::dump(output_hdf, "/Eigen_simple", eigen_simple, H5Easy::DumpMode::Overwrite);
```
Here's the error:
```
/usr/local/include/highfive/bits/H5Converter_misc.hpp: In instantiation of ‘HighFive::details::data_converter<Scalar, Enable>::data_converter(Scalar&, HighFive::DataSpace&) [with Scalar = Eigen::Map<Eigen::Matrix<double, 4, 4> >; Enable = void]’:
/usr/local/include/highfive/bits/H5Slice_traits_misc.hpp:227:44:   required from ‘void HighFive::SliceTraits< <template-parameter-1-1> >::write(const T&) [with T = Eigen::Map<Eigen::Matrix<double, 4, 4> >; Derivate = HighFive::DataSet]’
/usr/local/include/highfive/h5easy_bits/H5Easy_scalar.hpp:29:9:   required from ‘static HighFive::DataSet H5Easy::detail::scalar::dump_impl<T, E>::run(HighFive::File&, const string&, const T&) [with T = Eigen::Map<Eigen::Matrix<double, 4, 4> >; E = void; std::__cxx11::string = std::__cxx11::basic_string<char>]’
/usr/local/include/highfive/h5easy_bits/H5Easy_scalar.hpp:137:49:   required from ‘HighFive::DataSet H5Easy::dump(HighFive::File&, const string&, const T&, H5Easy::DumpMode) [with T = Eigen::Map<Eigen::Matrix<double, 4, 4> >; std::__cxx11::string = std::__cxx11::basic_string<char>]’
path/to/file/main.cpp:39:85:   required from here
/usr/local/include/highfive/bits/H5Converter_misc.hpp:121:52: error: static assertion failed: supported datatype should be an arithmetic value, a std::string or a container/array
         static_assert((std::is_arithmetic<Scalar>::value ||
                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                        std::is_enum<Scalar>::value ||
                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
                        std::is_same<std::string, Scalar>::value),
                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

The message is the same as in #256, but note that I am *not using Boost* here (so #261 won't help); I actually opted out when compiling HighFive. Note also that the problem remains with the current master (which already includes patch #258).

##### Full example

```cpp
#include <iostream>
#include <Eigen/Eigen>
#include <opencv2/core/eigen.hpp>
#include <highfive/H5Easy.hpp>

namespace eigentools {
	template<class T>
	using MatrixX = Eigen::Matrix<T, Eigen::Dynamic, Eigen::Dynamic, Eigen::RowMajor>; 
}


int main()
{

	double data[16] = {1,2,3,4, 5,6,7,8, 9,10,11,12, 13,14,15,16};
	cv::Mat cvmat = cv::Mat_<double>(4,4, data);

	// fixed dimensions, column-major
	Eigen::Map<Eigen::Matrix4d> eigen_simple(reinterpret_cast<double*>(cvmat.data));
	std::cout << eigen_simple << '\n' << std::endl;

	// dynamic, row-major
	Eigen::Map<eigentools::MatrixX<double>> eigen_dynamic_rowmajor(cvmat.ptr<double>(), cvmat.rows, cvmat.cols); 
	std::cout << eigen_dynamic_rowmajor << '\n' << std::endl;

	// idem
	Eigen::Map<eigentools::MatrixX<double>> eigen_dynamic_rowmajor_alt(reinterpret_cast<double*>(cvmat.data), cvmat.rows, cvmat.cols);
	std::cout << eigen_dynamic_rowmajor_alt << '\n' << std::endl;

	H5Easy::File output_hdf("out_test.hdf", H5Easy::File::Overwrite);

	// So far, so good.

	// However, putting any of these will prevent the programme from compiling:

	H5Easy::dump(output_hdf, "/Eigen_simple", eigen_simple, H5Easy::DumpMode::Overwrite);
	H5Easy::dump(output_hdf, "/EigenRowMajorFromCV", eigen_dynamic_rowmajor, H5Easy::DumpMode::Overwrite);
	H5Easy::dump(output_hdf, "/EigenRowMajorFromCV_alt", eigen_dynamic_rowmajor_alt, H5Easy::DumpMode::Overwrite);

	return 0;
}
```

**Comment by spacescientist** [comment]
Since the problem already appears with the simpler `Eigen::Matrix4d`, I thought I'd show that case. 

However what I actually intend to use are mappings to row major matrices, as in the full example:
`Eigen::Matrix<T, Eigen::Dynamic, Eigen::Dynamic, Eigen::RowMajor>; `

**Comment by alkino** [comment]
It seems that `Eigen::Map` is not a `Eigen::Matrix` so template deduction fail.

We should specifically add the support of `Map` inside HighFive.

**Comment by alexsavulescu** [comment]
At a lower level Eigen::Map is not currently supported. Maybe this could be easily tackled in the meantime at H5Easy API level, what do you think @tdegeus? 

@spacescientist have a look here, maybe you could find something to suit your needs: https://github.com/BlueBrain/HighFive/blob/master/tests/unit/tests_high_five_base.cpp#L1195

**Comment by tdegeus** [comment]
Normally you can just add the overload the H5Easy and it should work by SFINEA. If Eigen has a true parent object one could just try to change https://github.com/BlueBrain/HighFive/blob/d35a22fbc80d487a5291530def3b141e1c52ebd3/include/highfive/h5easy_bits/H5Easy_Eigen.hpp#L110 , otherwise you can simply add an overload for map. Are you willing to give it a try @alexsavulescu ?

**Comment by alexsavulescu** [comment]
Willing yes, when time permits :)

**Comment by eudoxos** [comment]
The proper way to support all Eigen types with dense storage (Including maps, as far as I can tell, expressions and Eigen::Array) would be to simply support `Eigen::DenseBase<DerivedT>`; note that Eigen uses CRTP rather than inheritance as explained https://eigen.tuxfamily.org/dox/TopicClassHierarchy.html .

**Comment by alexsavulescu** [comment]
Thank you for the insight @eudoxos

**Comment by tdegeus** [comment]
In that case one can just replace the `Eigen::Matrix<T,...>` in the dump methods with `Eigen::DenseBase<T>`. @eudoxos do you have an easy way to enforce writing in row-major? Currently I used `Eigen::Ref`, this could still work but it needs some details from `T`: https://github.com/BlueBrain/HighFive/blob/d35a22fbc80d487a5291530def3b141e1c52ebd3/include/highfive/h5easy_bits/H5Easy_Eigen.hpp#L72

**Comment by spacescientist** [comment]
Many thanks for your replies.

One comment though, regarding a replacement of the dump methods with `Eigen::DenseBase<T>`. While Matrix indeed inherits from `Eigen::DenseBase<T>`, I am actually not sure that `Eigen::Map<...>` does.

Eigen::Map<>:
https://eigen.tuxfamily.org/dox/classEigen_1_1Map.html#a3f621386d55a373f53082ac62579897e
Inheritance diagram: https://eigen.tuxfamily.org/dox/classEigen_1_1Map__inherit__graph.png

Eigen::Matrix<>:
Inheritance diagram: https://eigen.tuxfamily.org/dox/classEigen_1_1Matrix__inherit__graph.png

Eigen::DenseBase<>:
Inheritance diagram: https://eigen.tuxfamily.org/dox/classEigen_1_1DenseBase__inherit__graph.png

I am afraid I am not familiar with CRTP, but would that still be the way to go then?

**Comment by tdegeus** [comment]
My Eigen experience is limiting unfortunately. What you could do as a first step is to add you `Map` overload. We can always simplify in the future. 

One point is that Eigen is now also supported deeper down in the code, so at some point they could be removed from the Easy API.

Another point from my side you are welcome to add an openCV overload to the H5Easy API. This should be relatively straightforward. We can keep treating H5Easy as a broad API open to many many types.

**Comment by spacescientist** [comment]
It would indeed be great to have an openCV overload as well. Unfortunately I am sorry to admit that, not only am I pretty new to these two libraries myself (and with no knowledge of the internals), I am also new to HDF.

Trying to hack my way through though, I've found this, which might help with the `Eigen::Map` part: https://stackoverflow.com/questions/28587893/using-eigenmapeigenmatrixxd-as-function-argument-of-type-eigenmatrixxd/52920791#52920791 The trick is apparently to use `Eigen::Ref`. ggael is probably Gaël Guennebaud, one of the two people who started Eigen.

**Comment by tdegeus** [comment]
@spacescientist Can you try if #291 satisfies your wishes?

**Comment by spacescientist** [comment]
Sure, and thanks for your time. 

Here's an MWE with an `Eigen::Map` of a 1D `std::vector<double>`; it gives the same error.

```cpp
#include <iostream>
#include <Eigen/Eigen>
#include <highfive/H5Easy.hpp>

int main()
{
	std::vector<double> vec = {1,2,3,4, 5,6,7,8, 9,10,11,12, 13,14,15,16};
 
	Eigen::Map<Eigen::VectorXd> mapped_vector(vec.data(), vec.size());
	std::cout << mapped_vector << std::endl;

	H5Easy::File output_hdf("out_test.hdf", H5Easy::File::Overwrite);

	// So far, so good.

	// However, putting this will prevent the programme from compiling:
	H5Easy::dump(output_hdf, "/Eigen_mapped_vector", mapped_vector, H5Easy::DumpMode::Overwrite);

	return 0;
}
```

**Comment by tdegeus** [comment]
Thanks for the MWE. It should be good to go now. You could check with your OpenCV example as well.

**Comment by spacescientist** [comment]
I have and they both work; that's awesome. Thank you very much!

**Comment by tdegeus** [comment]
You're welcome!

**Comment by spacescientist** [comment]
Incidentally, since I was so happy about this and since we mentioned an opencv overload, I've tried and somehow managed to make HighFive read a dataset from an HDF file and store it as an opencv `cv::Mat_<double>`.

Beware that it's not nice at all as it stands: it still needs to be generalised beyond `double` and it's moreover incomplete (since there is only `load` for now; I haven't touched `dump`), but with it seems to work in the simple setting I used. I'm suprised `cv::Mat_` understood `rows` and `cols`, but it apparently did.

##### H5Easy_opencv.hpp (prototype)
```cpp
#ifndef H5EASY_BITS_OPENCV_HPP
#define H5EASY_BITS_OPENCV_HPP

#include "../H5Easy.hpp"
#include "H5Easy_misc.hpp"
#include "H5Easy_scalar.hpp"  // to get the basic "load_impl"

////#ifdef H5_USE_OPENCV

namespace H5Easy {

namespace detail {

namespace opencv {

// return the shape of the opencv-object as "std::vector<size_t>"
template <class T>
inline std::vector<size_t> shape(const T& data)
{
    return std::vector<size_t>(data.shape().cbegin(), data.shape().cend());
}


// load opencv-object from DataSet
template <class T>
struct load_impl
{
    static T run(const File& file, const std::string& path)
    {
        DataSet dataset = file.getDataSet(path);
        std::vector<size_t> dims = dataset.getDimensions();
        T data(dims[0], dims[1]);
        dataset.read(reinterpret_cast<double*>(data.data));
        //                             ^ ! Shouldn't be explicitly double of course TODO.
        return data;
    }
};

}  // namespace opencv

// front-end
template <class T>
struct load_impl<cv::Mat_<T>>
{
    static cv::Mat_<T> run(const File& file, const std::string& path)
    {
        return detail::opencv::load_impl<cv::Mat_<T>>::run(file, path);
    }
};


}  // namespace detail

}  // namespace H5Easy

////////#endif  // H5_USE_OPENCV

#endif  // H5EASY_BITS_OPENCV_HPP
```


##### H5Easy.hpp
```cpp
// I simply added at the end of H5Easy.hpp:
#include "h5easy_bits/H5Easy_opencv.hpp"
```

And modified the MWE to:
##### main.cpp
```cpp
#include <iostream>
#include <Eigen/Eigen>
#include <opencv2/core/eigen.hpp>
#include "highfive/H5Easy.hpp"

int main( int argc, char** argv )
{

	H5Easy::File input_hdf("out_test.hdf", H5Easy::File::ReadOnly);

	auto data_cv = H5Easy::load<cv::Mat_<double>>(input_hdf, "/EigenRowMajorFromCV");

	std::cout << data_cv << std::endl;
	std::cout << data_cv.rows << std::endl;
	std::cout << data_cv.row(2) << std::endl;

	return 0;
}

```

Could it be interesting for you to expend on this?
