### ISSUE TITLE
Easy compression in H5Easy

### ISSUE THREAD

**Issue by spacescientist** [BlueBrain/HighFive#301]
##### Detailed description:
It would be great to be able to easily enable compression when using H5Easy, especially given e.g. its Eigen support. Is there currently a way to specify `Chunking`, `Deflate` and `Shuffle` in H5Easy for Eigen, xtensor, etc..?

##### Tentative first step towards a solution:

As I couldn't find one, I've tried this (I'm not at all familiar with this, and I didn't find much on the subject at all, but #117 and `tests_high_five_base.cpp` were useful):
###### H5Easy.cpp
```cpp
// add the following:
using HighFive::Shuffle;
using HighFive::Deflate;
```
###### H5Easy_Eigen.cpp, `dump_impl`
```cpp
// create DataSet and write data
template <class T>
static DataSet dump_impl(File& file,
                         const std::string& path,
                         const T& data)
{
    using type = typename std::decay_t<T>::Scalar;
    detail::createGroupsToDataSet(file, path);

// NEW v [
    DataSetCreateProps props;
    props.add(Chunking(std::vector<hsize_t>{(hsize_t)data.rows(), (hsize_t)data.cols()})); // explicit cast to avoid complains from Eigen. Note that rows() and cols() are apparently 'long int'.
    props.add(Shuffle());
    const int deflate_level = 9; // hardcoded for now, should be given as an argument.
    props.add(Deflate(deflate_level));
    DataSet dataset = file.createDataSet<type>(path, DataSpace(shape(data)), props);
// NEW ^ ]
//    DataSet dataset = file.createDataSet<type>(path, DataSpace(shape(data)));
    detail::eigen::write(dataset, data);
    file.flush();
    return dataset;
}
```
(nb: I didn't take care of `overwrite_impl`)

###### main.cpp
```cpp
H5Easy::File output_hdf("out.hdf", H5Easy::File::Overwrite);
H5Easy::dump(output_hdf, dataset_name, eigen_map, H5Easy::DumpMode::Overwrite);
```

I've tested with a given dataset and, as a prototype, it seems work, namely: 
- the output file from the original `H5Easy::dump` is 12 Mb;
- the one using this prototype is 1.5 Mb;

and they are identical according to `h5diff` (or, equivalently, `diff` the outputs of `h5totxt`).

Cheers.

**Comment by alkino** [comment]
In fact the function should take a `DataSetCreateProps` and not the `deflate_level`.

**Comment by spacescientist** [comment]
Oh, yes sure.

**Comment by tdegeus** [comment]
It could be interesting to have the option to apply compressing. On the level of the API I think that compression should be an option (not a default). It could then be an extra option. E.g.
```cpp
H5Easy::dump(file, "/foobar", data, H5Easy::DumpOption::Compress)
```
Whereby it would be great to allow `H5Easy::DumpMode` and `H5Easy::DumpOption` in arbitrary order. 

I'm not a big expert on compression. Maybe the others should comment if there should be some finer options.

**Comment by eudoxos** [comment]
Compression level should definitely be easily accessible, deflate level 1...9 makes a *huge* difference (both in size and time). Maybe at a coarser level, like `CompressLow`, `CompressMedium`, `CompressHigh`.

**Comment by tdegeus** [comment]
I think it would be great to allow this. The API should be maybe such that in the future more than one option can be specified. Furthermore, if compression level 1-9 are standard in HDF5, it may make sense to follow the default terminology.
