### ISSUE TITLE
Update HighFive to run with HDF5 1.12.0

### ISSUE THREAD

**Issue by Mightrider** [BlueBrain/HighFive#309]
We just updated to the latest HDF5 1.12.0 release which broke some things in HIghFive. 

I will look into it and create a pull request if I manage to get it running.

**Comment by Mightrider** [comment]
So the only issue I found is that `H5O_info_t` is a different struct depending on the HDF5 Version. 
For us my fix works for HDF5 1.10.6 as well as for HDF5 1.12.0.

In the new `H5O_info_t` the member `addr` was replaced by `token` but I can't tell how this impacts existing code because we don't need ObjectInfo::getAddress().

**Comment by Dekken** [comment]
I could continue with the current code by using the following during compilation

```
-DH5Oget_info_vers=1 -DH5O_info_t_vers=1
```
