### ISSUE TITLE
Property POSITION_INDEPENDENT_CODE does not match the INTERFACE_POSITION_INDEPENDENT_CODE property 

### ISSUE THREAD

**Issue by taless474** [BlueBrain/HighFive#313]
We get this following [error](https://circleci.com/gh/STEllAR-GROUP/phylanx/34669) using HighFive
```console
-- Configuring done
CMake Error: Property POSITION_INDEPENDENT_CODE on target "fileio_primitive" does
not match the INTERFACE_POSITION_INDEPENDENT_CODE property requirement
of dependency "HighFive".
```
Isn't HighFive a header-only library? Would you please take a look at new changes and help us with a solution?

**Comment by matz-e** [comment]
Thank you for the report. Which HighFive commit did you use? I could not find any reference to the installation in your CI/code.

**Comment by taless474** [comment]
We use this command to get the HighFive:
`git clone https://github.com/BlueBrain/HighFive.git /highfive-src`
The problem started 2 days ago and I think [this commit](https://github.com/BlueBrain/HighFive/commit/64afaf531e8e42426ea560bec8f71e31bc03781a) is responsible for it.

**Comment by matz-e** [comment]
Thanks, I was suspecting that. I was able to reproduce your issue, see the mentioned PR for a fix. Sorry for the issues this caused!

**Comment by taless474** [comment]
Thank you. I tried your PR branch and it works. 
By the way, [this](https://github.com/STEllAR-GROUP/phylanx/blob/master/tools/docker/base/Dockerfile) is the complete instructions that show how we make HighFive in our Image.

**Comment by matz-e** [comment]
Thank you for the confirmation! I'll see that this will be merged quickly.
