### ISSUE TITLE
Append mode

### ISSUE THREAD

**Issue by m4ce** [BlueBrain/HighFive#320]
I was looking through the examples but didn't manage to find any information about it. Is it possible to append to an existing dataset?

**Comment by tdegeus** [comment]
I think that this is only possible if it was created as extendable. Maybe this example is relevant for you: https://github.com/BlueBrain/HighFive/blob/master/src/examples/create_extensible_dataset.cpp

**Comment by alkino** [comment]
Not waiting for an answer. If you need more explanation open this ticket again.
