### ISSUE TITLE
Can we please use the install-time dependencies by default?

### ISSUE THREAD

**Issue by matz-e** [BlueBrain/HighFive#321]
https://github.com/BlueBrain/HighFive/blob/4c70d818ed18231563fe49ff197d1c41054be592/CMakeLists.txt#L36

Simple scenario:
1. I clone :hand: 
2. I install it with `-DUSE_BOOST=OFF` or similar, since I don't have boost installed
3. I expect things to work
4. I install a library that depends on :hand:, which uses CMake, and point it to the install directory
5. Configuring said library fails, as :hand: tries to re-find Boost, which I originally disabled :boom: 

As far as I understand, re-finding dependencies was implemented due to a narrow scope originally. I'm wondering if we could have the exception be the non-default behavior and use things as installed by default.

**Comment by tdegeus** [comment]
You should be careful not to break things for conda users. On conda the package is not build by the user, and not even on the user's system. So the install-time dependencies are absolute bollux for the conda package. See also https://github.com/BlueBrain/HighFive/issues/325

W.r.t. the optional dependencies I argued before, and I argue again, that I think that it would be much cleaner to have additional targets like `HighFive::Boost` to add to your final `target_link_libraries`.

**Comment by matz-e** [comment]
> You should be careful not to break things for conda users. On conda the package is not build by the user, and not even on the user's system. So the install-time dependencies are absolute bollux for the conda package. See also #325

Is there a recipe and a dependent program/library in the Conda universe? I'm curious how you use HighFive in Conda (speaking as someone who is not really familiar with it).

One could keep the normal CMake expectancy of having install time dependencies, and a Conda recipe(s) could overwrite these by passing `-DHIGHFIVE_USE_INSTALL_DEPS:BOOL=OFF`. IMO, this would be the element of least surprise in a bare user workflow.

> W.r.t. the optional dependencies I argued before, and I argue again, that I think that it would be much cleaner to have additional targets like `HighFive::Boost` to add to your final `target_link_libraries`.

Adding a `HighFive::Boost` seems more of a barrier w.r.t. code portability. Say we have another library `X` with the same attitude, and now we have to pick between `X::Boost` and `HighFive::Boost`? If someone new starts on HighFive, how intuitive is a specialized target? And what about the components, such as `Boost::filesystem`?

**Comment by matz-e** [comment]
Ok, I found the [recipe](https://github.com/conda-forge/highfive-feedstock/blob/master/recipe/build.sh).  Would it be too much to add
```
-DHIGHFIVE_USE_INSTALL_DEPS:BOOL=OFF
```
? Seems like there are already quite a few other options there.

**Comment by tdegeus** [comment]
Good that you found it. I for one am extremely happy with the conda package. No more hassle of dependencies such as HDF5. 

Add the CMake option to the feedstock would be no obstacle at all!

**Comment by ferdonline** [comment]
As much as I dislike changing defaults, it was done here for the sake of what sounds more correct.
I would have nothing against changing it back if it wasn't for other users. As said, for ourselves, defaulting to use the INSTALL_DEPS would be great.
My rationale is that, this is a header only lib, and a good user will think "nice, header only, I can define my own options and dependencies", and I think we shouldnt trick him until he finds that actually he should have disabled some special option.

Now, the problem you report should be fixed the same way things were fixed for xtensor and Eigen. The `options(HIGHFIVE_USE_xxx)` should default to the install-time settings. So I believe, for some reason, Boost was left behind and we should fix it.

**Comment by matz-e** [comment]
>  My rationale is that, this is a header only lib, and a good user will think "nice, header only, I can define my own options and dependencies", and I think we shouldnt trick him until he finds that actually he should have disabled some special option.

That depends on the usage scenario. As a direct user, you could either disable install-time dependencies explicitly (then you know what you're doing), or pass the corresponding flag to HighFive when using it. I'm not sure how other header-only libraries do this, since most of the ones I've seen seem to be pretty light (no other dependencies).

Right now, if you use HighFive only indirect because it's a dependency in the chain somewhere, you have to find the hidden switch to set it to use install dependency *or every* user/dependent library has to set the correct options to have it behave correctly. That's pretty annoying IMO.

**Comment by 1uc** [comment]
For boost this is fixed. However, for Eigen and XTensor it still requires the consumer of the library to toggle it on. While parallel HDF5 is un-conditionally the version with which the library was configured during installation.

**Comment by 1uc** [comment]
The mess with different `cmake/*.cmake` files being installed depending on what what chosen at "compile time" (there's nothing to compile) needs cleaning up, either via targets or by changing how we organize our headers.

However, using install time dependencies doesn't seem like the way forward. Therefore, this can be closed.
