### ISSUE TITLE
doc target

### ISSUE THREAD

**Issue by lletournel** [BlueBrain/HighFive#323]
Hello,
Could it be possible to set an option for the doc target and maybe rename this target, since its name might conflict with other third parties libraries doc target (OpenMesh has the same doc name target, for example...)
Thank you !

**Comment by matz-e** [comment]
Hi, just to understand your problem a little better, I assume you're including HighFive with `add_subdirectory`? As a workaround, if you are not exporting any header functionality from HighFive, you could try the following?
```
add_subdirectory(HighFive EXCLUDE_FROM_ALL)
```

**Comment by lletournel** [comment]
Hi, we usually use add_subdirectory, concurrently with FetchContent, to manage projects with redundant dependencies. 

       FetchContent_Populate(highfive)

        # Highfive BUILD OPTIONS
        set(HIGHFIVE_USE_BOOST OFF CACHE BOOL "" FORCE)
        set(HIGHFIVE_USE_EIGEN ON CACHE BOOL "" FORCE)
        set(HIGHFIVE_USE_XTENSOR OFF CACHE BOOL "" FORCE)
        set(HIGHFIVE_UNIT_TESTS OFF CACHE BOOL "" FORCE)

        add_subdirectory(${highfive_SOURCE_DIR} ${highfive_BINARY_DIR})

I can also import HighFive as a header only lib, as a workaround to the doc target problem :

        add_library(HighFive INTERFACE)
        target_compile_definitions(HighFive INTERFACE HIGHFIVE_USE_EIGEN=ON)
        target_include_directories(HighFive INTERFACE ${highfive_SOURCE_DIR}/include)

**Comment by alkino** [comment]
So do we want to set an option? Or let the use make a workaround? What's your thoughts @ohm314 @tristan0x ?

**Comment by tristan0x** [comment]
> So do we want to set an option? Or let the use make a workaround? What's your thoughts @ohm314 @tristan0x ?

AFAIU the issue, @matz-e 's suggestion should avoid the HighFive `doc` target to be exported, thus fixing the issue.

**Comment by alkino** [comment]
So it's a `wontfix` on our side? I close it?
