### ISSUE TITLE
HDF5-DIAG from unit tests dumped, but "No errors detected"

### ISSUE THREAD

**Issue by eudoxos** [BlueBrain/HighFive#326]
I am running the current head and the unit tests (specifically: for `tests_high_five_easy`) give me this output:
```
Running 9 test cases...
HDF5-DIAG: Error detected in HDF5 (1.10.0-patch1) thread 140405351144320:
  #000: ../../../src/H5L.c line 881 in H5Lexists(): unable to get link info
    major: Symbol table
    minor: Object not found
  #001: ../../../src/H5L.c line 2962 in H5L__exists(): path doesn't exist
    major: Symbol table
    minor: Object already exists
  #002: ../../../src/H5Gtraverse.c line 869 in H5G_traverse(): internal path traversal failed
    major: Symbol table
    minor: Object not found
  #003: ../../../src/H5Gtraverse.c line 755 in H5G_traverse_real(): component not found
    major: Symbol table
    minor: Object not found
[[ REPEATED ABOUT 19 TIMES ]]
*** No errors detected
```
Is this actually expected or do I have a problem here? The discrepancy between reported errors and "No errors detected" smells, in any case.

Thanks for explanation!

**Comment by alkino** [comment]
We have test testing that things are failing. For example opening an unexisting group.
We catch the error in tests but hdf5 is verbose.
Maybe we should use `SilenceHDF5`? @ferdonline, any advice?

**Comment by eudoxos** [comment]
Not sure what `SilenceHdf5` is, the library way of disabling the messages [is](http://davis.lbl.gov/Manuals/HDF5-1.8.7/UG/13_ErrorHandling.html)

     H5Eset_auto(H5E_DEFAULT,NULL,NULL);

Where should it land? Fixture in each unit test file? Or wrap it in a nicer HighFive function?

**Comment by tdegeus** [comment]
I'm getting the same, see #331 . I cannot figure out what triggers this, my impression is an update in HDF5

**Comment by alkino** [comment]
Tell us if it still happen to you

**Comment by tdegeus** [comment]
For the me the messages disappears on the current master
