### ISSUE TITLE
There is no way to get the name of dataset or group

### ISSUE THREAD

**Issue by KerimMatlab** [BlueBrain/HighFive#329]
Hi,

`HighFive::File` has method `getName()` which returns name of the file.
But unfortunately there is no such method in `HighFive::DataSet` or `HighFive::Group` (I think neither has attribute). So it is impossible to get their names.

Best regards,
kerim

**Comment by alkino** [comment]
It has already been asked here. If you have an idea how to get the name feel free to give.
https://github.com/BlueBrain/HighFive/issues/314

**Comment by KerimMatlab** [comment]
I saw this but I thought that is a little different.
I wrote my idea in the [#314 ](https://github.com/BlueBrain/HighFive/issues/314)
