### ISSUE TITLE
Getting `File` from `DataSet`

### ISSUE THREAD

**Issue by tdegeus** [BlueBrain/HighFive#330]
Given a `DataSet` is there a way to call the `.flush()` method of the file to which it belongs (if one does not have access to the `File` in a function, but only the `DataSet`)?

**Comment by kerim371** [comment]
@tdegeus I'm looking for the same thing.

For now I've only found that it is possible to get File as a group. For example if we have any `HighFive::Group group` then we can reach root group as:
```cpp
HighFive::Group rootGroup = group.getGroup("/");
```
This group works like a File but it is a group :)

**Comment by 1uc** [comment]
This method has been implemented in the meantime in `PathTraits` and is called `getFile();`
