### ISSUE TITLE
Deprecation warning in tests

### ISSUE THREAD

**Issue by tdegeus** [BlueBrain/HighFive#334]
I'm getting the following warning:

```none
.../HighFive/tests/unit/tests_high_five_base.cpp:465:35: warning: 'getAddress' is deprecated: "Deprecated since
      HighFive 2.2. Soon supporting VOL tokens" [-Wdeprecated-declarations]
    auto addr = dataset.getInfo().getAddress();
```

**Comment by alkino** [comment]
In the test you can see:
https://github.com/BlueBrain/HighFive/blob/master/tests/unit/tests_high_five_base.cpp#L464-L465

So, if you have nothing against, I will close it.

**Comment by tdegeus** [comment]
I'll read better next time ☺️
