### ISSUE TITLE
Recursive directory structure.

### ISSUE THREAD

**Issue by PhilipDeegan** [BlueBrain/HighFive#338]
I believe we've hit an infinite loop in our CI tooling as a result of the recent additions.

https://github.com/BlueBrain/HighFive/blob/master/tests/test_project/deps/HighFive

**Comment by alkino** [comment]
@ferdonline it seems to be your patch https://github.com/BlueBrain/HighFive/commit/cfdc55a6c136f222d43b3b16f15766222f637552

**Comment by alkino** [comment]
Seems fixed by last cmake fixes. If it still occurs reopen it.
