### ISSUE TITLE
Using HighFive with HDF5 Built by CMake in Same Project

### ISSUE THREAD

**Issue by spinicist** [BlueBrain/HighFive#339]
Hello,

I have a slightly odd use-case - I want to read Eigen matrices out of an HDF5 file in an iPad app. 

To date, I have been using the HDF5 C and H5CPP libraries with my own CMake file to integrate them into my project. I do not install HDF5 somewhere first, it is directly built within the project. I also use Eigen as a submodule so I can stay close to head, rather than an installed version of Eigen.

I'd like to try HighFive, but I'm falling at the first hurdle (CMake configure) because of this setup. First it complained that it could not find `HDF5_INCLUDE_DIRS` and `HDF5_C_LIBRARIES`. I've set these in my top-level `CMakeLists.txt` with
```
get_target_property(HDF5_INCLUDE_DIRS HDF5_LIB INCLUDE_DIRECTORIES)
get_target_property(HDF5_C_LIBRARIES HDF5_LIB LIBRARY_OUTPUT_NAME)
```
However, now I have the following problems.
```
[cmake] CMake Error in HighFive/CMakeLists.txt:
[cmake]   Target "libdeps" INTERFACE_INCLUDE_DIRECTORIES property contains path:
[cmake] 
[cmake]     "/path/to/repo/eigen"
[cmake] 
[cmake]   which is prefixed in the source directory.
[cmake] 
[cmake] 
[cmake] CMake Error in external/HighFive/CMakeLists.txt:
[cmake]   Target "libdeps" INTERFACE_INCLUDE_DIRECTORIES property contains path:
[cmake] 
[cmake]     "/path/to/repo/hdf5/src"
[cmake] 
[cmake]   which is prefixed in the source directory.
```

These directories are being picked up from the respective `_INCLUDE_DIRS` variables.

My CMake is not good enough to understand these error messages properly. Any help would be much appreciated - I know I'm doing something non-standard but I don't think this should be impossible?

**Comment by tdegeus** [comment]
Hi @spinicist .

To understand your problem could you:
* Clarify where and how you install `HighFive`?
* Provide a folder structure, and specify where and how you build with `cmake`?
* Provide a minimal `CMakeLists.txt`?

If you end up providing everything as submodule, a simple workaround would simply be not to use the CMake-targets, but to hand-specify the paths and the >= C++11 version.

**Comment by spinicist** [comment]
Hello,

Thanks for getting back to me. In the end I hand-rolled my own simple HDF5 wrappers. I don't think it's worth anyone's time trying to replicate my exact setup. Long-term, Microsoft have announced that `vcpkg` will support building for iOS, and HDF5 & HighFive are in `vcpkg`, so I will try migrating to that at some point. I will close this issue.
