### ISSUE TITLE
Dump without Flushing

### ISSUE THREAD

**Issue by zfergus** [BlueBrain/HighFive#340]
Is there an alternative to `H5Easy::dump(...)` for an `Eigen::Matrix` that does not flush the file?

**Comment by tdegeus** [comment]
For the moment no. But an option can be easily added (see https://github.com/BlueBrain/HighFive/pull/337). What's the benefit of not flushing?

**Comment by tdegeus** [comment]
@zfergus The H5Easy API extension with feature an option to switch-off flushing.
