### ISSUE TITLE
make install path configurable

### ISSUE THREAD

**Issue by L0ric0** [BlueBrain/HighFive#341]
it would be nice to be able to configure the install path for include and share for the `make install` command
 at the moment the only possibility to change the install path is CMAKE_INSTALL_PREFIX and the `make install` command will put the `include` and `share` directory's into this path. it would be nice to be able to configure this paths independent from one another

**Comment by alkino** [comment]
You can do `make install DESTDIR=<...>`

**Comment by L0ric0** [comment]
will this only change the destination of the `include` directory or will `include` and `share` be placed in the same?

**Comment by alkino** [comment]
`include` and `share` will be placed together.

**Comment by L0ric0** [comment]
is it possible to split them, as i would like to have the cmake targets in the standard location and the header files in another

**Comment by ohm314** [comment]
I don't think I've seen this done usually, so I'm not sure this would be a good idea. Do you have a good use case for this? Maybe what you're trying to achieve can be done also in another way...

**Comment by L0ric0** [comment]
i'm setting up dependencys with https://github.com/cea-hpc/modules and have to support multiple versions so for the headers i have the following path: `/usr/local/include/highfive/<version>/highfive/<headerfiles>`

At the moment the `share` directory is also placed in `/usr/local/include/highfive` were it clearly doesn't belong. I would like to put is someware like `/usr/local/share/highfive/<version>/` or so.

i could always move the directory but that doesn't feel like the right way to do it.

**Comment by alkino** [comment]
The right way to do it is to use a package manager. And this package manager will move files where it belongs for your distribution.

**Comment by L0ric0** [comment]
i know but debian is a bit on the slow side and i'm forced to use it.

**Comment by alkino** [comment]
Maybe you can make your own package for debian? Is there any user repository?

**Comment by matz-e** [comment]
A package manager you say… …like [Spack](https://github.com/spack/spack)?

I think to support multiple versions, the best thing is to have different installation roots and not scatter files for several versions all over the filesystem. Like Rootless/Gobolinux did back in the day… and other systems do now.

**Comment by alkino** [comment]
Yes I think we should close this issue as we currently do not want to make such configuration possible.
