### ISSUE TITLE
Add posibility to rename objects

### ISSUE THREAD

**Issue by KerimMatlab** [BlueBrain/HighFive#344]
Hi,

As I see there is there is no method to rename groups/datasets etc...
Maybe somebody could do this. 
In original HDF5 library this is done via [H5L_MOVE(src_loc_id, src_name, dest_loc_id, dest_name, lcpl_id, lapl_id)](https://portal.hdfgroup.org/display/HDF5/H5L_MOVE) function

Best regards

**Comment by tdegeus** [comment]
Thanks for the idea. Would you be willing to have a go at it @KerimMatlab ? On place where it could fit well as a free function in the `H5Easy` API.

**Comment by KerimMatlab** [comment]
@tdegeus I'm a beginner programmer and I haven't looked yet at the high five source code. So I don't promise anything but my gut tells me that this request is up to me. So sooner or later I should give a try

**Comment by tdegeus** [comment]
Sounds great! We're here to help, so that's a good way to learn I suppose

**Comment by KerimMatlab** [comment]
@tdegeus I'm trying to understand how High Five is working?))
I added all files from  `include\highfive` directory and its subdirectory to my Qt project and I don't see any implementation wich would use native HDF5 library
Of course I'm able to use the functionality of High Five

**Comment by tdegeus** [comment]
@KerimMatlab I don't completely understand your question. But I have the impression that you still should link hdf5. Note that HighFive is not a replacement for the HDF5 library, it just wraps around it in a C++ way. Internally it calls HDF5 functions, and therefore you executable should be linked against HDF5

**Comment by KerimMatlab** [comment]
@tdegeus I added in [pull request](https://github.com/BlueBrain/HighFive/pull/346) my changes to solve this issue

**Comment by tdegeus** [comment]
Great! Will have a look

**Comment by tdegeus** [comment]
Fixed in https://github.com/BlueBrain/HighFive/pull/346
