### ISSUE TITLE
Why we don't have close() method for File/Dataset/Group?

### ISSUE THREAD

**Issue by KerimMatlab** [BlueBrain/HighFive#347]
Native hdf5 library suppose that we open object and after we done we should close it.
Is there some reasons why HighFive doesn't support such thing?

**Comment by tdegeus** [comment]
They are directly closed when the variables go out of scope (typically after the next `}`). For example if you create a file in a function the file is closed when you exit the function. Or if you write the DataSet in a loop, it closes when the loop finishes.

**Comment by KerimMatlab** [comment]
@tdegeus thank you
probably this is the reason

**Comment by alkino** [comment]
For your convenience HighFive handle the ref count of your Objects, the close is nothing less than a unref and a close if ref == 0. This is handle by HighFive directly because you don't even know if you need it.

**Comment by KerimMatlab** [comment]
I see now...
Thank you for explanation
