### ISSUE TITLE
Is packet table API supported?

### ISSUE THREAD

**Issue by baker-Xie** [BlueBrain/HighFive#354]
Dear author, is packet table API and variable length data type/composed data type supported?

**Comment by alkino** [comment]
What is packet table API?

**Comment by baker-Xie** [comment]
> What is packet table API?

It is a High level C API of HDF5

**Comment by baker-Xie** [comment]
It is a High level C API of HDF5发送自我的三星盖乐世智能手机。
-------- 原始信息 --------发件人： Nicolas Cornu <notifications@github.com> 日期: 2020/6/23  15:54  (GMT+08:00) 收件人： BlueBrain/HighFive <HighFive@noreply.github.com> 抄送： baker-Xie <ufopenguin@126.com>, Author <author@noreply.github.com> 主题： Re: [BlueBrain/HighFive] Is packet table API supported? (#354) 
What is packet table API?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/BlueBrain/HighFive/issues/354#issuecomment-647975615",
"url": "https://github.com/BlueBrain/HighFive/issues/354#issuecomment-647975615",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by alkino** [comment]
For compound type and variable length data type, it will be fully supported with: https://github.com/BlueBrain/HighFive/issues/307

For packet table API we don't schedule to add it in a short time, but feel free to make your own PR.
