### ISSUE TITLE
Add opportunity to owerwrite not only FIle but also Group/Dataset/Attribute

### ISSUE THREAD

**Issue by KerimMatlab** [BlueBrain/HighFive#355]
Hi,

As I see if for example I want to create new group I write:
`file.createGroup("myGroup");`
But if `file` already contains a group `myGroup` then we get an error. 
Is there a way to set flags like CREATE | TRUNCATE if I want to create new or open an existing?
The same concerns Attribute and Dataset

**Comment by KerimMatlab** [comment]
As I see HDF5 library doesn't support such creation property list.
Probably we could use the same flags like `File` uses (ReadOnly, ReadWrite, Create, Truncate, Excl) and based on `if/else` statements and `unlink()/removeAttribute()` we could implement such functionality.
Moreover I think optionally we could adjust `h5repack.exe` to free memory every time we `unlink` something

**Comment by matz-e** [comment]
Would that be in the scope of the library? I think this could just as well done by the clients… also, this would hide additional cost and complexity behind the API, in a way.

**Comment by KerimMatlab** [comment]
@matz-e I thought about implementing this in library. I understand that since even HDF5 library doesn't suport this functionality then it is not appropriate to add it in HDF5 wrapper library. But I think without this any library designated to work with "filesystem" is somehow incomplete

**Comment by matz-e** [comment]
I wouldn't want to give the illusion that HDF5 is like a filesystem, though, either? Unless I misunderstand you there.

**Comment by KerimMatlab** [comment]
@matz-e Probably I would have better said HDF5 is a tree model structure than filesystem.

**Comment by matz-e** [comment]
Sorry, I'm still not convinced that this is required functionality. The `Group` class provides an `unlink` method, and if one relies on repeated overwriting of datasets and/or attributes, I would wonder if the use case would be better served by a different storage model or solution.

**Comment by KerimMatlab** [comment]
@matz-e yes, probably you are right
