### ISSUE TITLE
MSVC Linking problem (Windows)

### ISSUE THREAD

**Issue by tvandera** [BlueBrain/HighFive#356]
Hi,

I wanted to use HighFive with MS Visual Studio on Windows, and ran into the following linking error:

`LINK : fatal error LNK1104: cannot open file '$<$<NOT:$<CONFIG:DEBUG>>:C:\Users\exaroot\vcpkg\installed\x64-windows\lib\hdf5.lib>' [C:\Users\exaroot\Documents\GitHub\smurff\build\cpp\Smurff\smurff.vcxproj]`

It seems the CMake generator commands are escaped:

```PS Select-String -Pattern Debug -Path *
HighFiveTargets.cmake:74:  INTERFACE_LINK_LIBRARIES "\$<\$<NOT:\$<CONFIG:DEBUG>>:C:/Users/exaroot/vcpkg/installed/x64-windows/lib/hdf5.lib>;\$<\$<CONFIG:DEBUG>:C:/Users/exaroot/vcpkg/installed/x64-windows/debug/lib/hdf5_D.lib>"
```

I have installed HighFive with **VcPkg** using my own port: https://github.com/ExaScience/smurff/tree/master/ci/vcpkg/ports/highfive

Any ideas on where to start looking?

Tom

**Comment by alkino** [comment]
You can see one space here `C:\Users\exaroot\vcpkg\installed\x64-windows\lib \hdf5.lib`, maybe this is a bad multilines copy / paste?

**Comment by tvandera** [comment]
That was indeed a copy-paste error. I have fixed it in the original comment in this issue, along with the CMake file snippet.

**Comment by tvandera** [comment]
Probably irrelevant to HighFive.

**Comment by alkino** [comment]
Sorry, to have been useless.
