### ISSUE TITLE
Add function to link a DataSet to another location (Hard Links)

### ISSUE THREAD

**Issue by L0ric0** [BlueBrain/HighFive#357]
Edit: The `hdf5` library has a function `link` which takes a type and two keys. This function links the first key to the location of the second. It would be nice to see such a function in HighFive so that one doesn't have to fall back to raw HDF5

Is it possible to link a DataSet to another location in the hdf5 file with this library?

**Comment by matz-e** [comment]
Yes, see [here](https://github.com/BlueBrain/HighFive/blob/master/src/examples/renaming_objects.cpp#L43).

**Comment by L0ric0** [comment]
well hdf5 supports `file->link(H5L_TYPE_HARD, original_key, link_key);` if that is not implemented then i will rewrite this issue as a feature request

**Comment by matz-e** [comment]
Please go ahead. I think I dropped to bare HDF5 before when needing to link like that.

**Comment by 1uc** [comment]
@Quark-X10 thanks for implementing the feature.
