### ISSUE TITLE
allow path objects to be used for keys

### ISSUE THREAD

**Issue by L0ric0** [BlueBrain/HighFive#359]
as hdf5 key are modled like filesystem paths it would be nice to be able to use `boost::filesystem::path` or/and `std::filesystem::path` as parameters for all functions as this makes key manipulation far more convinient

**Comment by alkino** [comment]
It looks like a good idea! Maybe only the `std` for beginning, but I personally think it should be possible.

**Comment by L0ric0** [comment]
for boost at last i know that you can tell it which format you want it to return for the `std` i don't realy know

**Comment by alkino** [comment]
For `std`, the `generic_` are use to output POSIX path from all systems: https://en.cppreference.com/w/cpp/filesystem/path/generic_string

**Comment by 1uc** [comment]
This would duplicate parts of our API (requiring twice the number of tests); use a concept for something similar but distinct to specify the "path" of an HDF5 dataset/group; and opens the possibility for bugs related to certain OSes and conversion between UTF-* variant seems to be implementation defined.
