### ISSUE TITLE
Add support for C++11 list initialization  inside the slice_write method

### ISSUE THREAD

**Issue by adevress** [BlueBrain/HighFive#36]
It would be nice to have a list initialization  support for the write method.
This would allow to have the following syntax for writing dataset.

d.write({ 1, 2, 3, 4 });

And it would :
- allow automatic type deduction
- avoid useless memory allocation

**Comment by 1uc** [comment]
To me this looks like something that is useful only when writing very short arrays to a dataset. The cost of the additional complexity, implementation (incl. comprehensive tests) and maintenance isn't, to me, worth the difference to performing:
```
d.write(std::array{1, 2, 3, 4});
```
