### ISSUE TITLE
New (minor) release

### ISSUE THREAD

**Issue by tdegeus** [BlueBrain/HighFive#361]
Can there be a new (minor) release such that conda-forge package gets the new H5Easy features? Maybe after merging https://github.com/BlueBrain/HighFive/pull/343

**Comment by matz-e** [comment]
Seconded!

**Comment by alkino** [comment]
Without problem.
2.2.2
You can make it yourself I think.
take care of changelog, and release note.

**Comment by alkino** [comment]
https://github.com/BlueBrain/HighFive/releases You have to forge it now ;)

**Comment by alkino** [comment]
You have been quick ^^
