### ISSUE TITLE
New (major) release

### ISSUE THREAD

**Issue by alkino** [BlueBrain/HighFive#362]
I'm rewriting the type read / write to be recursive.
I'm breaking API for that.
`void read<T>(T& value)` => `T read<T>()`
Do you think it is valuable to remove the old useless and weird (raw pointers) API?

By the way, at the end @tdegeus we should remove your own parser of type in H5Easy to use the new powerful one from core. Do you agree on that?

**Comment by tdegeus** [comment]
I could imagine that people do use the raw-pointer version (even though maybe one shouldn't use raw-pointers in C++) if one interfaces with some custom class class. So it might be worth keeping, or at least probing with a warning before removing.

Yes, I think it is a good idea to centralise the overloads! I would be happy to help.

**Comment by tdegeus** [comment]
It might be good to have some entry-point for iterators too. I was wondering if you could outline the new API?

**Comment by alkino** [comment]
Hm, I think we should stop supporting C-array because it's a nightmare (you can still use`read(T*)` and `write_raw(T*)`).
`read(T&)` will disappear for `auto var = read<T>()`

New major version

**Comment by alkino** [comment]
We will produce a new major version, because:

- |FixedLenStringArray| will disapear in favor of `std::array_t<FixedLengthString, N>`
