### ISSUE TITLE
hdf5-1.8 not supported?

### ISSUE THREAD

**Issue by mmmaat** [BlueBrain/HighFive#368]
Hi, thank you for this great library!

Using the default hdf5 centos7 package (which is version 1.8) I get an error using the `group.createAttribute` method. It works fine with hdf5 1.10 or 1.12.

In HighFive documentation it is not clear which hdf5 version is supported... but maybe you can just replace https://github.com/BlueBrain/HighFive/blob/40f7624b37e1386fe1ac1885beb474e9346311d6/CMake/HighFiveTargetDeps.cmake#L11 by `find_package(HDF5 1.10 REQUIRED)` to ask for *at least* the 1.10 version.

If you are interested in the `createAttribute` bug let me know I'll build a minimal example.

**Comment by alkino** [comment]
We have no minimal version of hdf5 yet, but we plan to support several.
We should discuss, it's not clear.

**Comment by ferdonline** [comment]
@mmmaat Could you please share the error you get? If not too hard we would like to support 1.8 as well.

**Comment by mmmaat** [comment]
Well... I'm sorry I moved to 1.10 by now and cannot retrieve the minimal example I was talking about...

**Comment by alkino** [comment]
In fact we fix the last minor version to support 1.8, if you still have problem, reopen the ticket
