### ISSUE TITLE
Make existence checks less verbose on stdout/stderr

### ISSUE THREAD

**Issue by emmenlau** [BlueBrain/HighFive#376]
We're happily using HighFive with xtensor. Everything generally works really well. Thanks for the great work!

One thing that recently became a bit of a problem is the verbose logging to stdout/stderr. I think the logging in HDF5 comes mostly from here, in `_exist()`: https://github.com/BlueBrain/HighFive/blob/9a5f707c4b427a5854bb7ca0426bdc7221173b4a/include/highfive/bits/H5Node_traits_misc.hpp#L198

There is a nice scope guard `SilenceHDF5` in that method, that seems very helpful. But as far as I could see, this scope guard will do either one of two things:
 * It either logs errors to stdout/stderr, or
 * It throws an exception.

For my personal taste, both options are not great for an existence check. This is because I am under the impression that an existence check may reasonably often fail, otherwise I would not have needed to check in the first place. But whatever code was executing the existence check seems to account for such behavior, since it was running the check in the first place. But if the code is safe (which I assume due to aforementioned point), then I assume neither an exception nor a warning are required.

Does my thinking make sense?

If you agree, then I would prefer to make this check less verbose. But what would be your preferred choice to do this? Add an alternative to `SilenceHDF5` that will neither throw nor print, for use cases like this?

**Comment by emmenlau** [comment]
We're hitting this issue again. Help or feedback would be great!

**Comment by alkino** [comment]
We agree with you on that.

Could you submit a PR with SilenceHDF5 always initialized with true in this function?

Regards

**Comment by ohm314** [comment]
Dear @emmenlau ,
I just wanted to add that since we are currently a little short on resources, we would be more than happy to get a patch from you that we can then work together on reviewing and merging. Your thinking makes sense and I would fix as @alkino suggested.
Please feel free to mention me or @alkino on your PR so that we notice and quickly review it!

Thanks!
