### ISSUE TITLE
Cant declare a simple HighFive::File class variable

### ISSUE THREAD

**Issue by wajihullahbaig** [BlueBrain/HighFive#390]
Thank you for this wonderful repo. I am new to this repo and HDF format so my question can be naive.
I wanted to declare a simple HightFive::File type variable. I need to retain it as a  class member but seems that for the explicit constructor of HighFive::File I am unable to do so. 
Here is part of the long list of errors that occur

`o matching function for call to ‘HighFive::File::File()’`

I wonder if it is permissible to declare? What is the work around for this?
Thank you!

**Comment by matz-e** [comment]
Hello, thanks for the kind words!

IIRC, we don't want to have files in an inconsistent state, so you should initialize the file object in the constructor. I think this should work:
```
class Foo {
    HighFive::File file_;
public:
    Foo(const std::string& filename) : file_(filename) {}
}
```
See also [here](https://github.com/BlueBrain/MVDTool/blob/master/include/mvdtool/bits/mvd3_misc.hpp#L142).

But you will not be able to have a default constructor. If you need that, I would recommend using a `shared_ptr` or `unique_ptr`.

**Comment by alkino** [comment]
@matz-e is right, as you can see in the reference: https://bluebrain.github.io/HighFive/class_high_five_1_1_file.html, the only accepted constructor take at least a filename.

**Comment by alkino** [comment]
Feel free to open again this issue if you have more questions.

**Comment by wajihullahbaig** [comment]
> `shared_ptr`

Thank you for the reply. I see the reason now for such explicit constructors. 
I will try your suggestions on shared pointers. @alkino Thank you to you too.
