### ISSUE TITLE
Link to hdf5 debug libraries when build in debug mode

### ISSUE THREAD

**Issue by L0ric0** [BlueBrain/HighFive#392]
At the moment HighFive links to the hdf5 release libraries when build in debug mode. this kills setups with vcpkg  when also linking against the hdf5 libs as `libhdf5.a` and `libhdf5_debug.a` are linked against, which leads to duplicate symbols.

**Comment by alkino** [comment]
The problem does not seem to be our side anymore.
https://github.com/microsoft/vcpkg/issues/14631#issuecomment-745806903
So I close this.
Open again if I misunderstand it.
