### ISSUE TITLE
How HighFive decides wich HDF5 library wrap over when there are few HDF5 libs in the project

### ISSUE THREAD

**Issue by kerim371** [BlueBrain/HighFive#393]
Hi,

I'm trying to use HighFive as a subdir in[ Slicer 3D](https://github.com/Slicer/Slicer) project.
Slicer uses ITK and VTK libs and those libs use name-mangled HDF5 lib.
If I try to add HighFive to my subproject I get many link errors like:

- create_attribute_string_integer.obj:- 1: error: LNK2019: unresolved external symbol __imp_itk_H5open referenced in function "class HighFive::DataType __cdecl HighFive::create_and_check_datatype<int>(void)" (??$create_and_check_datatype@H@HighFive@@YA?AVDataType@0@XZ) [C:\S\extensions\MSV-build\HighFive\src\examples\create_attribute_string_integer_bin.vcxproj]

- create_attribute_string_integer.obj:- 1: error: LNK2019: unresolved external symbol __imp_itk_H5check_version referenced in function "public: __cdecl HighFive::File::File(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,unsigned int,class HighFive::PropertyList<2> const &)" (??0File@HighFive@@QEAA@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@IAEBV?$PropertyList@$01@1@@Z) [C:\S\extensions\MSV-build\HighFive\src\examples\create_attribute_string_integer_bin.vcxproj]

- create_attribute_string_integer.obj:- 1: error: LNK2019: unresolved external symbol __imp_itk_H5Iis_valid referenced in function "public: class HighFive::Attribute __cdecl HighFive::AnnotateTraits<class HighFive::DataSet>::createAttribute<int>(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class HighFive::DataSpace const &)" (??$createAttribute@H@?$AnnotateTraits@VDataSet@HighFive@@@HighFive@@QEAA?AVAttribute@1@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBVDataSpace@1@@Z) [C:\S\extensions\MSV-build\HighFive\src\examples\create_attribute_string_integer_bin.vcxproj]

I feel like HighFive tries to wrap over ITK's HDF5 lib despite of I link or not link my standard HDF5 library (stardard built library with cmake-GUI) to my project.

I tried to figure out how HighFive searches for HDF5 lib but I didn't understand. None of HighFive include files doesn't have `#include <hdf5.h>`. 
So how HighFive "understands" wich HDF5 lib wrap over? Or more generally, how to solve my link error problem?

**Comment by tdegeus** [comment]
I presume that you are compiling with the help of CMake. In that case CMake is just using:
https://github.com/BlueBrain/HighFive/blob/e582076fb5b4dd654738c24c2d40517d11512ca6/CMake/HighFiveTargetDeps.cmake#L13
If you have several installations I would suggest to instead use different environments to separate them. Otherwise you should change the search order of CMake

**Comment by alkino** [comment]
It's not a HighFive question, but a CMake question that has already be answered by @tdegeus 

So I close, open it again if I misunderstood.
