### ISSUE TITLE
append to dataset

### ISSUE THREAD

**Issue by plusangel** [BlueBrain/HighFive#399]
Dear all,

I'm using the library so far without any issues.
At this point, I'm able to create a dataset and dump an Eigen Matrix, as expected.

At this point, in my application, after an internal procedure, I receive a new Matrix and I need to append to the existing dataset back to the existing matrix and this goes on and on.

How could I append new data to the existing dataset?
Is there any way?

**Comment by tdegeus** [comment]
You will need to create the dataset such that it can be extend. To see how it is done in HighFive you can check [this example](https://github.com/BlueBrain/HighFive/blob/master/src/examples/create_extensible_dataset.cpp). Other reference include for example [h5py's documentation](https://docs.h5py.org/en/stable/high/dataset.html#resizable-datasets).

I don't think that an existing dataset can be extended if it was not created to be extendable (but I might be mistaken)

**Comment by plusangel** [comment]
Thank you, Tom!
One more time, you saved the game.

I was influenced by Python and looking for append instead of dataspace resize.
Seems reasonable.

Consider the ticket close. Thank you again :)

**Comment by tdegeus** [comment]
You are welcome!
