### ISSUE TITLE
read and write std::vector<std::string> support

### ISSUE THREAD

**Issue by xiamr** [BlueBrain/HighFive#413]
read and write vectors of std::string , such as :

```
ATTRIBUTE "layer_names" {
      DATATYPE  H5T_STRING {
         STRSIZE 7;
         STRPAD H5T_STR_NULLPAD;
         CSET H5T_CSET_ASCII;
         CTYPE H5T_C_S1;
      }
      DATASPACE  SIMPLE { ( 6 ) / ( 6 ) }
      DATA {
      (0): "dense\000\000", "dense_1", "dense_2", "dense_3", "dense_4",
      (5): "dense_5"
      }
   }
```

**Comment by alkino** [comment]
Here is an example of writing `std::vector<std::string>` : https://github.com/BlueBrain/HighFive/blob/master/src/examples/read_write_dataset_string.cpp

**Comment by xiamr** [comment]
But when I run the folllowing code: 


> try {
>         File file(FILE_NAME, File::ReadWrite | File::Create | File::Truncate);
> 
>         std::vector<std::string> string_list{"very important Dataset !", "hello", "world" };
> 
>         Attribute a = file.createAttribute<std::vector<std::string>>(
>                     ATTRIBUTE_NAME_NOTE, DataSpace::From(string_list));
>         a.write(string_list);
> 
>     } catch (Exception& err) {
>         // catch and print any HDF5 error
>         std::cerr << err.what() << std::endl;
>     }


Just got only one string in the file:

`HDF5 "create_attribute.h5" {
GROUP "/" {
   ATTRIBUTE "note" {
      DATATYPE  H5T_STRING {
         STRSIZE H5T_VARIABLE;
         STRPAD H5T_STR_NULLTERM;
         CSET H5T_CSET_UTF8;
         CTYPE H5T_C_S1;
      }
      DATASPACE  SCALAR
      DATA {
      (0): "very important Dataset !"
      }
   }
}
}
`

**Comment by tdegeus** [comment]
Can you check with 
```cpp
H5Easy::dumpAttribute(file, "/mydataset", "myattribute", string_list);
```
? 
It explicitly passes the size of `string_list`

**Comment by xiamr** [comment]
It seems not work properly `H5Easy::dumpAttribute: path not a DataSet
Path: /
Filename: create_attribute.h5
`
It not belongs to any DataSet

**Comment by tdegeus** [comment]
You'd have to have a dataset. E.g.
```cpp
H5Easy::dump(file, "/mydataset", string_list);
H5Easy::dumpAttribute(file, "/mydataset", "myattribute", string_list);
```

**Comment by ferdonline** [comment]
For some reason it assumed a scalar value, so I we will need to look into that. Thanks for reporting @xiamr

**Comment by jorblancoa** [comment]
Hi @xiamr,
I had a look at this and managed to make it work as expected.
The only thing you have to change in your code is this:
```
Attribute a = file.createAttribute<std::vector<std::string>>(
                    ATTRIBUTE_NAME_NOTE, DataSpace::From(string_list));
```
For this:
```
Attribute a = file.createAttribute<std::string>(
                    ATTRIBUTE_NAME_NOTE, DataSpace::From(string_list));
```
After the change I get:
```
HDF5 "create_attribute.h5" {
GROUP "/" {
   ATTRIBUTE "note" {
      DATATYPE  H5T_STRING {
         STRSIZE H5T_VARIABLE;
         STRPAD H5T_STR_NULLTERM;
         CSET H5T_CSET_UTF8;
         CTYPE H5T_C_S1;
      }
      DATASPACE  SIMPLE { ( 3 ) / ( 3 ) }
      DATA {
      (0): "very important Dataset !", "hello", "world"
      }
   }
}
}
```
In order to read it you can just simply:
```
std::vector<std::string> result;
 a.read(result);
```
Hope it helps!
