### ISSUE TITLE
Urgent: CMake strategy for dependencies fully broken for newer CMake

### ISSUE THREAD

**Issue by tdegeus** [BlueBrain/HighFive#415]
I have a `CMakeLists.txt` that includes
```cmake
set(HIGHFIVE_USE_XTENSOR 1)
set(HIGHFIVE_USE_BOOST 0)
find_package(HighFive REQUIRED)
```

Now I'm getting:
```
CMake Warning (dev) at /Users/tdegeus/opt/miniconda3/envs/test/share/HighFive/CMake/HighFiveConfig.cmake:50 (option):
  Policy CMP0077 is not set: option() honors normal variables.  Run "cmake
  --help-policy CMP0077" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

  For compatibility with older versions of CMake, option is clearing the
  normal variable 'HIGHFIVE_USE_BOOST'.
Call Stack (most recent call first):
  CMakeLists.txt:7 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at /Users/tdegeus/opt/miniconda3/envs/test/share/HighFive/CMake/HighFiveConfig.cmake:52 (option):
  Policy CMP0077 is not set: option() honors normal variables.  Run "cmake
  --help-policy CMP0077" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

  For compatibility with older versions of CMake, option is clearing the
  normal variable 'HIGHFIVE_USE_XTENSOR'.
Call Stack (most recent call first):
  CMakeLists.txt:7 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

HIGHFIVE 2.2.2: (Re)Detecting Highfive dependencies (HIGHFIVE_USE_INSTALL_DEPS=NO)
-- HDF5 C compiler wrapper is unable to compile a minimal HDF5 program.
-- Found HDF5: /Users/tdegeus/opt/miniconda3/envs/test/lib/libhdf5.dylib (found version "1.10.6")
CMake Error at /Users/tdegeus/opt/miniconda3/envs/test/share/cmake-3.19/Modules/FindPackageHandleStandardArgs.cmake:218 (message):
  Could NOT find Boost (missing: Boost_INCLUDE_DIR system serialization)
Call Stack (most recent call first):
  /Users/tdegeus/opt/miniconda3/envs/test/share/cmake-3.19/Modules/FindPackageHandleStandardArgs.cmake:582 (_FPHSA_FAILURE_MESSAGE)
  /Users/tdegeus/opt/miniconda3/envs/test/share/cmake-3.19/Modules/FindBoost.cmake:2208 (find_package_handle_standard_args)
  /Users/tdegeus/opt/miniconda3/envs/test/share/HighFive/CMake/HighFiveTargetDeps.cmake:25 (find_package)
  /Users/tdegeus/opt/miniconda3/envs/test/share/HighFive/CMake/HighFiveConfig.cmake:67 (include)
  CMakeLists.txt:7 (find_package)
```

So there is no way to customise the dependencies anymore. I have to compile with Boost even if I entirely not use it.
See https://cmake.org/cmake/help/latest/policy/CMP0077.html

I know I have been complaining about this several times before, but now the time has truly come to move towards a modular HighFive target!

**Comment by matz-e** [comment]
I was just looking at your old PR an hour ago :)

**Comment by tdegeus** [comment]
I think it was mostly done @matz-e . I remember that I spent quite some effort.

**Comment by matz-e** [comment]
It looked nice at first look. I'll have to give another pass in-depth, and I myself would not be too concerned about breaking compatibility. Just bump the version number accordingly

**Comment by alkino** [comment]
https://github.com/BlueBrain/HighFive/runs/2131219811

BOOST disabled, not installed and not problem with cmake 3.19

What are we doing wrong?

**Comment by tdegeus** [comment]
Did you set the policies also to 3.19 by starting with

```cmake
cmake_minimum_required(VERSION 3.19)
```
Me, I had to accept also older policies just for HighFive, by setting
```cmake
cmake_minimum_required(VERSION 3.1..3.19)
```

Personally, I did not know that it is not so much the version of CMake that determines how the script is interpreted as to much 
`cmake_minimum_required`.

**Comment by tdegeus** [comment]
Also not that my error occurs on the user side. I.e. when you first install HighFive and its CMake target, and then try to use it

**Comment by alkino** [comment]
Did you try with `option(HIGHFIVE_USE_BOOST "Disable Boost in HighFive" OFF)` in your main project?

**Comment by tdegeus** [comment]
That I did not

**Comment by tdegeus** [comment]
For reference, I find that over at pybind11 they are doing their CMake well. I think that this could serve as an example for HighFive : https://pybind11.readthedocs.io/en/latest/cmake/index.html 

(In fact things are not much different from in my rejected PR from a while ago)
