### ISSUE TITLE
How to read variable length arrays

### ISSUE THREAD

**Issue by WanXinTao** [BlueBrain/HighFive#439]
I have an h5 file
```
DATASET "foo" {
    DATATYPE H5T_VLEN { H5T_STD_I32LE }
    DATASPACE SIMPLE { ( 2 ) / ( 2 ) }
    DATA {
        (0): (1), (1, 2)
    }
}
```

How should I read it, is there a similar example

**Comment by WanXinTao** [comment]
@alkino I want to read the data shown in the picture above

**Comment by WanXinTao** [comment]
Can you provide a demo, thank you very much

**Comment by ferdonline** [comment]
AFAIK var length non-string arrays are still not supported.

**Comment by maxnoe** [comment]
This is a duplicate of #369

**Comment by alkino** [comment]
Thanks ;)
