### ISSUE TITLE
compiler config error

### ISSUE THREAD

**Issue by PhilipDeegan** [BlueBrain/HighFive#446]
Hi there,

I'm trying to use the PGI/openacc compiler suite from nvidia and having difficulties with this line here:
https://github.com/BlueBrain/HighFive/blob/f2a6b1d29ff2f8ba1c08f85916e8b5fbe83763b8/CMake/config/CompilerFlagsHelpers.cmake#L38

in my case "CMAKE_${COMPILER_LANGUAGE}_COMPILER_ID" = PGI

I commented out fatal_error and stopped building the examples and things continued to work as expected

**Comment by tdegeus** [comment]
This does not address your bug, but it might open a way for more transparent and potentially faster support. 

When I was proposing to reform CMake support here, I must say that I felt that all of these functions simply did not belong in the library. All of the optimisation flags are in my opinion not helpful for compiling with HighFive as all the possible optimisation should be done in the HDF5 library, and that is precompiled and so settings these flags would not change anything.

So, I would propose that these convenience functions should be collected in targets in a separate library (CMakeBrain? OptimalCMake? ConvenientCMake?  ...) that could then be supported faster as everything is untangled from HighFive/HDF5. And actually, it would be really nice for many users as you could use it also if you do not use HighFive. I for one would be much interested in these targets, whose functionality I now often implement myself. 

At the same time, untangling things would allow an easier maintenance of CMake support here.

**Comment by PhilipDeegan** [comment]
I would say, if you're not building examples or tests, these compiler things might be skipped

**Comment by PhilipDeegan** [comment]
Would it be feasible to generate `H5Version.hpp` on release, that way cmake isn't required anymore for general usage

**Comment by pramodk** [comment]
> I'm trying to use the PGI/openacc compiler suite from nvidia and having difficulties with this line here:

Just want to mention that the original issue about incompatibility with NVHPC/PGI compiler is fixed via  https://github.com/BlueBrain/HighFive/pull/465.
