### ISSUE TITLE
Reading a compound type into memory

### ISSUE THREAD

**Issue by lwpiotr** [BlueBrain/HighFive#452]
Hello,

Is there a possibility to just read a dataset with a compound type as a byte array (for example, `vector<char[]>`) into memory, not knowing what is inside the type? In principle everything is there: `Dataset::getElementCount()` gives the number of elements in the vector, `Dataset::getStorageSize()` gives the size of the whole type, so unless there are some variable-length types inside the compound types, we can calculate the size of `char[]` for each vector element.

Ideally, it would be nice to dynamically create a compound type, perhaps as a `vector<any>`, but I understand that this is much more difficult.

**Comment by maxnoe** [comment]
I think what is meant is that a file contains a dataset of compound type and @lwpiotr wants to read all data of that dataset as bytes, i.e. a `std::vector<std::byte>` or just a `std::string` really.

**Comment by alkino** [comment]
So you can get the size of data and call `read` function with `T*` as parameter.
This object need to be of the right size.

```cpp
std::vector<char> v;
v.resize(p.getElementCount());
d.read(v.data());
```

Should work as expected!

**Comment by ohm314** [comment]
While, I'm not sure the question had been fully answered, I assume there is no specific follow-up and will close. Please feel free to reply here or post on the discussion forum if you have any other questions.
