### ISSUE TITLE
Retrieve offsets of chunks within dataset

### ISSUE THREAD

**Issue by QRabbani** [BlueBrain/HighFive#453]
Referring to [Retrieve offset of dataset](https://github.com/BlueBrain/HighFive/issues/87), how would one retrieve memory addresses of chunks within a (non-contiguous) chunked dataset?

**Comment by ferdonline** [comment]
In HighFive chunks are not exposed to the user. Besides this design, AFAIK there is no support for such operation in hdf5 itself. Therefore it is unlikely that we can ever provide such a functionality. In case this can be achieved with hdf5, you are still free to use it directly on the hid, which can be obtained from HighFive.
