### ISSUE TITLE
Support for CompoundType in Attributes?

### ISSUE THREAD

**Issue by JaWSnl** [BlueBrain/HighFive#454]
(TLDR: See bottom paragraph)

I've been unable to find an example or unit test that puts compound types in attributes. Given the following example code:
```
HighFive::CompoundType create_compound_Size2D() {
    return {{ "width",  HighFive::AtomicType<double>{} },
            { "height", HighFive::AtomicType<double>{} }};
}
HIGHFIVE_REGISTER_TYPE(Size2D, create_compound_Size2D)

void WriteAttribute(HighFive::DataSet& h5DataSet, const Size2D& value)
{
    // What goes here?
}
```
What goes in the `WriteAttribute` function?

I've tried for example:
```
auto size2DType = create_compound_Size2D();
size2DType.commit(h5DataSet, "size2d_type");
h5DataSet.createAttribute(
    "pixelSize",
    HighFive::DataSpace(HighFive::DataSpace::datascape_scalar), size2DType )
            .write(value);
```
Which gives:
> error C2338: supported datatype should be an arithmetic value, a std::string or a container/array
As provided by `H5Converter_misc.hpp`.  

The same compiler error is given when I try:
```
create_compound_Size2D();
h5DataSet.createAttribute("pixelSize", value)
```
Which is how I can successfully use EnumTypes that I've registered in the same way.

So now I'm wondering: does HighFive currently support using CompoundType in an attribute? If not, can you provide me some pointers on how to implement it?

**Comment by ferdonline** [comment]
We can add a test for this, but it was implemented by #450
