### ISSUE TITLE
H5Easy::load_back(...) and H5Easy::load_front(...)?

### ISSUE THREAD

**Issue by tdegeus** [BlueBrain/HighFive#459]
Would it make sense to implement H5Easy::load_back(...) and H5Easy::load_front(...)? This could shorten something like
```cpp
auto stored = H5Easy::load<std::vector<size_t>>(data, "/stored");
size_t inc = stored.back();
```

**Comment by alkino** [comment]
Hum I don't think we should add this kind of feature.

It will make the API more complex for something that does not look really useful.

**Comment by tdegeus** [comment]
Probably I agree ;) Thanks for your feedback @alkino
