### ISSUE TITLE
String attribute read exception 

### ISSUE THREAD

**Issue by wajihullahbaig** [BlueBrain/HighFive#466]
**Describe the bug**
Read a std::string from an attribute

**To Reproduce**
```c++
for (auto &attribute_name : group.listAttributeNames())
    {
        auto attribute = group.getAttribute(attribute_name);
        if (attribute.getDataType().getClass() == HighFive::DataTypeClass::String)
        {
            std::string value ="";
            attribute.read(value); // Here is where the exception is thrown
        }
}
```

**Expected behavior**
value should now contain the string attribute read from HDF file.

**Stacktrace**
```
HDF5-DIAG: Error detected in HDF5 (1.8.20) thread 0:
/hdf5-1.8.20/src/H5A.c line 640 in H5Aread(): unable to read attribute
    major: Attribute
    minor: Read failed
/hdf5-1.8.20/src/H5Aint.c line 644 in H5A_read(): unable to convert between src and dst datatypes
    major: Attribute
    minor: Feature is unsupported
/hdf5-1.8.20/src/H5T.c line 4516 in H5T_path_find(): no appropriate function for conversion path
    major: Datatype
    minor: Unable to initialize object
terminate called after throwing an instance of 'HighFive::AttributeException'
  what():  Error during HDF5 Read:  (Datatype) Unable to initialize object
```

Stepping into the code  further investigation seems the problem pops up from H5Attribute_misc.cpp at the following lines
```c++
if (H5Aread(getId(), mem_datatype.getId(),
                static_cast<void*>(converter.transform_read(array))) < 0) 
{
        HDF5ErrMapper::ToException<AttributeException>(
            "Error during HDF5 Read: ");
 }
```

**Desktop:**
 - OS: Ubuntu 20.04
 - hdf5: 1.8.20 
-  highfive; 2.2 

**Additional context**
The problem only occurs when I try to read string attributes, float/ints are read fine. No problems there.
The string occurs in the system attributes. I am I am using ViTables to view the HDF file.

![user attributes](https://user-images.githubusercontent.com/2294224/119798842-cbb9d180-bedb-11eb-9c16-f69deacd5e46.png)

![system attributes](https://user-images.githubusercontent.com/2294224/119794103-85fb0a00-bed7-11eb-8206-7b3b9d2180e7.png)

**Comment by alkino** [comment]
Is it fixed or variable length string?

`std::string` is for variable-length.

**Comment by wajihullahbaig** [comment]
> Is it fixed or variable length string?
> 
> `std::string` is for variable-length.

It is for variable length strings. The HDF file retain variable length strings so I am using std::string to read them.

**Comment by ferdonline** [comment]
@wajihullahbaig I don't know ViTables but it seems to me these "system attributes" is an extension to hdf5. If you do a plain `h5ls -v` do you see the attributes there? HighFive can only read what's acgtually in the file, probably what ViTables calls "user"

**Comment by wajihullahbaig** [comment]
> @wajihullahbaig I don't know ViTables but it seems to me these "system attributes" is an extension to hdf5. If you do a plain `h5ls -v` do you see the attributes there? HighFive can only read what's acgtually in the file, probably what ViTables calls "user"

I see all the attributes in a list. Just as a side check, I made a string attribute in user-attributes. The code again fails there. Possibly you are right on the extensions thing but I am not sure either.

**Comment by ferdonline** [comment]
Can you show us the result of `h5ls -v` of your file?

**Comment by wajihullahbaig** [comment]
> Can you show us the result of `h5ls -v` of your file?

I am new to HDF and stuff, any quick links I can use for the above command? Sorry for being so naive.

**Comment by wajihullahbaig** [comment]
> Can you show us the result of `h5ls -v` of your file?

Attribute: CLASS scalar
        Type:      5-byte null-terminated UTF-8 string
        Data:  "GROUP"
    Attribute: TITLE null
        Type:      1-byte null-terminated UTF-8 string

.........

    Attribute: time scalar
        Type:      native float
        Data:  0
.........

Entities                 Group
    Attribute: CLASS scalar
        Type:      5-byte null-terminated UTF-8 string
        Data:  "GROUP"
    Attribute: TITLE null
        Type:      1-byte null-terminated UTF-8 string

    Attribute: VERSION scalar
        Type:      3-byte null-terminated UTF-8 string
        Data:  "1.0"
    Location:  1:7345508
    Links:     1


I have truncated the output

**Comment by tdegeus** [comment]
A naive question: we do you initialise the string. Shouldn't you do
```cpp
std::string value;
attribute.read(value);
```
See e.g. https://github.com/BlueBrain/HighFive/blob/5e5673d9146e55e64b07954b4aa0177a250a2ca4/include/highfive/h5easy_bits/H5Easy_scalar.hpp#L62-65

**Comment by wajihullahbaig** [comment]
> A naive question: we do you initialise the string. Shouldn't you do
> 
> ```c++
> std::string value;
> attribute.read(value);
> ```
> 
> See e.g.
> 
> https://github.com/BlueBrain/HighFive/blob/5e5673d9146e55e64b07954b4aa0177a250a2ca4/include/highfive/h5easy_bits/H5Easy_scalar.hpp#L62-L65

I should not need to initialize it. But I tried that as well. Same error I get.

**Comment by wajihullahbaig** [comment]
> > A naive question: we do you initialise the string. Shouldn't you do
> > ```c++
> > std::string value;
> > attribute.read(value);
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > See e.g.
> > https://github.com/BlueBrain/HighFive/blob/5e5673d9146e55e64b07954b4aa0177a250a2ca4/include/highfive/h5easy_bits/H5Easy_scalar.hpp#L62-L65
> 
> I should not need to initialize it. But I tried that as well. Same error I get.

I even tried the templated version, same error.

**Comment by alkino** [comment]
As we don't reproduce and there is no news, let's close. If the problem still occur on your side. Feel free to open it again.
