### ISSUE TITLE
std::array is not a container

### ISSUE THREAD

**Issue by ivan-tkatchev** [BlueBrain/HighFive#470]
```c++
// check if the type is a container ( only vector supported for now )
template <typename>
struct is_container {
    static const bool value = false;
};

template <typename T>
struct is_container<std::vector<T> > {
    static const bool value = true;
};
```
This means that writing e.g., `std::vector<std::array<double, 10>>` currently doesn't work.

What are the downsides of supporting `std::array` in `is_container`?

Thanks.

**Comment by alkino** [comment]
It's not so easy today, putting `std::array` inside `is_container` won't make it works, we should develop the classes for `std::vector<std::array>`.

There is currently (too much) long term refactoring to handle those kind of feature automatically.

Look at: https://github.com/BlueBrain/HighFive/issues/307

**Comment by alkino** [comment]
Support added by #586
