### ISSUE TITLE
Patch release

### ISSUE THREAD

**Issue by tdegeus** [BlueBrain/HighFive#473]
Since the release frequency on this repo is quite low (i.e. the code is quite stable!) : 
I would like to use https://github.com/BlueBrain/HighFive/pull/471 on conda-forge. For that the nicest is to have a patch release. Could you set a reasonable milestone for such a release?

**Comment by ferdonline** [comment]
You can go ahead @tdegeus having a patch release every time important patches are available.

**Comment by tdegeus** [comment]
Thanks @ferdonline . I'll give it another week to give a chance to:
* https://github.com/BlueBrain/HighFive/pull/469
* https://github.com/BlueBrain/HighFive/pull/465
to be included. If not I'll prepare the release without them

**Comment by alkino** [comment]
I was in holidays add 3 days and I fix the #465
