### ISSUE TITLE
Using compound type in a static library and the main program

### ISSUE THREAD

**Issue by pquan** [BlueBrain/HighFive#478]
This is probably not a bug, but my ignorance, yet I'm struggling to understand how to use a compound type between a static library and the main program.

I'm following the example in the source by declaring a function that returns the compound type as HighFive::CompoundType and associate it to the c++ class via `HIGHFIVE_REGISTER_TYPE(cpp_class, compount_type_function)

If I do this in the static library, I can read/write the compound type in the static library, but read/write from "main" gives me "unsupported atomic type" compile error.

If I do this in the "main" function, I can read/write the compound type from the main program but not from a library.

And If I "register" the types in both places, I get an "Already defined in library.lib" error at link time.

What is the proper way to read/write the same compound types from different libraries and avoid the linking errors?

I'm sure I'm missing something obvious here.

Thanks.

**Comment by alkino** [comment]
Can you give some basics code you use?

**Comment by pquan** [comment]
@alkino yes, I created a proxy solution in VS2019, Windows with just 1 library as a static library project and a single main.cpp in another project and starting point.

The library is reader.h + reader.cpp

**reader.h**
``` 
#pragma once
#define WIN32_LEAN_AND_MEAN             // Exclude rarely-used stuff from Windows headers

#include <highfive/H5DataSet.hpp>
#include <highfive/H5DataSpace.hpp>
#include <highfive/H5File.hpp>

class my_class_t{
public:
	long long u1;
	float u2;
	int32_t size;
	int16_t u4;
        // ... methods follow here...
};

size_t fnreader(void);
HighFive::CompoundType make_my_class_t();
```

**reader.cpp:**
```
#include <stdio.h>
#include "reader.h"

HighFive::CompoundType make_my_class_t() {
	return {
		{"u1", HighFive::AtomicType<long long>{}},		// long long
		{"u2", HighFive::AtomicType<float>{}},			// float 
		{"size", HighFive::AtomicType<int32_t>{}},			// size
		{"u4", HighFive::AtomicType<int16_t>{}},			// an int 16
	};
}
HIGHFIVE_REGISTER_TYPE(my_class_t, make_my_class_t);

// This is the library reader function
size_t fnreader(void)
{
	HighFive::File f("test.h5", HighFive::File::ReadOnly);
	HighFive::DataSet ds = f.getDataSet("mydataset");

	std::vector<my_class_t> data;
	ds.read(data);
	std::cout << " [ Framework Read " << data.size() << " rows ] ";

	return data.size();
}
```

**main.cpp** contains the program code in a separate project. Also main.cpp would like to read the compound type :)

```
#include <vector>

#include <highfive/H5DataSet.hpp>
#include <highfive/H5DataSpace.hpp>
#include <highfive/H5File.hpp>

#include "reader.h"

#if 1 // THIS WORKS, new class for compound type

class main_my_class_t {
public:
	long long u1;
	float u2;
	int32_t size;
	int16_t u4;
};
HIGHFIVE_REGISTER_TYPE(main_my_class_t, make_my_class_t);

#elif 0 // THIS DOES NOT (my_class_t taken from reader.h)

HIGHFIVE_REGISTER_TYPE(my_class_t, make_my_class_t);

#elif 0 // Also this does not work (atomic type unknown error)

// We avoid registering the compound type 

#endif 


using namespace HighFive;

int main()
{
	HighFive::File f("test.h5", HighFive::File::ReadOnly);
	HighFive::DataSet ds = f.getDataSet("mydataset");
	
	std::vector<main_my_class_t> data;
	ds.read(data);
	std::cout << "MAIN Read " << data.size() << " rows\n";

	std::cout << "FN Reader returns " << fnreader() << "\n";

	return 0;
}
```

So, main.cpp is using the type from "reader.h" and want to read it by itself. To do so, it needs to register the type or highfive will complain about unknown atomic type at compile time. However, when registering it, it cannot be linked with the library because the compound type is declared in both the library and main (perhaps the library can/could define it as static?).

If, however, I register the compound type using an "alias" for the C++ type in reader.h (**my_class_t**) and call it **main_my_class_t** then the link succeeds and the program works.

The problem with this is that those classes in the library do a little more than just hold data (they have methods) so it's not as simple as redeclaring the type in the main program. 

I hope the problem is clear. 

I'm not sure how to fix it.

**Comment by pquan** [comment]
A problem with deriving from a base class however turned out to be that more data is inserted by the compiler in the derived class. I understand why, but the alignment of the derived class is then broken and no good data can be read from the file.

As a workaround, I had to create a single "hdf access" module in my library for doing all read/write access to the HDF files. All hdf access needs in other parts of the program go trough this reader. 

For testing and custom, I am required to re-declare the classes from scratch and not reuse the library header files. This way "it works".

But let me know if there's better way.
