### ISSUE TITLE
Add support for std::byte as Dataset type

### ISSUE THREAD

**Issue by ghost** [BlueBrain/HighFive#480]
Creating a dataset with underlying type of `std::byte` currently triggers a static assertion ("Type not supported"). This makes sense as `std::byte` is implemented as an enum rather than a scalar/numeric type. However, CPP Core Guidelines encourages the use of `std::byte` as the preferred way to refer to generic, non-character data. Does it make sense for `HighFive` to support this?

Minimal example of the issue:
```c++
#include <highfive/H5File.hpp>
#include <cstddef>
#include <vector>

using namespace HighFive;

int main()
{
    std::vector<std::byte> buffer(1024, std::byte(0xCD));
    File file("database.h5", File::ReadWrite | File::Create | File::Truncate);
    file.createDataSet<std::byte>("frame", DataSpace::From(buffer)).write(buffer);
}
```

**Comment by alkino** [comment]
Of course, it makes sense. Do you want to try?

**Comment by bitset32** [comment]
I am willing to have a go, let's see how much damage I can do :wink:
