### ISSUE TITLE
Example of reading a compound datset

### ISSUE THREAD

**Issue by mfouesneau** [BlueBrain/HighFive#487]
I cannot find a simple example to read into memory a multidimensional dataset. I probably missed it.

I was expecting something like 

```cpp
typedef struct{
...
} record;

std::vector<record> data;
HighFive::DataSet hf_ds = file.getDataSet(path);
ds.read(data);
```

This does not work. It seems "type not supported"

I'm a bit lost. I find a lot on writing/reading single-dimensional data but not multi-dimensional.

I found this example, but the CompoundType usage is obscure
https://github.com/BlueBrain/HighFive/blob/master/src/examples/compound_types.cpp

**Comment by tdegeus** [comment]
Your question is a bit vague to me. If your question is: can I read a multidimensional array, the answer is yes: you can read `vector` of `vector` etc., or use a continuous container like Eigen (2d) or xtensor (nd) using `H5Easy`. You could then map your datatype to it, or simply copy relevant data. 

"compound" data to me refers more to a multitude of datatypes, which is I'm afraid not something that I know the answer to.

Then, why your example does not work: that is completely logical, how would HighFive know how to interpret data and write it to your class?

**Comment by mfouesneau** [comment]
"compound" data is the compound type from the HighFive library, which is supposed to read mixtures of datatypes.

**Comment by tdegeus** [comment]
Alright, I was simply not sure as you were mentioning multi-dimensional. 

The example is a bit more extended than you present here. In particular it provides a method to HighFive how to interpret. I think that your question should include a try for it, then one can build/debug from there

**Comment by mfouesneau** [comment]
I solved my issue. What was very unclear was all the steps and individual definitions

It requires a structure with all row elements and the data table structure function.

```c++
    typedef struct {
        double wavelength;
        double transmission;
    } filter_t;

    HighFive::CompoundType create_compound_filter_t(){
        return {{"WAVELENGTH", HighFive::AtomicType<double>{} },
                     {"THROUGHPUT", HighFive::AtomicType<double>{}} };
    }

    Filter get_filter_from_hdf5_library(const std::string& library_filename,
                                        const std::string& filter_name){

        // read string attributes that HIGHFIVE cannot
        std::string dataset_path ("/filters/" + filter_name);
        H5::H5File file(library_filename, H5F_ACC_RDONLY);
        H5::DataSet ds = file.openDataSet(dataset_path);
        std::string name = get_str_attribute(ds, "NAME");
        std::string detector_type = get_str_attribute(ds, "DETECTOR");
        std::string wavelength_unit = get_str_attribute(ds, "WAVELENGTH_UNIT");
        file.close();

        H5Easy::File hf_file(library_filename, H5Easy::File::ReadOnly);
        HighFive::DataSet hf_ds = hf_file.getDataSet(dataset_path);
        std::vector<filter_t> data;
        hf_ds.read(data);
        //....
}
```

However I do use the `HIGHFIVE_REGISTER_TYPE(filter_t, create_compound_filter_t)`. Initially, a piece I forgot, I could not understand what additional information this generates.

**Comment by 1uc** [comment]
The linked example seems to contain all the steps in the final solution. Including the use of the macro. It may have changed in the meantime. As is, I feel this is sufficiently well documented by the example.
