### ISSUE TITLE
Cast fixed-length string -> `std::string` missing

### ISSUE THREAD

**Issue by JATC1024** [BlueBrain/HighFive#505]
**Is your feature request related to a problem? Please describe.**
H5Easy.load cannot load fixed length strings. I always get the error `Can't output std::string as fixed-length. Use raw arrays or FixedLenStringArray`. I tried to use `HighFive::FixedLenStringArray<N>` and it worked. However, I had to know the length of the strings beforehand since N must be a constant. This does not seem viable to me.

**Describe the solution you'd like**
Something like
```
int size = dataset.getStringSize();
HighFive::FixedLenStringArray strs(size);
```
would be nice. Or even better if `H5Easy` will handle everything so that I don't have to care if the dataset is fixed length or not.

**Comment by ferdonline** [comment]
Hey.
Your request is understandable but I believe HighFive already implements the required API.
Have you tried along the lines? (not tested):
```
int size = dataset.getDataType().getSize();
HighFive::FixedLenStringArray strs(size);
```

**Comment by JATC1024** [comment]
Thanks for replying. I think my comment here best describes my problem: https://github.com/BlueBrain/HighFive/issues/94#issuecomment-1048514871.

Looking through the [document](https://bluebrain.github.io/HighFive/class_high_five_1_1_fixed_len_string_array.html#a93e3229e9a807bf171cbbaa8064cceb6), I cannot find a way to construct `FixedLenStringArray` without knowing `N` beforehand. Did I miss something?

**Comment by JATC1024** [comment]
I think the problem here is that `FixedLenStringArray<N>` is a `std::vector<std::array<T, N>>` in disguise, which requires knowing `N` in compile time.

Therefore,
```
const int len = 10;
FixedLenStringArray<len> strs;
```
works but 
```
const int len = dataset.getDataType().getSize();
HighFive::FixedLenStringArray<len> strs;
```
doesn't.

**Comment by ferdonline** [comment]
Oh, I'm sorry I overlooked the fact that the signature of FixedLenStringArray is `FixedLenStringArray<N>`, then N must be known at compile time.
I find your use case valid. There are plans to create a replacement of `FixedLenStringArray` but unfortunately our bandwidth is limited. If you feel comfortable to draft a solution, along the lines of using regular std::vector with `std::string_view` but keep compat with c++11 (like https://github.com/bitwizeshift/string_view-standalone) I would be happy to review.

**Comment by JATC1024** [comment]
I'll try to look into this in my free time. For now, I will simply set `N` as a big enough integer.

**Comment by tdegeus** [comment]
@JATC1024 You probably have a good reason to do what you do. Still, `std::string` may not be fixed-size, but is still pretty 'easy':
```cpp
auto mystring = H5Easy::load<std::string>(file, "/path/to/my/string");
```

Also, unlike @ferdonline I'm not super sure that a 'fixed-size' string object that is dynamically allocated is relevant. Wouldn't that we `std::string` that you `reserve` to a certain size? Also this you can do currently (though not in `H5Easy` but in `HighFive`).
The current compile-time allocated truly fixed-size string is different. It presumably lives on the stack on might gain you some speed (though I doubt a lot, because I think that disk-IO will always be limiting).

**Comment by JATC1024** [comment]
@tdegeus 
Oh I think I didn't describe the problem properly. I want to load an array of strings, not just a single string. What I'm trying to do is:
```
std::vector<std::string> strs;
strs = H5Easy::load<std::vector<std::string>>(file, "/path/to/strings")`
```
For variable-length strings, this works. For fixed-length strings, it shows the error `Can't output std::string as fixed-length. Use raw arrays or FixedLenStringArray`.

Or are you suggesting that I cant load each string in the array individually? Something like
```
auto mystring = H5Easy::load<std::string>(file, "/path/to/strings", index);
```

I see you do have a [function](https://github.com/BlueBrain/HighFive/blob/c9739ef1ac6b91e74d85643f2186abbb6861a634/include/highfive/H5Easy.hpp#L340) like that. I will try it tomorrow, though I think I will get the same error.

**Comment by tdegeus** [comment]
Thanks for the clarification @JATC1024 . This makes a lot of sense. I should say that I'm not at all an expert on HDF5 fixed-length strings. That being said, I see no reason why `HighFive` should not provide a method to load strings that are stored as fixed-length to `std::string`. I think that this should be implemented in the 'core' for `std::string` types. In that case it should be automatically available in `H5Easy` as well.

**Comment by JATC1024** [comment]
@tdegeus sure, whatever way you see fit. If you create a new one then I think we can close this one.

**Comment by 1uc** [comment]
With https://github.com/BlueBrain/HighFive/pull/744 merged std::strings and containers thereof, e.g. std::vector<std::string> can be read and written to fixed or variable length HDF5 strings. There's an example here:
https://github.com/BlueBrain/HighFive/blob/master/src/examples/read_write_std_strings.cpp
