### ISSUE TITLE
Remove cyclic dependencies of includes.

### ISSUE THREAD

**Issue by 1uc** [BlueBrain/HighFive#508]
When looking at the dependency graph of the `H5Easy.hpp` one sees several cyclic dependencies and it's not very obvious what needs what. By lifting the declaration in the namespace `H5Easy` into a separate file, the dependencies can be simplified and made acyclic.

This change might affect how template specializations are imported. Therefore, I like to ask if such a change would be welcome and worthwhile. Sketch of a solution to follow.

**Comment by 1uc** [comment]
The change leads to a situation where if one looks at the new dependency graph of the files, which is displayed in the Doxygen documentation, e.g. [1], to me it is more clear how the code is organized, i.e. what to expect in which file.

[1]: https://bluebrain.github.io/HighFive/_h5_easy_8hpp.html

The top-level file `H5Easy.hpp` now clearly includes numerous files that are suffixed by external dependency, suggesting that the dependency specific code can be found there. Which to me implies, that `H5Easy.hpp` is indeed the file to include if I want to use (all of) `H5Easy`. In the current state, `H5Easy.hpp` has a sensible name, which suggests the same thing. When looking at the dependency graph, to me, that becomes less obvious.

When adding another array library, it seems more which files the other implementations require and therefore which files must be included by the new implementation, and also where the implementation needs to be 'registered', i.e. in `H5Easy.hpp`.

I'd need to test carefully, but this should provide a path to enable including only the subset of `H5Easy` which works with one specific external dependency, say `xtensor`, maybe because those are the only type of arrays used in a specific compilation unit. Thereby reducing a) the reasons why that compilation unit needs to rebuild in an incremental build, and b) the number of files the preprocessor needs to consider.

On the other hand as you say the preprocessor can figure it out and the remaining benefits are quite possibly not that relevant either.

The promised sketch can be found here: #509.

**Comment by tdegeus** [comment]
Thanks. I see now at which problem this addresses, and how making changes can invite additions. A couple of discussion points:

My idea behind the `H5Easy.hpp` as it is, is that at least there is at least one clear point where all the definitions are. So if one looks at the the source one would find everything relevant to the public API in one place. Instead, https://github.com/BlueBrain/HighFive/pull/509 moves almost the entire public API to `H5Easy_bits` where one might expect only implementation details. 

The current implementation of `H5Easy` respects the style of the rest of `HighFive`. I think that any changes should keep respecting this style.

If I read the rest of your ideas I would say that you are arguing that in stead of
```cpp
#include <xtensor/xtensor.hpp>
#include <Eigen/Eigen>
#include <highfive/H5Easy.hpp>
```
or 
```cpp
#define H5_USE_XTENSOR
#define H5_USE_Eigen
#include <highfive/H5Easy.hpp>
```
it could also be nice to have
```cpp
#define <highfive/H5Easy_xtensor.hpp>
#define <highfive/H5Easy_Eigen.hpp>
```
i.e. to split the public API of `H5Easy`.
The benefit being:
* There would be 'new' API that avoids any form of auto-including in the case that there might be name-clash with for example `EIGEN_WORLD_VERSION`. A side note: ignoring that such a name-clash may occur, currently `H5Easy` only enables either what you tell it to, or what is included already anyway. I don't think the latter comes at any cost, but I could be overlooking something?
* It might guide someone adding let's say `Armadillo`. At this point I don't think the advantage is huge: registering the extension should still be done in `highfive/H5Easy_Armadillo.hpp` and `highfive/H5Easy.hpp` for 'backward' compatibility.

**Comment by 1uc** [comment]
> The current implementation of H5Easy respects the style of the rest of HighFive. I think that any changes should keep respecting this style.

That's indeed a draw back. I don't know how two achieve both. Therefore, if consistency with the rest of `HighFive` is more valuable, we can close both #508 and #509. Please feel free to do so, since you're more familiar with `H5Easy` than me.


> i.e. to split the public API of H5Easy.

Exactly, either as nicely as you suggest or unofficially by putting the user in a position where including the bits files is possible, but (presumably) at their own risk. If the declarations are to remain in `highfive/H5Easy.hpp`, any subset of the API, e.g. `highfive/H5Easy_xtensor.hpp` must include `highfive/H5Easy.hpp` to obtain the declarations. Therefore, pulling the other specializations (as a side effect).

**Comment by tdegeus** [comment]
I would then be an even more flexible public API!

**Comment by 1uc** [comment]
Sorry for the delay. Personally, my productivity drops when compile times are too high. I've had this problem in my own codes and since try to enable, optionally, including less.

The structure of the includes you propose feels natural. I'll try if there are any nasty issues, e.g. one compilation unit only includes the specializations for `xtensor` and the other only for `eigen`.

**Comment by 1uc** [comment]
I'm unable to improve the code organization in such a way that the declarations of the API remain in the `H5Easy.h` while supporting the desired functionality. Since this issue suggests a particular reorganization of files, I propose to close this issue.
