### ISSUE TITLE
Use Catch2 for unit testing

### ISSUE THREAD

**Issue by matz-e** [BlueBrain/HighFive#510]
I think it may be worthwhile switching to Catch2 for unit testing, as many of our newer projects have done. In the past, I've experienced bad linking issues with Boost's unit tests with the same code paths but different operating systems.

This would also allow us to make Boost fully optional and maybe even disable it by default.

**Comment by tdegeus** [comment]
Sounds great. I would be in strong favour for making boost by default optional! It is really not something the project depends on, and might discourage use.

**Comment by tdegeus** [comment]
I wonder if the Boost default in the CMake target should in term not change

**Comment by matz-e** [comment]
> I wonder if the Boost default in the CMake target should in term not change

Yes. That seems a bit more invasive, so I did not want to put that in here yet.

**Comment by tdegeus** [comment]
I can imagine. But I think this should at some point be done, I really dislike this enforced default with a bit clumsy way to turn it off. At some point I proposed to have modular targets in parallel.
