### ISSUE TITLE
Unable to read hdf5 files 

### ISSUE THREAD

**Issue by alamj** [BlueBrain/HighFive#560]
I get the following error while attempting to read a file, which was written in parallel (n x m matrix, m is large). Inside the writing loop, I can read the written file. I can read the file from python h5py.

I need to read file from a separate (user) code (sequential for now). To reproduce the error, I used the following code:
Here, example.h5 was created by a HighFive example code. I got a very similar or same error using H5Easy and HighFive::File, but the example with xtensor is easy to reproduce the error. (Running on CentOS 7)

```c++
#include <xtensor/xio.hpp>
#include <xtensor-io/xhighfive.hpp>

int main()
{
    xt::xtensor<double,2> A = xt::ones<double>({10,5});

    A = xt::load_hdf5<xt::xtensor<double,2>>("example.h5", "/home/alamj/TestCases/tests/hdf5of/");

    std::cout << A << std::endl;

    return 0;
}
```

Part of the error is pasted below:
```
HDF5-DIAG: Error detected in HDF5 (1.12.1) thread 0:
  #000: H5D.c line 141 in H5Dcreate2(): unable to create dataset
    major: Dataset
    minor: Unable to create file
  #001: H5VLcallback.c line 1806 in H5VL_dataset_create(): dataset create failed
    major: Virtual Object Layer
    minor: Unable to create file

#008: H5Gtraverse.c line 692 in H5G__traverse_real(): unable to create group entry
    major: Symbol table
    minor: Unable to initialize object
  #009: H5Gobj.c line 185 in H5G__obj_create_real(): no write intent on file
    major: Object cache
    minor: Bad value
terminate called after throwing an instance of 'HighFive::DataSetException'
  what():  Unable to create the dataset "/home/alamj/TestCases/tests/hdf5of/": (Object cache) Bad value
Aborted
```

**Comment by tdegeus** [comment]
Just from the look of it your path is not pointing to a dataset, but rather to a group (at best). Note that is in the path *inside* the HDF5 file, not that *of* the HDF5 file

**Comment by alkino** [comment]
I wonder if those kind of issues should go on xtensor-io github

**Comment by tdegeus** [comment]
They should ;)
But I'd rather that @alamj simply switches to H5Easy which started as an upstream port of xtensor-io. 
Please checkout https://github.com/BlueBrain/HighFive/blob/2cb795962a5c00021f28d4d2cb9b05bdbbd147d8/src/examples/easy_load_dump.cpp#L94

**Comment by alamj** [comment]
The same error thrown by (using easy_load_dump.cpp)

E = H5Easy::load<xt::xtensor<size_t, 1>>(file, "/home/alamj/TestCases/tests/hdf5of");   

Am I missing something?

**Comment by tdegeus** [comment]
I have the impression that the underlying problem is still the same. I feel that you are misinterpreting file paths and paths inside the HDF5 file. Note that an HDF5 file is like a file system inside a file system. 

In order to help you you should also post the code where you write the `file` (and the code on how you open it)

**Comment by alkino** [comment]
I think we can close it because the user seems gone
