### ISSUE TITLE
Writing pre-compressed data to chunks with H5Dwrite_chunk

### ISSUE THREAD

**Issue by antonysigma** [BlueBrain/HighFive#590]
https://github.com/ess-dmsc/h5cpp/pull/424/files#diff-4bef1fa82b9bea1e0737f93a6bf87fd664c77ccc04a46d4d1a72f3cc27e4afa0R700

**Is your feature request related to a problem? Please describe.**
I wish to write a pre-compressed chunk of data to the corresponding chunk location of a HDF5 dataset. The corresponding low-level API is `H5Dwrite_chunk` for `libhdf5 >= 1.10.3`, or `H5DOWrite_chunk` for `libhdf5 < 1.10.3`. 

In my application, the data is pre-compressed by the camera ahead of time, so I can utilize `H5Dwrite_chunk` to bypass the slow path in the HDF5 write mechanism. For example, the 16-bit images (W x H), compressed by `zlib`/`deflate` ahead of time, matches completely the user-provided HDF5 datatype setting (16-bit unsigned, little-endian), chunk shape (W x H), as well as the filter setting (`gzip` filter, byte-shuffle off). So, technically I can create a dataset with `HighFive` having the above configs, and then directly the precompressed data directly to the corresponding chunk.

**Describe the solution you'd like**

A function:
```c++
template<class A, typename T>
HighFive::SliceTraits<A>::write_chunk(const T* encoded_data);
```
similar to another HighFive API: `HighFive::SliceTraits<>::write_raw(const T* data);`.

**Describe alternatives you've considered**

- Moving from `HighFive` library to the `H5CPP` library; but that involves the complete refactoring of my existing application.
https://github.com/ess-dmsc/h5cpp/pull/424/files#diff-4bef1fa82b9bea1e0737f93a6bf87fd664c77ccc04a46d4d1a72f3cc27e4afa0R700

- Create a `HighFive::DataSet` object, and then try to cast the object to `hid_t dset_id` in order to call the low-level API `H5Dwrite_chunk` directly. I am unable to do that because `HighFive::Object<>::_hid` variable is `protected`.

**Additional context**

- A similar request on the `H5CPP` library: https://github.com/ess-dmsc/h5cpp/issues/286
- HDF5Group's white paper on the direct chunk write design intent: https://docs.hdfgroup.org/archive/support/HDF5/doc/Advanced/DirectChunkWrite/DECTRISIntegrationRFC2013-1-25.pdf
- HDF5Group's API documentation: https://confluence.hdfgroup.org/display/HDF5/H5D_WRITE_CHUNK

**Comment by alkino** [comment]
> Create a HighFive::DataSet object, and then try to cast the object to hid_t dset_id in order to call the low-level API H5Dwrite_chunk directly. I am unable to do that because HighFive::Object<>::_hid variable is protected.

You can get `hid_t` from any object by calling `.getId()` on it: https://bluebrain.github.io/HighFive/class_high_five_1_1_object.html#a0efb623a7ceb36777ce81e215995a3bc

I will consider your request.

**Comment by antonysigma** [comment]
Thanks @alkino for the tips. Here's the minimal working example, for record keeping purpose:

```c++
#include <cstdint>
#include <iostream>
#include <vector>

#include <hdf5_hl.h>
#include <highfive/H5File.hpp>
#include <highfive/H5PropertyList.hpp>

using HighFive::File;
using HighFive::DataSpace;
using HighFive::DataSetCreateProps;
using HighFive::Chunking;

namespace {

template<class Dataset, typename T>
herr_t
writeChunk(Dataset& dset, const std::vector<T>& src_buffer) {
    const auto dset_id = dset.getId();
    constexpr auto filter_mask = 0;
    constexpr hsize_t offset[] = {0, 0};

    return H5DOwrite_chunk(dset_id, H5P_DEFAULT, filter_mask, offset, src_buffer.size() * sizeof(T),
                          src_buffer.data());
}

}

int main() {
    // Open a file
    File file("/tmp/testing.h5", File::ReadWrite | File::Truncate);

    // Create DataSet
    constexpr int height = 5;
    constexpr int width = 7;

    auto props = DataSetCreateProps::Default();
    props.add(Chunking{height, 1});

    auto dset = file.createDataSet<uint16_t>("/dset1", DataSpace{height, width}, props);

    const std::vector<uint16_t> ones(height * width, 1);

    // Write ones
    dset.write_raw(ones.data());

    // Write twos to the left most chunk. I haven't figured out
    // how to pass the chunk location / offset values yet, in order to
    // write to the N-th chunk.
    const std::vector<uint16_t> twos(height, 2);
    const auto status = writeChunk(dset, twos);

    if (status < 0) {
        std::cerr << "Error: " << status << '\n';
        return 1;
    }

    return 0;
}
```

**Comment by 1uc** [comment]
Thanks for posting the solution; and I think this is the correct approach to this problem.

The desired solution is to do something very specific which requires precise knowledge about the HDF5 library. Therefore using one native HDF5 function seems appropriate; and the overall amount of code required doesn't seem excessive.
