### ISSUE TITLE
Writing empty xtensor array results in filled h5 dataset

### ISSUE THREAD

**Issue by james-mxr** [BlueBrain/HighFive#599]
In numpy I can write a shape to an h5 dataset, and it will not actually populate it with information;
```py
  h5 = h5py.File('mytestfile.hdf5', 'w')
  h5.create_dataset("/empty", {100, 50, 50, 3}, h5py.h5t.IEEE_F32LE)
```
![image](https://user-images.githubusercontent.com/109164466/181216264-07a2f0bd-3c3a-4ad8-9db6-f6791902cdb6.png)

However with xtensor or highfive it seems to always populate it with data.
xtensor-io code:
```cpp
xt::xtensor<float, 4> empty = xt::empty<float>({100, 50, 50, 3});
xt::dump_hdf5("xio_test_empty.h5", "/empty", empty);
```
or 
```cpp
xt::xtensor<float, 4> empty ({100, 50, 50, 3});//= xt::empty<float>({100, 50, 50, 3});
xt::dump_hdf5("xio_test_empty.h5", "/empty", empty);
```

I believe xtensor-io wraps Highfive Easy? Which makes sense why this also doesn't work
```cpp
auto file = H5Easy::File("h5easy_test_empty.h5", HighFive::File::Create);
H5Easy::dump(file, "/empty", empty);
```
Both yield the following hdf5 file,
![image](https://user-images.githubusercontent.com/109164466/181216713-3e950d83-e9a5-4712-a6f2-6031eb450e09.png)

**Comment by tdegeus** [comment]
H5Easy does not support allocating an empty array. That *is* a thing that you can do with the basic API of HighFive, see e.g. https://github.com/BlueBrain/HighFive/blob/master/src/examples/create_dataset_double.cpp . In fact, H5Easy was specifically created to wrap around several functions including this one to provide the user with one-liners. 

Then just a comment. `xt::empty` means allocate some memory for me, but do not do anything to it (yet, of course later operations will/should modify it). So it gives you a matrix with whatever happened to be on that memory. So indeed, it is fully populated to arbitrary values. H5Easy then simply writes that populated matrix (btw, it would have no way of knowing what you would have liked it to do).

**Comment by tdegeus** [comment]
Closing as resolved for now, but please come back to us when that is not the case
