### ISSUE TITLE
same issue,Reading fixed length string from attribute #322

### ISSUE THREAD

**Issue by wadv1232** [BlueBrain/HighFive#613]
version:2.4.1
code：
```c++
HighFive::FixedLenStringArray<8> v;
file.getGroup("/what").getAttribute("date").read(v);
```
error:
```c++
inline bool checkDimensions(const DataSpace& mem_space, size_t input_dims) {

for (auto i = dims.crbegin(); i != --dims.crend() && *i == 1; ++i)
```
same issue ：Reading fixed length string from attribute #322

**Comment by N-damo** [comment]
same issue

**Comment by N-damo** [comment]
dimension of the attribute is 0,so "Impossible to read DataSet of dimensions 0 into arrays of dimensions 1"?

**Comment by 1uc** [comment]
It sounds like you want to read a single fixed length string, not an array of fixed length strings. The class `HighFive::FixedLenStringArray<8>` models an array of strings, each of which has length 8.

In order to read a fixed length string you do something along the lines of:
```
    using fixed_len_str_t = std::array<char, 6>;
    // Create a new file using the default property lists.
    {
        File file(FILE_NAME, File::ReadWrite | File::Create | File::Truncate);
        auto attr = fixed_len_str_t{"Hello"};
        file.createAttribute("str", attr);
    }
    // Re-read it
    {
        File file(FILE_NAME);

        // without pre-allocation
        {
            auto attr = file.getAttribute("str").read<fixed_len_str_t>();
            CHECK(attr.data() == std::string("Hello"));
        }

        // with pre-allocation
        {
            auto attr = fixed_len_str_t{};
            file.getAttribute("str").read(attr);
            CHECK(attr.data() == std::string("Hello"));
        }
    }
```
Probably a `char [6]` would work too. Naturally, you could also read the string as a `std::string`.

**Comment by N-damo** [comment]
not work.
error:
Can't output std::string as fixed-length. Use raw arrays or FixedLenStringArray  


![image](https://user-images.githubusercontent.com/43883112/203674221-334d5e2c-369f-4d11-8c4f-7beb7230ab53.png)
![image](https://user-images.githubusercontent.com/43883112/203674551-83730749-869b-4d45-8a72-f318db758ae7.png)

**Comment by kailvn** [comment]
same issue, but the test case "HighFiveFixedLenStringArrayAttribute" work.

**Comment by andrewliuhui** [comment]
@kailvn testcase has dimensions 1, so it can work.
If fixed-len-string  attribute with  dimension 0 , highfive cannot read that attribute.

**Comment by 1uc** [comment]
Thank you for this subtle difference. 

We've been working towards improving `std::string` support. In particular, making it possible to read/write `std::string`s and containers (`std::vector`, `std::array`, etc) of `std::string` to/from any HDF5 string datatype.

This would hopefully eliminate the need for `FixedLenStringArray` entirely. The PR is #744.

**Comment by 1uc** [comment]
With https://github.com/BlueBrain/HighFive/pull/744 merged std::strings and containers thereof, e.g. std::vector<std::string> can be read and written to fixed or variable length HDF5 strings. There's an example here:
https://github.com/BlueBrain/HighFive/blob/master/src/examples/read_write_std_strings.cpp
