### ISSUE TITLE
Build coverage for pHDF5

### ISSUE THREAD

**Issue by 1uc** [BlueBrain/HighFive#638]
For sequential HDF5 we check that HDF5 can be build and linked properly. One of the important errors this find are missing `inline`. However, in #637 these checks failed to uncover such a case. It would be pleasant to close this gap, since the issues is likely to reoccur.

**Comment by alkino** [comment]
Today in https://github.com/BlueBrain/HighFive-testing only serial tests are run.
We could duplicate compilation to add parallel tests.
