### ISSUE TITLE
Implement better error / warning logging

### ISSUE THREAD

**Issue by ohm314** [BlueBrain/HighFive#640]
Currently we mostly use `std::cerr` and Exceptions for reporting warnings and errors. This is not very flexible and can sometimes be quite inefficient (e.g. log one message per dataset might create an avalanche of messages for large HDF5 files).

It would be nice to replace this ad-hoc way of reporting things with a proper system. We could use a third-party logger library, or write a simple logging facility / manager into HighFive.

Just quickly considering this I think we need from the logger different log levels, follow-up action (e.g. automatically fail on some log levels), integration with exception handling and singleton logs (or suppression of log messages beyond a given count.

**Comment by 1uc** [comment]
Closed via #690
