### ISSUE TITLE
External Catch2 setup seems to be wrong. 

### ISSUE THREAD

**Issue by Neumann-A** [BlueBrain/HighFive#668]
Please be aware of https://github.com/microsoft/vcpkg/blob/c2997692821e6cbc146e8adc5820ddc83830147c/ports/highfive/fix_catch2.patch

I basically had to change all `target_link_libraries(${test_name} HighFive Catch2::Catch2)` to `target_link_libraries(${test_name} HighFive Catch2::Catch2WithMain)` and `#include <catch2/catch.hpp>` to `#include <catch.hpp>`

**Comment by alkino** [comment]
You use a catch2 version 3 where we use a catch2 version 2, I guess
