### ISSUE TITLE
Track creation order for the root group

### ISSUE THREAD

**Issue by jjcasmar** [BlueBrain/HighFive#670]
I am having HighFive to write the results of an animation I am simulating. In my hierarchy, each frame is a direct children of the root group, so I have something like this

```
/0/
/1/
/2/
...
/10/
...
```

If I just let the default ordering, I would get the group `/10` before the group `/2`. Therefore, I want to track the insertion order. 

I am using this simple example to do some testing (and some variations on it)

```c++
struct A {
    void apply(hid_t hid) const
    {
        std::cout << "Adding insertion order property";
        auto status = H5Pset_link_creation_order(hid, H5P_CRT_ORDER_TRACKED | H5P_CRT_ORDER_INDEXED);
        if (status < 0) {
            std::cout << "error";
        }
    }
};

int main()
{
    HighFive::File f("test.hdf5", HighFive::File::Truncate);

    A aProp;
    auto rootG = f.getGroup("/");
    auto rpcl = rootG.getCreatePropertyList();
    rpcl.add(aProp);

    auto fCreateProps = HighFive::GroupCreateProps();
    fCreateProps.add(aProp);
    auto b = rootG.createGroup("b", fCreateProps);
    rootG.createGroup("a", fCreateProps);

    b.createGroup("d", fCreateProps);
    b.createGroup("c", fCreateProps);
}

```

I have had some success for groups that are not direct children of the root (in the example, `d` and `c`). When I run that code, in python, using h5py I get the following

```python
>>> [print(i) for i in f["/"]]                                                                                                                                
a                                                                                                                                                             
b                                                                                                                                                             
[None, None]

>>> [print(i) for i in f["/b"]]                                                                                                                               
d                                                                                                                                                            
c                                                                                                                                                             
[None, None]
```

which clearly shows that under the group `b` the ordering is being track, but not under the root group. 

Is there anyway I can add the property to the root group, or even better, to the file itself so all the groups inherit from it?

**Comment by alkino** [comment]
```c++
HighFive::File(const std::string& filename,
               unsigned openFlags,
               const FileCreateProps& fileCreateProps,
               const FileAccessProps& fileAccessProps = FileAccessProps::default());
```

This is the signature you want.

```c++
A aProps;
auto fCreateProps = HighFive::FileCreateProps();
fCreateProps.add(aProp);
HighFive::File f("test.hdf5", HighFive::File::Truncate, fCreateProps);
```

You can get the properties' lists but only for reading, you cannot modify them on the fly.

I encourage you to make a new PR to add this property as an object in the current code, it will be great!

**Comment by jjcasmar** [comment]
Works fine for setting the track order property to the root group. There is no way to set it for the whole file, so I dont have to specify this property if I want to track order in other places, right?

Ill do a PR, sure!

**Comment by alkino** [comment]
In fact, it does not seem, but this question belong the to the HDF5 upstream forum.
Let us know if there is an hdf5 way. If yes, we can look how do it in HighFive side ;)

**Comment by jjcasmar** [comment]
I think there is a way, because hdfview shows if the order is being tracked for the file 
![image](https://user-images.githubusercontent.com/2644001/208902451-3e8cd295-7aaf-4f56-8b2c-ee5c5f14462d.png)

I will ask in hdf5 forum.

**Comment by jjcasmar** [comment]
Other option would be to allow to modify the Default property list. Default can mean different things for each project, and could be nice to override the default behavior such the GroupCreateProps::Default() can return a property list with properties predefined by the user. 

```
    /// Return the Default property type object
    static const PropertyList<T>& Default() noexcept {
        auto pl = static_cast<const PropertyList<T>&>(PropertyListBase::Default());
        using HighFive::detail::addProperties;
        addProperties(pl);
        return pl;
    }
```

The addProperties function could be found via ADL, so if the user provides an implementation of it inside HighFive namespace, it would be found. That way, we can overwrite the default behavior at a global level, instead of having to add the property list to all the calls of createGroup.

What do you think?

**Comment by alkino** [comment]
@jjcasmar Can we know which version of HighFive you use?

**Comment by alkino** [comment]
About be able to change the default, we are not really fond of this idea because it will be too much complex to handle.
If your usage is really large, you should wrap HighFive with your own library taking care of your own user types. In this wrapper it becomes really easy to overload default by setting properties at files creation.

**Comment by alkino** [comment]
https://github.com/BlueBrain/HighFive/pull/683 <= merged in last version
