### ISSUE TITLE
Dump Eigen Map doesn't work for HighFive::Group

### ISSUE THREAD

**Issue by jjcasmar** [BlueBrain/HighFive#694]
I am, trying to dump an `Eigen::Map<Eigen::Matrix<>>` using
```c++
group.createDataSet("VERTICES",
                    Eigen::Map<Eigen::Matrix<const float, Eigen::Dynamic, 3, Eigen::RowMajor>>(
                    meshPoints.data(), meshPoints.size() / 3, 3));
```
with `group` being a `HighFive::Group`, but it doesn't compile, throwing this error:
```
[build] /workspace/src/deSim/HookPlugins/HDF5Plugin/HDF5Plugin.cpp:83:77:   required from here
[build] /home/seddi/.conan/data/highfive/2.6.2/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include/highfive/bits/H5Converter_misc.hpp:110:23: error: static assertion failed: The type is not trivially copyable
[build]   110 |         static_assert(is_trivially_copyable, "The type is not trivially copyable");

**Comment by alkino** [comment]
`Eigen::Matrix` is supported but not `Eigen::Map`.

**Comment by 1uc** [comment]
Also this:
https://github.com/BlueBrain/HighFive/issues/532

As long as you only read and write with HighFive the bug is consistent and will read things back consistently. However, if you read data not created by writing a `Eigen::Matrix` via HighFive, then almost all entries will be incorrect.

The very ugly part is if we fix the bug, then loading an `Eigen::Matrix` which was written with an older version of HighFive will be broken (and in general we can't detect the issue).

**Comment by jjcasmar** [comment]
Works fine using the H5Easy::dump API though when dumping an Eigen::Map.

**Comment by jjcasmar** [comment]
For the #532 issue I am actually setting the Eigen::RowMajor bit.

**Comment by jjcasmar** [comment]
This code works fine and its dumping an Eigen::Map
```
        H5Easy::dump(group.getFile(),
                     fmt::format("{}/INDICES", group.getPath()),
                     Eigen::Map<const Eigen::Matrix<unsigned int, Eigen::Dynamic, 3, Eigen::RowMajor>>(
                         indices.data(), static_cast<Eigen::Index>(indices.size() / 3), 3));
```
so I guess Eigen::Map is somehow supported or something really weird is happening. Also, Eigen::Map implements the same API as the underlying Eigen::Matrix, so I dont get any reason not to support it. 

Should I add a PR?

**Comment by alkino** [comment]
The code of HighFive is splitted in two. The core one, and the easy one. `Eigen::Map` is supported in Easy but not in core.

The same for `RowMajor` / `ColMajor` not supported in core.

**Comment by jjcasmar** [comment]
Fair enough. I will use H5Easy API. Just a bit unconvenient that we need to pass the `HighFive::File` and do something like
```
H5Easy::dump(group.getFile(), group.getPath...)
```
instead of 
```
H5Easy::dump(group, ...)
```
directly

**Comment by tdegeus** [comment]
There latter overload can be discussed! If your are up for it you can open a PR

**Comment by jjcasmar** [comment]
Ill try to do a PR asap

**Comment by 1uc** [comment]
From v3 onwards this should be supported.
