### ISSUE TITLE
Update GHA for mac.

### ISSUE THREAD

**Issue by 1uc** [BlueBrain/HighFive#704]
We're getting the following warning from GHA:

> 
> HighFive_CI: .github#L1
> The macOS-10.15 environment is deprecated, consider switching to macos-11(macos-latest), macos-12 instead. For more details see https://github.com/actions/virtual-environments/issues/5583
> 

We'll likely need to slightly modernize our CI for mac.

**Comment by tdegeus** [comment]
I think we should just run with `latest`

**Comment by 1uc** [comment]
The downside of that is that that then our CI breaks whenever `latest` changes. When that happens fixing CI is the number one and only priority and will prevent merging anything else.

Personally, I'm not very keen on that type of setup, since I fear Murphy's law, i.e. it'll break when we need to merge something urgently, but don't have the time to fix CI for a new OS. (We'd have time a few weeks later or before, just not right then.)

**Comment by tdegeus** [comment]
Things should not break if `latest` changes ;) And if they do we should know soon as possible, as users will also be updating. 

I would not worry however that it would become a blocker. If this happens we can always quickly downgrade the CI on order to still have passing checks. In addition, that is a special case anyway that needs special attention anyway. 

My personal strategy is to only hardcode when needed, not to hardcode when possibly useful. 

But, whatever you want ;).

**Comment by pramodk** [comment]
> The downside of that is that then our CI breaks whenever latest changes.

Don't have a strong opinion but have similar experiences with some other projects. Especially (**if/**) when rely on some of the stuff "custom sauce or updates" that GitHub and/or Azure actions runners are shipped with.
