### ISSUE TITLE
Potential regression when writing booleans

### ISSUE THREAD

**Issue by ischoegl** [BlueBrain/HighFive#713]
**Describe the bug**

A recent update (2.7.0?) appears to be have broken the ability of writing boolean attributes; the breakage appears to be limited to the conda package, as I am unable to reproduce it with the main branch.

**To Reproduce**

Among other data types, we use HighFive to write attributes containing booleans and boolean arrays. We use the following approach:

```c++
namespace h5 = HighFive;

enum class H5Boolean {
    FALSE = 0,
    TRUE = 1,
};

h5::EnumType<H5Boolean> create_enum_boolean() {
    return {{"FALSE", H5Boolean::FALSE},
            {"TRUE", H5Boolean::TRUE}};
}

HIGHFIVE_REGISTER_TYPE(H5Boolean, create_enum_boolean)
```
which is used to eventually either write a scalar `bool bValue`

```C++
            H5Boolean value = bValue ? H5Boolean::TRUE : H5Boolean::FALSE;
            h5::Attribute attr = sub.createAttribute<H5Boolean>(
                name, h5::DataSpace::From(value));
            attr.write(value);
```

or a `vector<bool> bValue`

```C++
            vector<H5Boolean> values;
            for (auto b : bValue) {
                values.push_back(b ? H5Boolean::TRUE : H5Boolean::FALSE);
            }
            h5::Attribute attr = sub.createAttribute<H5Boolean>(
                name, h5::DataSpace::From(values));
            attr.write(values);
```

In either case the following error is thrown when attempting to write:

```
Size of array type 4 != that of memory datatype 1
```

**Expected behavior**

Until March 31st, the above code worked for both conda package and compilations using the HighFive git submodule. At this point, it still works for the current main (559bd8565f001984013a0c7a215ef19503855884), but fails as described above for the conda package.

**Desktop (please complete the following information):**

 - OS: macOS (same failure also observed on linux) 
 - Version 2.7.0; conda package only(?)

**Additional context**

The problem may be limited to the conda package on `conda-forge`, with the following details

```
$ conda list
[...]
highfive                  2.7.0                h0747e88_0    conda-forge
[...]
```

**Comment by 1uc** [comment]
Thank you for reporting the issue. A quick look suggests that it's related to the fact that we've fixed boolean support, in the same way you seem to have implemented it yourself (if I understand the snippet correctly). See,
https://github.com/BlueBrain/HighFive/blob/c6ffef489a919c0c745a2c24f3a5615088560a47/include/highfive/bits/H5DataType_misc.hpp#L209

Note that we've added a function `create_enum_boolean` which might clash with the one you're mentioning.

This is just a hunch, and I'll look into it more carefully.

**Comment by ischoegl** [comment]
@1uc ... thanks for the quick response! A clash of names with a newly introduced variable *does* explain things. I have some initial evidence that renaming our function resolves the issue. I will report back once I see what our CI is doing.

**Comment by ischoegl** [comment]
I verified that renaming the function resolves the issue. Thanks!

**Comment by 1uc** [comment]
Nice to hear it's resolved!

I've checked that we namespace our register invocation:
https://github.com/BlueBrain/HighFive/blob/c6ffef489a919c0c745a2c24f3a5615088560a47/include/highfive/bits/H5DataType_misc.hpp#L506

I suspect (and hope) that fully naming the function when registering it would also work, e.g.,
```
# Version if `create_enum_boolean` lives in the global namespace.
HIGHFIVE_REGISTER_TYPE(H5Boolean, ::create_enum_boolean)

# Variation if it lies in `app`.
HIGHFIVE_REGISTER_TYPE(H5Boolean, ::app::create_enum_boolean)
```

**Comment by ischoegl** [comment]
@1uc ... yes, I can confirm that using the full name `::create_enum_boolean` likewise resolves the issue.

As 2.7.0 removes the need for us to implement `create_enum_boolean` ourselves, I started to experiment with the new capability. One issue I am currently running into is that 
```c++
typedef HighFive::details::Boolean H5Boolean;
```
works when I use the `conda` package, but it fails with the following error if I check out the git module with version `v2.7.0`:
```
error: no type named 'Boolean' in namespace 'HighFive::details'
```

As an aside, I believe the `VERSION` file in the root folder is obsolete as it is now set in `CMakeLists.txt` instead?

**Comment by ischoegl** [comment]
I am still wondering why `create_enum_boolean` appears outside of the `HighFive` namespace? - We are *not* `using namespace HighFive` anywhere in our code. Is this a bug after all?

**Comment by ischoegl** [comment]
> I've checked that we namespace our register invocation:
> 
> https://github.com/BlueBrain/HighFive/blob/c6ffef489a919c0c745a2c24f3a5615088560a47/include/highfive/bits/H5DataType_misc.hpp#L506

Actually, I believe your namespace ends the line before, which would explain the behavior?

**Comment by 1uc** [comment]
First regarding `create_enum_boolean`. The macro is defined as:
```
#define HIGHFIVE_REGISTER_TYPE(type, function)                    \
    template <>                                                   \
    inline HighFive::DataType HighFive::create_datatype<type>() { \
        return function();                                        \
    }
```
When performing:
```
HIGHFIVE_REGISTER_TYPE(H5Boolean, create_enum_boolean)
```
it'll expand to:
```
    template <>                                                   \
    inline HighFive::DataType HighFive::create_datatype<type>() { \
        return create_enum_boolean();                                        \
    }
```
which means that since `create_datatype` lives inside `HighFive`, I think it should pick up the version `HighFive::create_enum_boolean` not `::create_enum_boolean`. My hope is that
```
HIGHFIVE_REGISTER_TYPE(H5Boolean, ::create_enum_boolean)
```
would protect from this issue since it would expand to:
```
    template <>                                                   \
    inline HighFive::DataType HighFive::create_datatype<type>() { \
        return ::create_enum_boolean();                                        \
    }
```
which should refer to the function defined in global scope.

**Comment by ischoegl** [comment]
Hi @1uc ... thanks for your explanations. Yes, `::create_enum_boolean` does prevent the failure.

Regarding some of the other issues I mentioned, I *believe* I tracked one down on my side, while the compiler dependence is really limited to MSVC - it likely is related to some of the new issues and PR's that I saw popping up.

**Comment by 1uc** [comment]
Yes, there's a good chance you'll see issues related to macros clashing. However, the CI you linked contained something else too. Can we continue that discussion here #724?
