### ISSUE TITLE
Write to DataSet from a pointer to a multidimensional array

### ISSUE THREAD

**Issue by michaelbuehlmann** [BlueBrain/HighFive#74]
I have some data that is on a 3D grid with dimensions [n, n, n], but I only have the pointer to this data array. If I try to store it as a [n, n, n] `DataSet`, I get the following error:

```
  terminate called after throwing an instance of 'HighFive::DataSpaceException'
  what():  Impossible to write buffer of dimensions 1 into dataset of dimensions 3
```

Also wrapping the array using a `boost::multi_array_ref` doesn't work, as `DataSet::write` only accepts a pure `boost::multi_array`, and I get linking errors using the ref array.

It would be nice to add this functionality to this really nice library! (Or maybe I just missed something...)

**Comment by adevress** [comment]
Hi michaelbuehlmann,

One way to do it currently is to pass to Highfive the data cast as a datatype*** pointer. The template system should correctly detect that you are working with 3 dimensional dataset.

Can you post here the code associated with that ?

**Comment by michaelbuehlmann** [comment]
Hi!
Thank you for your answer and sorry for the late reply. Yes, this works perfectly, thank you :)
