### ISSUE TITLE
Add the Block parameter to dataset.selection

### ISSUE THREAD

**Issue by L-M-V** [BlueBrain/HighFive#77]
Is it possible to add the block parameter to the dataset selection function (or is there a better practice in HighFive)?

The current code has a different sized block depending if the current processor is on the 'edge' of the 3d space. For example:
```C++
const auto blockX= mpi.rankX() >0 ? nx - 1 : nx;
const auto blockY= mpi.rankY() >0 ? ny - 1 : ny;
const auto blockZ= mpi.rankZ() >0 ? nz - 1 : nz;

const std::vector<hsize_t> block = { blockX, blockY, blockZ };

auto dataset = file.createDataSet<double>(dimensionName, fileDataspace);
auto selection = dataset.select(offset, count, stride, block);
selection.write(output);
```

**Comment by alkino** [comment]
I hope, you stop to wait for that, but hey, now it will be there!
