### ISSUE TITLE
oneAPI not ready for -Werror ?

### ISSUE THREAD

**Issue by aminiussi** [BlueBrain/HighFive#776]
**Describe the bug**
Some cmake configuration option add a -Werror with oneAPI, wich crash the compiler on a unused command line option warning.

**To Reproduce**

 1. Load Intel OneAPI environement
 2. Configure with -DCMAKE_BUILD_TYPE:STRING=RelWithDebInfo <path to 82aa8ca5e6756cbfe8f015e7329a2fde879335b4>
 3. Run make, it will crash at the firt oneAPI warning, in my case: 
 ```[ 60%] Building CXX object _deps/highfive-build/src/examples/CMakeFiles/compound_types_bin.dir/compound_types.cpp.o
icpx: error: -Wl,-rpath,/data/spack/opt/spack/linux-centos7-x86_64/gcc-12.2.0/intel-oneapi-mkl-2023.1.0-x6dxpakvvn4sntkmbzqvtjdndc3g5ttn/mkl/2023.1.0/lib/intel64: 'linker' input unused [-Werror,-Wunused-command-line-argument]
make[2]: *** [_deps/highfive-build/src/examples/CMakeFiles/compound_types_bin.dir/compound_types.cpp.o] Error 1
```

**Expected behavior**
Do not crash, as warning happens and are difficult to anticipate in an exhaustive way.

**Stacktrace**
If applicable, add a stacktrace and error messages to help explain your problem.

**Desktop (please complete the following information):**
 - OS: CentOS 7
 - Version 82aa8ca5e6756cbfe8f015e7329a2fde879335b4

**Additional context**

The problem seems to be in `CMake/config/CompilerFlagsHelpers.cmake`, but I'm not sure why -Werror was added to that specific flags. Specially considering it will apply to all warnings, not just those specifid

```
OR CMAKE_${COMPILER_LANGUAGE}_COMPILER_ID MATCHES "Intel")
                set(CMAKE_${COMPILER_LANGUAGE}_WARNING_ALL " -Wall -Wextra")
                string(CONCAT CMAKE_${COMPILER_LANGUAGE}_WARNING_DEBUG
			" -Werror -Wshadow -Wnon-virtual-dtor -Wunused -Woverloaded-virtual"
                        " -Wformat=2 -Wconversion -Wsign-conversion -Wno-error=deprecated-declarations"
                )
                if(NOT CMAKE_${COMPILER_LANGUAGE}_COMPILER_IS_ICC)

```

Thanks

**Comment by aminiussi** [comment]
As a side note, in the same file, there is a mention of `CMAKE_${COMPILER_LANGUAGE}_COMPILER_IS_ICC` that I was unable to find in cmake documentation ? 

Sheers

**Comment by alkino** [comment]
I quickly fix the usage of `CMAKE_${COMPILER_LANGUAGE}_COMPILER_IS_ICC` in #777

**Comment by aminiussi** [comment]
Oups, no -Werror in the current master.

**Comment by 1uc** [comment]
Yes, `-Werror` has been deleted =) I prefer the solution you mentioned elsewhere, which was to replace `MATCH` with `STREQUAL` or to just let the compiler be "mad" since now it's just a warning.
