### ISSUE TITLE
Cannot create very large attributes

### ISSUE THREAD

**Issue by ccorti87** [BlueBrain/HighFive#783]
**Describe the bug**
When trying to create an attribute of type `vector<double>` with 9000 items, HighFive fails with the following error:
> HDF5-DIAG: Error detected in HDF5 (1.10.7) thread 1:
  #000: ../../../src/H5A.c line 285 in H5Acreate2(): unable to create attribute
    major: Attribute
    minor: Unable to initialize object
  #001: ../../../src/H5Aint.c line 275 in H5A__create(): unable to create attribute in object header
    major: Attribute
    minor: Unable to insert object
  #002: ../../../src/H5Oattribute.c line 332 in H5O__attr_create(): unable to create new attribute in header
    major: Attribute
    minor: Unable to insert object
  #003: ../../../src/H5Omessage.c line 219 in H5O__msg_append_real(): unable to create new message
    major: Object header
    minor: No space available for allocation
  #004: ../../../src/H5Omessage.c line 1904 in H5O__msg_alloc(): unable to allocate space for message
    major: Object header
    minor: Unable to initialize object
  #005: ../../../src/H5Oalloc.c line 1304 in H5O__alloc(): object header message is too large
    major: Object header
    minor: Unable to initialize object
Error in <TRint::HandleTermInput()>: HighFive::AttributeException caught: Unable to create the attribute "rig": (Object header) Unable to initialize object

**To Reproduce**
```cpp
#include <highfive/H5File.hpp>
#include <highfive/H5Group.hpp>
#include <numeric>
#include <vector>

int main() {
   std::vector<double> rig(9000);
   std::iota(rig.begin(), rig.end(), 0);

   HighFive::File f("test.h5", HighFive::File::ReadWrite | HighFive::File::Create | HighFive::File::Truncate);
   auto g = f.createGroup("info");
   f.createAttribute("rig", rig);

   return 0;
}
```

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Version v2.7.1

**Additional context**
This seems to be the same problem as reported in [this h5py issue](https://github.com/h5py/h5py/issues/1053).
I tried the suggested workaround of forcing attributes to use dense storage, but to no avail:
```cpp
#include <highfive/H5File.hpp>
#include <highfive/H5Group.hpp>
#include <numeric>
#include <vector>

int main() {
   std::vector<double> rig(9000);
   std::iota(rig.begin(), rig.end(), 0);

   HighFive::File f("test.h5", HighFive::File::ReadWrite | HighFive::File::Create | HighFive::File::Truncate);
   auto g = f.createGroup("info");
   H5Pset_attr_phase_change(g.getCreatePropertyList().getId(), 0, 0); // force dense storage
   f.createAttribute("rig", rig);

   return 0;
}
```
This code fails with the same error.

I can always use a dataset instead of an attribute, but it would be nice if large attributes were supported.

**Comment by ccorti87** [comment]
For reference, I can successfully create a `vector<double>` attribute of size 8183, but it fails for larger sizes.
This threshold is very close to the 64 kb limit for the maximum size of an attribute to be stored in the default compact storage.

**Comment by ccorti87** [comment]
I never used pure HDF5, so I won't be able to provide such an example.

If I create the property list before creating the group, then `H5Pset_attr_phase_change` fails:
```cpp
#include <highfive/H5File.hpp>
#include <highfive/H5Group.hpp>
#include <numeric>
#include <vector>

int main() {
   std::vector<double> rig(9000);
   std::iota(rig.begin(), rig.end(), 0);

   HighFive::File f("test.h5", HighFive::File::ReadWrite | HighFive::File::Create | HighFive::File::Truncate);
   auto props = HighFive::GroupCreateProps::Default();
   H5Pset_attr_phase_change(props.getId(), 0, 0); // force dense storage
   auto g = f.createGroup("info", props);
   g.createAttribute("rig", rig);

   return 0;
}
```
> HDF5-DIAG: Error detected in HDF5 (1.10.7) thread 1:
  #000: ../../../src/H5Pocpl.c line 237 in H5Pset_attr_phase_change(): can't find object for ID
    major: Object atom
    minor: Unable to find atom information (already closed?)
  #001: ../../../src/H5Pint.c line 3822 in H5P_object_verify(): property list is not a member of the class
    major: Property lists
    minor: Unable to register new atom
  #002: ../../../src/H5Pint.c line 3772 in H5P_isa_class(): not a property list
    major: Invalid arguments to routine
    minor: Inappropriate type

**Comment by 1uc** [comment]
I think internally the `HighFive::*Props` all store an invalid ID until a property is set via the HighFive mechanism. However, `getId` likely doesn't know about this an just returns the ID (which would be invalid). 

This sounds a lot like it's a bug. I'll look into it.

**Comment by 1uc** [comment]
In #785 there's an example of how to make it work. You could either use the the branch (and then `master`); or you can copy the `PropertyList` related code into your own namespace and use it that way; then once it's in a release you can use it from there (or stick with the local version).

Naturally, this doesn't fix the issue with:
```
   auto props = HighFive::GroupCreateProps::Default();
   H5Pset_attr_phase_change(props.getId(), 0, 0); // force dense storage
```
failling. Which we'll address separately, see #786.

**Comment by ccorti87** [comment]
Great, thank you very much!
