### ISSUE TITLE
vector of string to FixedLenStringArray droppoing the last element

### ISSUE THREAD

**Issue by ronzhou** [BlueBrain/HighFive#791]
**Describe the bug**
When transfering a vector of string to FixedLenStringArray, the last element will get lost.

**To Reproduce**
```cpp
std::vector<std::string> x{"abc", "def"};
HighFive::FixedLenStringArray<3> arr(x);
std::cout << x.size() << ":" << arr.size() << std::endl;
assert(x.size() == arr.size() && "size must equal");
```

**Comment by 1uc** [comment]
I think this is due assumptions about what a string is, precisely. The string literal `"abc"` is 4 elements long `a`, `b`, `c` and `\0'. As far as I can tell from looking at the code, e.g.,
https://github.com/BlueBrain/HighFive/blob/db6f31e578539962f0cc0ba8c59d557b115464b4/include/highfive/bits/H5DataType_misc.hpp#L335-L338

HighFive assumes that all strings are null-terminated and enforces this fact. Please try:
```
HighFive::FixedLenStringArray<4> arr(x);
```

**Comment by 1uc** [comment]
We're currently working towards supporting strings more cleanly, see #744.

**Comment by ronzhou** [comment]
It still raise the size unequal assertion error after change the length from 3 to 4.

**Comment by ronzhou** [comment]
@1uc It still raise the size unequal assertion error after change the length from 3 to 4.

**Comment by 1uc** [comment]
You're right, and I didn't read sufficiently carefully. There's a PR that addresses the bug #797. Does it fix the issue?
