### ISSUE TITLE
Simplify creation of property lists

### ISSUE THREAD

**Issue by jjcasmar** [BlueBrain/HighFive#800]
Right now, to create a property list, we must first creation the PropertyList<> object and then add the particular properties we need

For example, for LinkCreationOrder, we have to do

```
    HighFive::GroupCreateProps gcpl;
    gcpl.add(HighFive::LinkCreationOrder{HighFive::CreationOrder::Indexed | HighFive::CreationOrder::Tracked});
```

I think it would be easy to provide a variadic constructor so we can pass the properties directly during the creation of the PropertyList, so we can do

```
    HighFive::GroupCreateProps(std::make_tuple(HighFive::LinkCreationOrder{HighFive::CreationOrder::Indexed | HighFive::CreationOrder::Tracked}));
```

The tuple is needed so we can create an overload to differentiate from the copy constructor. 
Does this make sense?

**Comment by 1uc** [comment]
I agree that the properties really aren't very elegant. Therefore, yes, improving the situation would be helpful. I'm not sure this makes it simpler for the following reasons:

1. The proposal needs an `std::make_tuple` for the sole purpose of appeasing the compiler (conflict with copy ctor). I'm not sure it's immediately obvious to the user that the compiler would complain, and why an `std::make_tuple` is the obvious fix.
2. The suggestion doesn't save characters typed (+10) or concepts (+ put everything in a tuple, - need to add stuff).

Hence, to me it looks like it doesn't make it simpler for the user, but adds something we need to maintain, i.e. adds complexity for the developers.

One of the things to figure out would be if we really need the `std::make_tuple`. The compiler should be able to distinguish the copy ctor from other (single argument) ctors based on types; `Properties` are never `PropertyLists`. Hence one could tell the difference (and use some template magic).

The other issue, again related to putting properties into an `std::tuple`, is that some properties carry state with non-trivial ownership semantics. For example, some contain a `MPI_Comm`. We've not yet added the code required to read such properties.

However, if we could get to something like:
```
    HighFive::GroupCreateProps gcpl(
        HighFive::LinkCreationOrder{HighFive::CreationOrder::Indexed | HighFive::CreationOrder::Tracked},
        HighFive::SomeGroupProperty(...)
    );
```
I'd start to see an advantage.

**Comment by 1uc** [comment]
In the interest of only keeping tickets open that we intend to work on, I'm closing this one.

If anyone wants to work on this ticket, they should feel free to reopen the ticket.
