### ISSUE TITLE
Remove PropertyType::OBJECT_COPY and PropertyType::OBJECT_CREATE

### ISSUE THREAD

**Issue by alkino** [BlueBrain/HighFive#812]
Those 2 properties are only place holders to mean several properties like dset_create, and group_create.

**Comment by 1uc** [comment]
@alkino is this still something you want to remove?

**Comment by alkino** [comment]
Yes, because those both words does not really exist. In the doc they mean it can be: file, group or dataset most of the time.

**Comment by 1uc** [comment]
Removed by #1002.
