### ISSUE TITLE
Options for latest intel compiler

### ISSUE THREAD

**Issue by VictorEijkhout** [BlueBrain/HighFive#815]
```
icpx: command line warning #10430: Unsupported command line options encountered
These options as listed are not supported.
For more information, use '-qnextgen-diag'.
option list:
        -wd1682
```

This is Intel 2023.1

**Comment by 1uc** [comment]
Thank you, looks like the same as #776. Does it just cause a warning, or does it actually break something?

**Comment by VictorEijkhout** [comment]
Warning only.

**Comment by 1uc** [comment]
Thank you. I'll close it in favour of #816 which suggest setting warning flags in a manner that avoid them from propagating to users of HighFive.
