### ISSUE TITLE
Conda package?

### ISSUE THREAD

**Issue by wolfv** [BlueBrain/HighFive#83]
Hi, I wanted to ask if you would be interested in packaging High Five as a conda package (e.g. through conda-forge)?
I would like to use it as a dependency for `xtensor-io` (https://github.com/QuantStack/xtensor-io).

Cheers!
Wolf

**Comment by adevress** [comment]
Hi wolfv,
I am not experienced in conda packaging but I have nothing against the idea to help if someone want to start it.
However, like HighFive is purely header-only, would you see any issue to add it in your project as git submodule ?
As long as you are not exporting any HighFive functions / class, it should not be an issue.

**Comment by adevress** [comment]
I close that. Feel free to Re-open if anyone want to package that

**Comment by wolfv** [comment]
hey @adevress just wanted to let you know that we've indeed started to package highfive for conda. 

Currently it lives on the `quantstack` channel (https://anaconda.org/search?q=highfive) but hopefully we can soon push the recipe to conda-forge to make it available to the bigger community.

**Comment by wolfv** [comment]
(it's necessary because that's how we distribute `xtensor-io` where we're close to integrate HighFive).
