### ISSUE TITLE
writing and reading 2d C array

### ISSUE THREAD

**Issue by basegpu** [BlueBrain/HighFive#84]
I have the following working example:

~~~c
#include <string>
#include <vector>
#include <iostream>
#include <highfive/H5File.hpp>
#include <highfive/H5DataSet.hpp>
#include <highfive/H5DataSpace.hpp>

namespace h5 = HighFive;
using namespace std;

const string FILE_NAME("test.h5");
const string DATASET_NAME("dset");
const int ROWS(5);
const int COLS(2);

int main(void) {
	h5::File file(FILE_NAME, h5::File::ReadWrite | h5::File::Create | h5::File::Truncate);

	vector<size_t> dims(2);
	dims[0] = ROWS;
	dims[1] = COLS;

	// dynamically allocate C array (2d)
	double **data = (double **)calloc(ROWS, sizeof(double *));
	data[0] = (double *)calloc(ROWS*COLS, sizeof(double));
	for (int ii = 1; ii < ROWS; ii++) {
		data[ii] = data[0] + ii * COLS;
	}

	// put some values
	for (int ii = 0; ii < ROWS; ii++) {
		for (int jj = 0; jj < COLS; jj++) {
			data[ii][jj] = (double)(ii*COLS + jj);
			cout << "data[" << ii << "][" << jj <<"] = " << data[ii][jj] << endl;
		}
	}

	// writing the dataset
	h5::DataSet dataset = file.createDataSet<double>(DATASET_NAME, h5::DataSpace(dims));
	dataset.write(data);
	file.flush();

	// reading the dataset
	double **data_read = NULL;
	dataset = file.getDataSet("dset");
	// dataset.read(data_read);
	// for (int ii = 0; ii < ROWS; ii++) {
	// 	for (int jj = 0; jj < COLS; jj++) {
	// 		cout << data[ii][jj] << " <-> " << data_read[ii][jj];
	// 	}
	// }

	// free memory
	free(data);
	free(data[0]);

        return 0;
}
~~~

Two questions/problems:
1. the the printed values in `data` look okay, but the written values in `test.h5` are wrong. where is the error? in my example or in the HighFive?
2. reading back the 2d dataset into a C-array does not work at all. I get the runtime error

> HDF5-DIAG: Error detected in HDF5 (1.8.16) thread 139984454051648:
>  #000: ../../../src/H5Dio.c line 173 in H5Dread(): can't read data
>    major: Dataset
>    minor: Read failed
>  #001: ../../../src/H5Dio.c line 443 in H5D__read(): no output buffer
>    major: Invalid arguments to routine
>    minor: Bad value
>terminate called after throwing an instance of 'HighFive::DataSetException'
>  what():  Error during HDF5 Read:  (Invalid arguments to routine) Bad value

Do I expect too much simplicity and flexibility of the HighFive API?
Looking forward to the feedbacks...cheers

**Comment by adevress** [comment]
Hi,

By doing the following 

```
double **data = (double **)calloc(ROWS, sizeof(double *));
	data[0] = (double *)calloc(ROWS*COLS, sizeof(double));
	for (int ii = 1; ii < ROWS; ii++) {
		data[ii] = data[0] + ii * COLS;
	}
```

You allocate an array of pointer, where each pointer its a single dimensional array.
This is unfortunately not what libHDF5 expect. LibHDF5 expect a single-continuous-array of dimension S = ROWS * COLS. 

If you want to do use a two dimensional array and store / reload it you can:
- Use a continuous C style stack allocated array like in this example https://github.com/BlueBrain/HighFive/blob/master/src/examples/create_dataset_double.cpp
- use a continuous C array dynamically allocated where you do the indexing yourself.
- Use C++ and use a "vector of vector". HighFive do the necessary trick to make this works.
- Use Boost.UBLAS and its matrix class, which is transparently map to a two dimensional array.

Adev

**Comment by adevress** [comment]
I close this, please re-open if you need more help

**Comment by basegpu** [comment]
thx for your comments.

finally it worked! the way I allocated and indexed the memory of the c-array was fine (the same as you suggested). passing the array for writing to a dataset actually worked with
~~~c
...
// dynamically allocate C array (2d)
double **data = (double **)calloc(ROWS, sizeof(double *));
data[0] = (double *)calloc(ROWS*COLS, sizeof(double));
for (int ii = 1; ii < ROWS; ii++) {
	data[ii] = data[0] + ii * COLS;
}
...
dataset.write((double**) data[0]);
...
~~~
