### ISSUE TITLE
Retrieve offset of dataset

### ISSUE THREAD

**Issue by wolfv** [BlueBrain/HighFive#87]
I'm not sure wether it's currently possible or not: I would like to retrieve the offset of a dataset inside the HDF5 file, in order to obtain a pointer with `mmap`. This enables high-performance reading of extremely large datasets. 

E.g. in Python: https://gist.github.com/maartenbreddels/09e1da79577151e5f7fec660c209f06e

**Comment by adevress** [comment]
Hi wolfv,

I would honestly not do that. 
For the good reason that this would explode if you are trying to read chunked or compressed datasets, or simply a datasets in a different endianness.
I also do not think you are going to have any performance benefit compare to a normal read / write pattern ( excepted if you try to do very little reads ).

But if you still want to do it, you can manually by using the C API and DataSet.getId() 

https://support.hdfgroup.org/HDF5/doc/RM/RM_H5D.html#Dataset-GetOffset

**Comment by wolfv** [comment]
Thanks for the super-fast response!
This is @maartenbreddels so maybe he can weigh in... :)

**Comment by maartenbreddels** [comment]
I don't think it is a hack, but it will only work for continuous datasets. Endianness info is included in the hdf5 file, so you can make a decision based on that. And it will be faster when you are memory bandwith limited, you'll just directly read from the OS cache, no syscall and memory copy will be needed. It's an important part of why https://vaex.io is so fast.

**Comment by adevress** [comment]
> I don't think it is a hack, but it will only work for continuous datasets. Endianness info is included in the hdf5 file, so you can make a decision based on that.

@maartenbreddels  At this point, you are better to not use HDF5 at all read from a raw mapped file, because you anyway do not use any feature of HDF5 ^^.

If I understand why you do that in python, to avoid the conversion to-from numpy arrays, and the poor performance of slicing yourself, but it does not make sense in my mind to do it in C++.

Adev

**Comment by maartenbreddels** [comment]
Well, you don't want to lock your data in some new file format, and hdf5 can store about anything, including meta information. But, in vaex I open the hdf5 file just to get the meta information (and the offsets etc), then close it and memory map without using the hdf5 library. So yes, I don't really use the hdf5 library, but don't like to create yet another file format :)

**Comment by jrs65** [comment]
I've done this in the past to overcome limitations in the parallel API in `h5py`, i.e. I would pre-allocate a contiguous dataset, and then get the offset so I can have multiple processes lock the correct ranges and do parallel writes into the file. However, as @adevress says you can just do it with a few calls to the C-api.

**Comment by wolfv** [comment]
I agree that it might not be the good thing for every user, but this library would only have a nice way to expose a *feature* of HDF5 (which is retrieving the offset of a dataset). 

I get that it's possible to do it by hand by using the C-API and I can also do it, but it might be a functionality that's useful for other people in the future (doesn't necessarily have to be used for `mmap`ing stuff) and it would probably also not require that much code as part of this library.

I'll probably try making this feature and then I'll send you a PR and you can decide :)

**Comment by maartenbreddels** [comment]
Yes, I think it could be useful as well, i'm not a big fan of the C-api, so if that means I can use this library in the future that would make me happy :)

**Comment by adevress** [comment]
> I'll probably try making this feature and then I'll send you a PR and you can decide 

I'm fine with adding the a get_offset() method to the HighFive API, no problem for me :)

I just wanted to make clear that playing with mmap and HDF5 has limitations.

**Comment by adevress** [comment]
Implemented and merged with #89, thx to wolfv
