### ISSUE TITLE
Support creation of DataSpace from iterators or generic containers

### ISSUE THREAD

**Issue by wolfv** [BlueBrain/HighFive#88]
Currently, only `std::vector` is allowed in the creation of a `DataSpace`. It would be good if e.g. `std::array<...>` would be supported as well. A possible interface would be an overload taking a pair of iterators.

**Comment by adevress** [comment]
I agree. That's worth to add it for std::array.

For generic containers, the problem is that it does not make sense use for HDF5 C++ containers that are not continuous in memory.

**Comment by wolfv** [comment]
But you might have your own datatype defined for a shape type in some array library (such as LLVM's small_vector, for example, which is what we're planning to do very soon). Therefore, creating more overloads for each of these potential types seems not a feasible way to go. 

The iterator interface is pretty standard. And you could copy the `DataSpace` data internally to an std::vector or similar if you want and that's required.

**Comment by wolfv** [comment]
Anyways, that's pretty much what's happening here: 

https://github.com/BlueBrain/HighFive/blob/9459ddd4583916df0f867781247e254e4d14e208/include/highfive/bits/H5Dataspace_misc.hpp#L24-L25

**Comment by adevress** [comment]
> Anyways, that's pretty much what's happening here:

Yes, I am fine with the iterator interface, no problem for me.

**Comment by wolfv** [comment]
Cool! I'll make another PR

**Comment by adevress** [comment]
Merge with #90, thank you
