### ISSUE TITLE
Remove include of `<boost/serialize>`

### ISSUE THREAD

**Issue by 1uc** [BlueBrain/HighFive#893]
We should remove this include:
https://github.com/BlueBrain/HighFive/blob/c660174d43302b43616b87233631324eb96c8daf/include/highfive/bits/H5Inspector_misc.hpp#L26-L28

HighFive doesn't require `serialize` and shouldn't force the dependency on its users.

**Comment by matz-e** [comment]
I concur.

**Comment by 1uc** [comment]
Merged: #903
