### ISSUE TITLE
UTF-8 / ASCII convertion problem with string dataset

### ISSUE THREAD

**Issue by adevress** [BlueBrain/HighFive#9]
variable size string dataset to vector of string cause conversion issues with some specific string type.

Here is an example file that triggers the issue for /library/morphology
[circuit.mvd3.zip](https://github.com/BlueBrain/HighFive/files/158715/circuit.mvd3.zip)

**Comment by alkino** [comment]
I'm not sure we will address this issue. UTF-8 conversion is a nightmare.

**Comment by ferdonline** [comment]
@sergiorg-hpc This issue was recently resolved with #428
