### ISSUE TITLE
Write a table

### ISSUE THREAD

**Issue by HealthyPear** [BlueBrain/HighFive#916]
Hi,

premise: I only used HDF% via a Python interface written by other people, so I do not know (yet) the inner workings of this data format.

From C++ I need to write a table, i.e. a 2D dataset with columns each with its name and possibly different types such as,

| x  | y | name |
| ------------- | ------------- | --- |
| 0  | 1 | foo |
| 0.3  | 2.4  | bar |

I understand there is an implementation in pure HDF5 named `H5TB` but their documentation is not very easy and it seems that there is only a C and Fortran interface.

Is this possible from this project? I couldn't find this in your docs

thanks in advance

**Comment by 1uc** [comment]
Probably not, this is the first time I hear of tables in HDF5. There's a small chance that these tables are 1D arrays with a compound datatype, i.e. essentially a `std::vector<Row>` where row is:
```
struct {
double x;
double y;
std::string name;
};
```
if it is, there's some hope that it might work; but probably not because IIRC there's a bug related to strings inside compound datatypes.

What you can do is use HighFive to open the file get the group etc. Then once you've dealt with all that you can use `getId()` to get a plain HDF5 identifier and use it as the `loc_id` in:
```
 herr_t H5TBread_table( hid_t loc_id, const char *table_name, size_t dst_size,  const size_t *dst_offset, const size_t *dst_sizes, void *dst_buf )
```
So maybe something like:
```
auto file = HighFive::File("table.h5", HighFive::File::ReadOnly);
auto group = file.getGroup("some/group");

H5TBread_table(group.getId(), "table", ?, ?, ?, ?);
```

**Comment by alkino** [comment]
So `Table` in HDF-5 is not what you are looking for. Tables are from 1 to 4 dimensions but with an unique type inside.

Compoud is more what you are looking for. If the string is of fixed size, so yes we support it.
If the string is a variable length one, so we don't support it, as-is. But you can write some code for it. We can help you on that.

The easiest way to know what is inside your file is `h5dump`.
You can copy here the structure without the data.

**Comment by HealthyPear** [comment]
Thanks for the info!

I don't have a file, I have to write one.

What I need to do is build a table object row by row at runtime and when the user is ready to proceed to the next step, write the table to an HDF5 file.

I don't yet have a final data model, so I don't know exactly the composition of the columns in terms of datatypes, but starting from a simple example like the one I show above might be enough to start testing.

Regarding the fixed length I don't think I get it: what string are you referring to exactly?

**Comment by HealthyPear** [comment]
For reference if it can help I have found these alternatives,

- https://www.hdfgroup.org/wp-content/uploads/2019/01/HDF5Ntuple-final.pdf, some obscure academia repository
- https://forum.hdfgroup.org/t/writing-variables-of-different-types-to-a-dataset-table/7157/2, a different implementation of this project I guess (see [here](https://github.com/steven-varga/h5cpp))?

**Comment by alkino** [comment]
You mean like the slide `4`/`12` of the first slides?

This is not a table at all, this is explained as `Group` / `Dataset` that is a really basic and supported schema in `HighFive`.

We call it `SoA`: Structure Of Array in opposition of `AoS`: Array of Structures.

https://en.wikipedia.org/wiki/AoS_and_SoA

**Comment by alkino** [comment]
In `HDF5` it is possible to have fixed-length string and variable length string.

Fixed-length strings are of specific number of characters, variable length can have any size.
You can see that as:
fixed-length: `char[10]`: all strings have at most 10 chars, but it can be less as it is null-terminated.
variable-length: `std::string`: strings can be any size.

**Comment by HealthyPear** [comment]
I guess...when I say table I mean it in the common language: a set of columns each with its name all with the same number of rows

I get what fixed/variable string means, I mean how does this associate with the table: are you talking about the column names?

If what I need is already available without requiring new API in your project could you suggest an example to write build dummy table I show above and add it to a new file? An example like this might be also nice to have in your docs I think

**Comment by HealthyPear** [comment]
ah I also found this

https://support.hdfgroup.org/HDF5/Tutor/h5table.html

no idea while it seems disappeared from the new documentation tough...

**Comment by HealthyPear** [comment]
I guess the equivalent in Python would be this
https://www.pytables.org/usersguide/tutorials.html

**Comment by HealthyPear** [comment]
aha I think what I need is this

https://github.com/BlueBrain/HighFive/blob/master/src/examples/compound_types.cpp

**Comment by 1uc** [comment]
If you're free to pick how you store things then maybe what @alkino proposes is easy to deal with:
```
std::vector<double> xs;
std::vector<double> ys;
std::vector<std::string> names;

auto file = HighFive::File("table.h5", HighFive::Truncate); // Note: deletes the file before opening it.
auto group = file.createGroup("table");
group.createDataSet("x", xs);
group.createDataSet("y", ys);
group.createDataSet("name", names);
```
Each dataset is a column of the table. Personally, I find this layout quite convenient. Since if I only need one of the `x`, `y`, `name` values one can just read those. Additionally, one would be using only the most basic features of HDF5: groups and datasets of simple types (doubles and strings). This is quite easy to read back in other applications.

The issue with compound types is that if someone needs to read it back, they to deal with the compound datatype.

If you want to use other libraries, e.g. `pytables`, pandas, etc., to read the table you're not entirely free in how you structure the HDF5 file.

**Comment by HealthyPear** [comment]
Yes I'd like to open the resulting HDF5 in pytables later on (still planning and designing, but that's the idea)

also with the approach above when I try to open the file with [vitables](https://vitables.org/) (which should be based on pytables) then I get an error stating that variable size strings are not supported, while with the compound dataset example it seems to work

**Comment by alkino** [comment]
We can help you to use a specific hdf5 format with HighFive, it will be more difficult for us to choose the right hdf5 schema for your usage.

**Comment by 1uc** [comment]
@HealthyPear since I don't see anything we can do to help you, I'll close this issue. If while implementing the feature you have concrete issue, please re-open or open a new issue.
