### ISSUE TITLE
Intel options for OneAPI compiler

### ISSUE THREAD

**Issue by VictorEijkhout** [BlueBrain/HighFive#920]
Using the icpx Intel 2024 compiler:
```
icpx: command line warning #10430: Unsupported command line options encountered
These options as listed are not supported.
For more information, use '-qnextgen-diag'.
option list:
        -wd1682
```

**Comment by alkino** [comment]
Should be interesting to know the version you use, setting this option `-wd1682` have been removed in the last version 2.8.0.

https://github.com/BlueBrain/HighFive/commit/7340d1fcc7c455519c113216d8415e003ed37cc6

**Comment by 1uc** [comment]
Thank you for reporting the issue. How does it differ from: #815 and more importantly is the most recent version affected?

We've reworked how we handle warnings, AFAICT they're not added any targets consuming `HighFive` (since the warnings are `PRIVATE`). Moreover, the string `wd1682` seems to have vanished from the repo. Hence, I'm surprised that recent versions would be affected.

**Comment by VictorEijkhout** [comment]
It's still in the 2.7.1 release:
```
[staff highfive:416] grep wd16 /work2/00434/eijkhout/highfive/highfive-2.7.1/CMakeLists.txt
  add_definitions("-wd1682")
```

But it's only a warning and if it's gone from the next release then this is more or less solved.

**Comment by VictorEijkhout** [comment]
Oh, I thought I had the latest. Rebuilding 2.8.0.
```
In file included from /work2/00434/eijkhout/highfive/highfive-2.8.0/include/highfive/bits/H5Node_traits.hpp:15:
/work2/00434/eijkhout/highfive/highfive-2.8.0/include/highfive/bits/H5Converter_misc.hpp:182:68: warning: declaration shadows a field of 'StringBuffer<T, buffer_mode>' [-Wshadow]
  182 |         void assign(char const* data, size_t length, StringPadding padding) {
      |                                                                    ^
/work2/00434/eijkhout/highfive/highfive-2.8.0/include/highfive/bits/H5Converter_misc.hpp:324:19: note: previous declaration is here
  324 |     StringPadding padding;
      |                   ^
1 warning generated.
```

**Comment by 1uc** [comment]
Thanks for mentioning the issue. It's already been fixed on `master`:
https://github.com/BlueBrain/HighFive/blob/1299c556a992bea8aa03c3b75cca50560a5078b6/include/highfive/bits/H5Converter_misc.hpp#L182

**Comment by VictorEijkhout** [comment]
`Werror` is evil. I've run into cases where the compiler gives helpful hints on "this is legal but potentially confusing" and then the code refuses to build.  In effect you are introducing a dependency on your compiler.

Anyway, issue closed. Thanks for the fast response.

**Comment by 1uc** [comment]
Exactly why we turned it off; but when we did, this annoying bug with shadowing `padding` crept in. So now there's a flag to request `-Werror` (off by default) and we turn `-Werror` back on during CI to make it fail on warnings.
