### ISSUE TITLE
Any publication to cite

### ISSUE THREAD

**Issue by VictorEijkhout** [BlueBrain/HighFive#926]
If I want to refer to your project, do I cite the github page or is there a preferred publication? If so, please add that to your github main page.

**Comment by pramodk** [comment]
Hello @VictorEijkhout,

As of now, we do not have a DOI/publication available for citation. For now, please cite the GitHub repository. We anticipate having Zenodo artifacts for releases soon and will update the README with the DOI once available.

Thanks!

**Comment by alkino** [comment]
Hello @VictorEijkhout , we now have a Zenodo : https://zenodo.org/records/10679738
