### ISSUE TITLE
typo in migration doc

### ISSUE THREAD

**Issue by delpinux** [BlueBrain/HighFive#950]
Hi.

I just noticed a typo in migration doc [doc] `doc/migration_guide.md`
(since commit 83b13287af30)

Example in https://github.com/BlueBrain/HighFive/blob/master/doc/migration_guide.md#intentional-raw-read
```c++
double x = malloc(2*3 * sizeof(double));
dset.read_raw(x);
```
should read
```c++
double* x = malloc(2*3 * sizeof(double));
dset.read_raw(x);
```
May I suggest a more C++-ish version
```c++
double* x = new double[2*3];
dset.read_raw(x);
```

Thank you for your excellent job.

Regards,
Stéphane.

**Comment by 1uc** [comment]
Thank you for letting us know. How users allocate memory is not part of the message we're trying to convey, it's just a placeholder for: Somehow you have the address to the first byte of a contiguous sequence of doubles. It's naturally good advice, especially for non-trivial types.
