### ISSUE TITLE
Using traits in DataSpace::From()

### ISSUE THREAD

**Issue by akheir** [BlueBrain/HighFive#97]
We are trying to use HighFive library with **blaze** matrices (https://bitbucket.org/blaze-lib/blaze). HighFive is a very nicely written library so I was able to write few traits such as `array_dims` and `transform_read`... to make it work with blaze. But I couldn't do the same thing with `DataSpace::From()` since it doesn't use traits. This is not a serious issue since I can create DataSpace with a vector but It would be much nicer if we could use `DataSpace::From()` with blaze.

So is it possible to use traits in `DataSpace::From()` instead of creating a function for each input data?

**Comment by adevress** [comment]
Hi hapoo,

Indeed, this part of the API has not been done with traits yet. 

The good way to do would be to extend array_dims to do runtime array dimension computing. And use this logic in DataSpace::From. 

I would welcome a patch on that if you have the time for it. 

Concerning Blaze, you are welcome also if you want to merge conditional blaze support ( done like for boost.ublas ) inside HighFive too.

**Comment by hapoo** [comment]
Hi, I might as well do both. I will get back to you on this.

**Comment by alkino** [comment]
Is fixed by #384
