### ISSUE TITLE
dataspace.getDimension() for zero-dimensional data-space will cause out-of-bounds index 

### ISSUE THREAD

**Issue by hkaiser** [BlueBrain/HighFive#98]
Calling `dataspace.getDimensions()` for a data-space that is zero-dimensional will cause an out-of-bounds index access to `a std::vector` here: 

https://github.com/BlueBrain/HighFive/blob/master/include/highfive/bits/H5Dataspace_misc.hpp#L85

**Comment by adevress** [comment]
Thanks you very much for the bug report Hartmut.

We will fix that.

**Comment by adevress** [comment]
Fixed

**Comment by hkaiser** [comment]
Thanks a lot!
