### ISSUE TITLE
<HD5Ppublic.h> is missing

### ISSUE THREAD

**Issue by 8enjam1n** [BlueBrain/HighFive#983]
Hello everyone,

I'm currently revisiting an old C++ project as part of my studies. This project utilizes HighFive. I'm not very familiar with C++ compilation, but I know that the basic program uses a 'makefile' that looks like this:
```make
CC=g++
CFLAGS=-O2 -std=c++17 -Wall -pedantic
LDFLAGS=-I ./gcem/include -I ./stats/include -I ./HighFive/include -I /usr/include/hdf5

all : bayarac

bayarac : Model.o ARAinfARAinf.o BayesianEstimation.o AlphaComputed.o AlphaPrior.o T1.o PosteriorDistribution.o FailureIntensity.o FirstFailureTimePrior.o FirstFailureTimeT1.o FailuresNumber.o main.o
	$(CC) $(CFLAGS) -o bayarac Model.o ARAinfARAinf.o BayesianEstimation.o AlphaComputed.o AlphaPrior.o T1.o PosteriorDistribution.o FailureIntensity.o FirstFailureTimePrior.o FirstFailureTimeT1.o FailuresNumber.o main.o -lhdf5

Model.o : Model.cpp
	$(CC) $(CFLAGS) -c Model.cpp

ARAinfARAinf.o : ARAinfARAinf.cpp Model.cpp
	$(CC) $(CFLAGS) -c ARAinfARAinf.cpp Model.cpp

BayesianEstimation.o : BayesianEstimation.cpp Model.cpp
	$(CC) $(CFLAGS) $(LDFLAGS) -c BayesianEstimation.cpp Model.cpp

AlphaComputed.o : AlphaComputed.cpp BayesianEstimation.cpp
	$(CC) $(CFLAGS) $(LDFLAGS) -c AlphaComputed.cpp BayesianEstimation.cpp

AlphaPrior.o : AlphaPrior.cpp BayesianEstimation.cpp
	$(CC) $(CFLAGS) $(LDFLAGS) -c AlphaPrior.cpp BayesianEstimation.cpp

T1.o : T1.cpp BayesianEstimation.cpp
	$(CC) $(CFLAGS) $(LDFLAGS) -c T1.cpp BayesianEstimation.cpp

PosteriorDistribution.o : PosteriorDistribution.cpp Model.cpp
	$(CC) $(CFLAGS) -c PosteriorDistribution.cpp Model.cpp

FailureIntensity.o : FailureIntensity.cpp PosteriorDistribution.cpp
	$(CC) $(CFLAGS) $(LDFLAGS) -c FailureIntensity.cpp PosteriorDistribution.cpp

FirstFailureTimePrior.o : FirstFailureTimePrior.cpp PosteriorDistribution.cpp
	$(CC) $(CFLAGS) $(LDFLAGS) -c FirstFailureTimePrior.cpp PosteriorDistribution.cpp

FirstFailureTimeT1.o : FirstFailureTimeT1.cpp PosteriorDistribution.cpp
	$(CC) $(CFLAGS) $(LDFLAGS) -c FirstFailureTimeT1.cpp PosteriorDistribution.cpp

FailuresNumber.o : FailuresNumber.cpp PosteriorDistribution.cpp
	$(CC) $(CFLAGS) $(LDFLAGS) -c FailuresNumber.cpp PosteriorDistribution.cpp

main.o : main.cpp
	$(CC) $(CFLAGS) $(LDFLAGS) -c main.cpp

clean :
	rm bayarac *.o *.gch

```

I also know that the HighFive folder is located at the root of my project.

The problem is that when I compile with the 'make' command at the root of my project, I get an error stating that in 'PropertyList.h,' which is a .h file contained within HighFive, the inclusion of <HD5Ppublic.h> is missing. However, this inclusion refers to the HDF5 library, which I know is installed properly."

The error : 
```
In file included from ./HighFive/include/highfive/H5FileDriver.hpp:12,
                 from ./HighFive/include/highfive/H5File.hpp:14,
                 from main.cpp:18:
./HighFive/include/highfive/H5PropertyList.hpp:12:10: fatal error: H5Ppublic.h: Aucun fichier ou dossier de ce nom
   12 | #include <H5Ppublic.h>
      |          ^~~~~~~~~~~~~
compilation terminated.
make: *** [makefile:44 : main.o] Erreur 1
```
Thank you for your help.

**Comment by alkino** [comment]
You should give the full line of compilation because this file exists in hdf5 for sure.

**Comment by 8enjam1n** [comment]
Thanks for your help,

So i tried to use pkg-config and it gives to me : -I/usr/include/hdf5/serial -L/usr/lib/x86_64-linux-gnu/hdf5/serial -lhdf5

So i modified my makefile and now it looks like that :

``
CC=g++
CFLAGS=-O2 -std=c++17 -Wall -pedantic
LDFLAGS=-I ./gcem/include -I ./stats/include -I ./HighFive/include -I/usr/include/hdf5/serial -L/usr/lib/x86_64-linux-gnu/hdf5/serial -lhdf5

all : bayarac

bayarac : Model.o ARAinfARAinf.o BayesianEstimation.o AlphaComputed.o AlphaPrior.o T1.o PosteriorDistribution.o FailureIntensity.o FirstFailureTimePrior.o FirstFailureTimeT1.o FailuresNumber.o main.o
	$(CC) $(CFLAGS) -o bayarac Model.o ARAinfARAinf.o BayesianEstimation.o AlphaComputed.o AlphaPrior.o T1.o PosteriorDistribution.o FailureIntensity.o FirstFailureTimePrior.o FirstFailureTimeT1.o FailuresNumber.o main.o -lhdf5

Model.o : Model.cpp Model.hpp
	$(CC) $(CFLAGS) -c Model.cpp Model.hpp

ARAinfARAinf.o : ARAinfARAinf.cpp ARAinfARAinf.hpp Model.hpp
	$(CC) $(CFLAGS) -c ARAinfARAinf.cpp ARAinfARAinf.hpp Model.hpp

BayesianEstimation.o : BayesianEstimation.cpp BayesianEstimation.hpp Model.hpp
	$(CC) $(CFLAGS) $(LDFLAGS) -c BayesianEstimation.cpp BayesianEstimation.hpp Model.hpp

AlphaComputed.o : AlphaComputed.cpp AlphaComputed.hpp BayesianEstimation.hpp
	$(CC) $(CFLAGS) $(LDFLAGS) -c AlphaComputed.cpp AlphaComputed.hpp BayesianEstimation.hpp

AlphaPrior.o : AlphaPrior.cpp AlphaPrior.hpp BayesianEstimation.hpp
	$(CC) $(CFLAGS) $(LDFLAGS) -c AlphaPrior.cpp AlphaPrior.hpp BayesianEstimation.hpp

T1.o : T1.cpp T1.hpp BayesianEstimation.hpp
	$(CC) $(CFLAGS) $(LDFLAGS) -c T1.cpp T1.hpp BayesianEstimation.hpp

PosteriorDistribution.o : PosteriorDistribution.cpp PosteriorDistribution.hpp Model.hpp
	$(CC) $(CFLAGS) -c PosteriorDistribution.cpp PosteriorDistribution.hpp Model.hpp

FailureIntensity.o : FailureIntensity.cpp FailureIntensity.hpp PosteriorDistribution.hpp
	$(CC) $(CFLAGS) $(LDFLAGS) -c FailureIntensity.cpp FailureIntensity.hpp PosteriorDistribution.hpp

FirstFailureTimePrior.o : FirstFailureTimePrior.cpp FirstFailureTimePrior.hpp PosteriorDistribution.hpp
	$(CC) $(CFLAGS) $(LDFLAGS) -c FirstFailureTimePrior.cpp FirstFailureTimePrior.hpp PosteriorDistribution.hpp

FirstFailureTimeT1.o : FirstFailureTimeT1.cpp FirstFailureTimeT1.hpp PosteriorDistribution.hpp
	$(CC) $(CFLAGS) $(LDFLAGS) -c FirstFailureTimeT1.cpp FirstFailureTimeT1.hpp PosteriorDistribution.hpp

FailuresNumber.o : FailuresNumber.cpp FailuresNumber.hpp PosteriorDistribution.hpp
	$(CC) $(CFLAGS) $(LDFLAGS) -c FailuresNumber.cpp FailuresNumber.hpp PosteriorDistribution.hpp

main.o : main.cpp
	$(CC) $(CFLAGS) $(LDFLAGS) -c main.cpp

clean :
	rm bayarac *.o *.gch
``

but now i have this error : 

`
g++ -O2 -std=c++17 -Wall -pedantic -c ARAinfARAinf.cpp ARAinfARAinf.hpp Model.hpp
g++ -O2 -std=c++17 -Wall -pedantic -I ./gcem/include -I ./stats/include -I ./HighFive/include -I/usr/include/hdf5/serial -L/usr/lib/x86_64-linux-gnu/hdf5/serial -lhdf5 -c BayesianEstimation.cpp BayesianEstimation.hpp Model.hpp
g++ -O2 -std=c++17 -Wall -pedantic -I ./gcem/include -I ./stats/include -I ./HighFive/include -I/usr/include/hdf5/serial -L/usr/lib/x86_64-linux-gnu/hdf5/serial -lhdf5 -c AlphaComputed.cpp AlphaComputed.hpp BayesianEstimation.hpp
g++ -O2 -std=c++17 -Wall -pedantic -I ./gcem/include -I ./stats/include -I ./HighFive/include -I/usr/include/hdf5/serial -L/usr/lib/x86_64-linux-gnu/hdf5/serial -lhdf5 -c FailureIntensity.cpp FailureIntensity.hpp PosteriorDistribution.hpp
g++ -O2 -std=c++17 -Wall -pedantic -I ./gcem/include -I ./stats/include -I ./HighFive/include -I/usr/include/hdf5/serial -L/usr/lib/x86_64-linux-gnu/hdf5/serial -lhdf5 -c FirstFailureTimePrior.cpp FirstFailureTimePrior.hpp PosteriorDistribution.hpp
g++ -O2 -std=c++17 -Wall -pedantic -I ./gcem/include -I ./stats/include -I ./HighFive/include -I/usr/include/hdf5/serial -L/usr/lib/x86_64-linux-gnu/hdf5/serial -lhdf5 -c FirstFailureTimeT1.cpp FirstFailureTimeT1.hpp PosteriorDistribution.hpp
g++ -O2 -std=c++17 -Wall -pedantic -I ./gcem/include -I ./stats/include -I ./HighFive/include -I/usr/include/hdf5/serial -L/usr/lib/x86_64-linux-gnu/hdf5/serial -lhdf5 -c FailuresNumber.cpp FailuresNumber.hpp PosteriorDistribution.hpp
g++ -O2 -std=c++17 -Wall -pedantic -o bayarac Model.o ARAinfARAinf.o BayesianEstimation.o AlphaComputed.o AlphaPrior.o T1.o PosteriorDistribution.o FailureIntensity.o FirstFailureTimePrior.o FirstFailureTimeT1.o FailuresNumber.o main.o -lhdf5
Model.o: file not recognized: file format not recognized
collect2: error: ld returned 1 exit status
make: *** [makefile:8 : bayarac] Erreur 1
``
and if i ls in /usr/include/hdf5/serial i have:

``
kalicb@ljk-ad-03:/usr/include/hdf5/serial$ ll
total 1760
drwxr-xr-x 2 root root   4096 avril 17 09:55 ./
drwxr-xr-x 3 root root   4096 avril 17 09:55 ../
-rw-r--r-- 1 root root   3157 déc.   9  2021 H5AbstractDs.h
-rw-r--r-- 1 root root  25449 déc.   9  2021 H5ACpublic.h
-rw-r--r-- 1 root root  12724 déc.   9  2021 h5a.mod
-rw-r--r-- 1 root root   9720 déc.   9  2021 H5api_adpt.h
-rw-r--r-- 1 root root   5582 déc.   9  2021 H5Apublic.h
-rw-r--r-- 1 root root   2807 déc.   9  2021 H5ArrayType.h
-rw-r--r-- 1 root root   3155 déc.   9  2021 H5AtomType.h
-rw-r--r-- 1 root root   4281 déc.   9  2021 H5Attribute.h
-rw-r--r-- 1 root root   1770 déc.   9  2021 H5Classes.h
-rw-r--r-- 1 root root   3761 déc.   9  2021 H5CommonFG.h
-rw-r--r-- 1 root root   5099 déc.   9  2021 H5CompType.h
-rw-r--r-- 1 root root   3634 déc.   9  2021 H5CppDoc.h
-rw-r--r-- 1 root root   2089 déc.   9  2021 H5Cpp.h
-rw-r--r-- 1 root root   1760 déc.   9  2021 H5Cpublic.h
-rw-r--r-- 1 root root   2779 déc.   9  2021 H5DaccProp.h
-rw-r--r-- 1 root root   7086 déc.   9  2021 H5DataSet.h
-rw-r--r-- 1 root root   5757 déc.   9  2021 H5DataSpace.h
-rw-r--r-- 1 root root   7333 déc.   9  2021 H5DataType.h
-rw-r--r-- 1 root root   6426 déc.   9  2021 H5DcreatProp.h
-rw-r--r-- 1 root root  13875 déc.   9  2021 h5d.mod
-rw-r--r-- 1 root root   1931 déc.   9  2021 H5DOpublic.h
-rw-r--r-- 1 root root   9021 déc.   9  2021 H5Dpublic.h
-rw-r--r-- 1 root root  85607 déc.   9  2021 h5ds.mod
-rw-r--r-- 1 root root   2590 déc.   9  2021 H5DSpublic.h
-rw-r--r-- 1 root root   5497 déc.   9  2021 H5DxferProp.h
-rw-r--r-- 1 root root  10018 déc.   9  2021 h5e.mod
-rw-r--r-- 1 root root   3566 déc.   9  2021 H5EnumType.h
-rw-r--r-- 1 root root  22386 déc.   9  2021 H5Epubgen.h
-rw-r--r-- 1 root root   9027 déc.   9  2021 H5Epublic.h
-rw-r--r-- 1 root root   6857 déc.   9  2021 H5Exception.h
-rw-r--r-- 1 root root   1873 déc.   9  2021 H5f90i_gen.h
-rw-r--r-- 1 root root   1426 déc.   9  2021 H5f90i.h
-rw-r--r-- 1 root root   7219 déc.   9  2021 H5FaccProp.h
-rw-r--r-- 1 root root   4579 déc.   9  2021 H5FcreatProp.h
-rw-r--r-- 1 root root   1472 déc.   9  2021 H5FDcore.h
-rw-r--r-- 1 root root   1931 déc.   9  2021 H5FDdirect.h
-rw-r--r-- 1 root root   1488 déc.   9  2021 H5FDfamily.h
-rw-r--r-- 1 root root   3784 déc.   9  2021 H5FDhdfs.h
-rw-r--r-- 1 root root   3299 déc.   9  2021 H5FDlog.h
-rw-r--r-- 1 root root   2745 déc.   9  2021 H5FDmirror.h
-rw-r--r-- 1 root root   2550 déc.   9  2021 H5FDmpi.h
-rw-r--r-- 1 root root   2422 déc.   9  2021 H5FDmpio.h
-rw-r--r-- 1 root root   1782 déc.   9  2021 H5FDmulti.h
-rw-r--r-- 1 root root  17227 déc.   9  2021 H5FDpublic.h
-rw-r--r-- 1 root root   3330 déc.   9  2021 H5FDros3.h
-rw-r--r-- 1 root root   1321 déc.   9  2021 H5FDsec2.h
-rw-r--r-- 1 root root   3824 déc.   9  2021 H5FDsplitter.h
-rw-r--r-- 1 root root   1350 déc.   9  2021 H5FDstdio.h
-rw-r--r-- 1 root root   1389 déc.   9  2021 H5FDwindows.h
-rw-r--r-- 1 root root   5060 déc.   9  2021 H5File.h
-rw-r--r-- 1 root root   3493 déc.   9  2021 H5FloatType.h
-rw-r--r-- 1 root root  10989 déc.   9  2021 h5f.mod
-rw-r--r-- 1 root root    365 déc.   9  2021 h5fortkit.mod
-rw-r--r-- 1 root root   2324 déc.   9  2021 h5fortran_types.mod
-rw-r--r-- 1 root root  15029 déc.   9  2021 H5Fpublic.h
-rw-r--r-- 1 root root  63845 déc.   9  2021 h5_gen.mod
-rw-r--r-- 1 root root   9468 déc.   9  2021 h5global.mod
-rw-r--r-- 1 root root  11253 déc.   9  2021 h5g.mod
-rw-r--r-- 1 root root   7216 déc.   9  2021 H5Gpublic.h
-rw-r--r-- 1 root root   3119 déc.   9  2021 H5Group.h
-rw-r--r-- 1 root root   4002 déc.   9  2021 H5IdComponent.h
-rw-r--r-- 1 root root  84946 déc.   9  2021 h5im.mod
-rw-r--r-- 1 root root   9949 déc.   9  2021 h5i.mod
-rw-r--r-- 1 root root   3274 déc.   9  2021 H5IMpublic.h
-rw-r--r-- 1 root root   1622 déc.   9  2021 H5Include.h
-rw-r--r-- 1 root root   2573 déc.   9  2021 H5IntType.h
-rw-r--r-- 1 root root   4882 déc.   9  2021 H5Ipublic.h
-rw-r--r-- 1 root root   2704 déc.   9  2021 H5LaccProp.h
-rw-r--r-- 1 root root   3001 déc.   9  2021 H5LcreatProp.h
-rw-r--r-- 1 root root   1362 déc.   9  2021 H5LDpublic.h
-rw-r--r-- 1 root root   1756 déc.   9  2021 h5lib.mod
-rw-r--r-- 1 root root   2881 déc.   9  2021 H5Library.h
-rw-r--r-- 1 root root  12293 déc.   9  2021 h5l.mod
-rw-r--r-- 1 root root  18198 déc.   9  2021 H5Location.h
-rw-r--r-- 1 root root  10165 déc.   9  2021 H5Lpublic.h
-rw-r--r-- 1 root root  89631 déc.   9  2021 h5lt_const.mod
-rw-r--r-- 1 root root 127846 déc.   9  2021 h5lt.mod
-rw-r--r-- 1 root root  14181 déc.   9  2021 H5LTpublic.h
-rw-r--r-- 1 root root   1737 déc.   9  2021 H5MMpublic.h
-rw-r--r-- 1 root root   5844 déc.   9  2021 H5Object.h
-rw-r--r-- 1 root root   3004 déc.   9  2021 H5OcreatProp.h
-rw-r--r-- 1 root root  14274 déc.   9  2021 h5o.mod
-rw-r--r-- 1 root root  12759 déc.   9  2021 H5Opublic.h
-rw-r--r-- 1 root root 151496 déc.   9  2021 H5overflow.h
-rw-r--r-- 1 root root   7720 déc.   9  2021 H5PacketTable.h
-rw-r--r-- 1 root root   1528 déc.   9  2021 H5PLextern.h
-rw-r--r-- 1 root root   2402 déc.   9  2021 H5PLpublic.h
-rw-r--r-- 1 root root  21301 déc.   9  2021 h5p.mod
-rw-r--r-- 1 root root  29241 déc.   9  2021 H5Ppublic.h
-rw-r--r-- 1 root root  16005 déc.   9  2021 H5PredType.h
-rw-r--r-- 1 root root   5850 déc.   9  2021 H5PropList.h
-rw-r--r-- 1 root root   3861 déc.   9  2021 H5PTpublic.h
-rw-r--r-- 1 root root  21530 déc.   9  2021 H5pubconf.h
-rw-r--r-- 1 root root  13339 déc.   9  2021 H5public.h
-rw-r--r-- 1 root root  11702 déc.   9  2021 h5r.mod
-rw-r--r-- 1 root root   3794 déc.   9  2021 H5Rpublic.h
-rw-r--r-- 1 root root  11894 déc.   9  2021 h5s.mod
-rw-r--r-- 1 root root   7662 déc.   9  2021 H5Spublic.h
-rw-r--r-- 1 root root   3040 déc.   9  2021 H5StrType.h
-rw-r--r-- 1 root root  87063 déc.   9  2021 h5tb_const.mod
-rw-r--r-- 1 root root  89789 déc.   9  2021 h5tb.mod
-rw-r--r-- 1 root root   8419 déc.   9  2021 H5TBpublic.h
-rw-r--r-- 1 root root  14105 déc.   9  2021 h5t.mod
-rw-r--r-- 1 root root  27251 déc.   9  2021 H5Tpublic.h
-rw-r--r-- 1 root root   2468 déc.   9  2021 H5VarLenType.h
-rw-r--r-- 1 root root  16788 déc.   9  2021 H5version.h
-rw-r--r-- 1 root root   9672 déc.   9  2021 h5z.mod
-rw-r--r-- 1 root root  11228 déc.   9  2021 H5Zpublic.h
-rw-r--r-- 1 root root   3625 déc.   9  2021 hdf5.h
-rw-r--r-- 1 root root   1543 déc.   9  2021 hdf5_hl.h
-rw-r--r-- 1 root root  84559 déc.   9  2021 hdf5.mod
`

**Comment by 1uc** [comment]
The lines of:
```
g++ ...
```
doesn't include a line to generate `Model.o`. Could you please `make clean` and them `make`? It should delete all files including the allegedly corrupted `Model.o`; and then recompile them all, now with the correct flags.
